inveniosoftware/invenio-rdm-records

- .gitignore
- README.rst
- invenio_rdm_records/config.py
- invenio_rdm_records/permissions.py
- setup.py
Move all configuration related to records from `invenio-app-rdm`:
- Records REST
- Records Files
- Records Permissions
Along withhttps://github.com/inveniosoftware/invenio-app-rdm/pull/14 closes https://github.com/inveniosoftware/invenio-rdm-records/issues/11
> global: add records configuration and dependencies

- invenio_rdm_records/version.py
Just the release. I am merging this in when the build passes.
> release: 1.0.0a2

- invenio_rdm_records/cli.py
- setup.cfg
- setup.py
- tests/api/test_demo_cli.py
- tests/conftest.py
> cli: create fake records

- invenio_rdm_records/version.py
Merge and release as soon as #27 is merged.
> Release 1.0.0a3

- invenio_rdm_records/cli.py
- setup.py
~~Will fail until https://github.com/inveniosoftware/invenio-pidstore/pull/125 is merged and invenio-pidstore 1.1.0 is released.~~
invenio-pidstore 1.1.0 released
closes #29 ; closes #31
> cli: mint recordids with base32 provider

- invenio_rdm_records/config.py
- invenio_rdm_records/mappings/v6/records/record-v1.0.0.json
- invenio_rdm_records/mappings/v7/records/record-v1.0.0.json
Changes:
* Make `resource_type` of type `object` as agreed IRL. It is better for aggregations.
* Add simple facets configuration.
> global: december release fixes for UI

- invenio_rdm_records/marshmallow/json.py
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/contributors.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/creators.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/list_entities.html
> ui: fix if no identifiers + default icon

- invenio_rdm_records/theme/__init__.py
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/63
> theme: remove unnecessary version export

- invenio_rdm_records/marshmallow/json.py
- invenio_rdm_records/version.py
- tests/api/test_elasticsearch_mapping.py
- tests/api/test_serializers.py
> Release v0.10.1

- invenio_rdm_records/cli.py
- invenio_rdm_records/marshmallow/json.py
- invenio_rdm_records/metadata_extensions.py
- invenio_rdm_records/vocabularies/__init__.py
- invenio_rdm_records/vocabularies/resource_types.csv
- tests/api/conftest.py
- tests/api/data/resource_types.csv
- tests/api/test_schemas_json_dump.py
- tests/api/test_schemas_json_load.py
- dumps empty record for frontend
- dumps resource type vocabulary for frontend
- register icons in the resource type file + order resource type according to file 
There will be refactoring when we generalize to all other custom vocabularies.
> Dump vocabularies

- invenio_rdm_records/version.py
patch release to fix resource type typo in record landing page
> release: v0.11.1

- invenio_rdm_records/version.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/108
> release: v0.12.0

- MANIFEST.in
- invenio_rdm_records/theme/assets/semantic-ui/less/invenio_rdm_records/theme.less
- invenio_rdm_records/theme/assets/semantic-ui/less/invenio_rdm_records/variables.less
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/contact.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/contributors.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/creators.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/keywords.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/list_entities.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/side_bar.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/record_landing_page.html
- invenio_rdm_records/theme/webpack.py
- setup.py
> assets: migrating assets to less and fixing record landing page

- invenio_rdm_records/theme/assets/semantic-ui/js/invenio_rdm_records/rdmrecords.js
- invenio_rdm_records/theme/assets/semantic-ui/less/invenio_rdm_records/theme.less
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/doi.html
- invenio_rdm_records/version.py
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/116
Triggers: https://github.com/inveniosoftware/invenio-formatter/issues/72
> fix modal and release 0.13.2

- invenio_rdm_records/theme/templates/invenio_rdm_records/details/description.html
> ui: handle absent descriptions

- invenio_rdm_records/cli.py
- invenio_rdm_records/jsonschemas/records/record-v1.0.0.json
- invenio_rdm_records/mappings/v6/records/record-v1.0.0.json
- invenio_rdm_records/mappings/v7/records/record-v1.0.0.json
> datamodel: fix affiliation identifiers json+mappings

- invenio_rdm_records/marshmallow/__init__.py
- invenio_rdm_records/marshmallow/json.py
- invenio_rdm_records/resources.py
- invenio_rdm_records/serializers/__init__.py
- invenio_rdm_records/services.py
- requirements-devel.txt
- run-tests.sh
- setup.py
- tests/api/conftest.py
- tests/api/test_api_flow.py
- depends on https://github.com/inveniosoftware/invenio-records-resources/pull/28
- shows how search of published records would look like
- draft of bibliographic records not included (wait until creation implemented I think)
> api: lay out integration w/ invenio-records-resources

- invenio_rdm_records/version.py
Will merge as soon as CI passes
> release: v0.15.0

- invenio_rdm_records/version.py
> release: v0.18.2

- invenio_rdm_records/search.py
- invenio_rdm_records/services.py
- invenio_rdm_records/version.py
- have to use 'records' index rather than '*' to not crash because getting communities in record search.
Merging when passing.
> fix used search index + version bump

- invenio_rdm_records/cli.py
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/contributors.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/creators.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/description.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/doi.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/keywords.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/licenses.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/side_bar.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/record_landing_page.html
- invenio_rdm_records/version.py
opens https://github.com/inveniosoftware/invenio-rdm-records/issues/176
Current UI status:
> cli: fix demo data input data model and landing page

- invenio_rdm_records/jsonschemas/records/record-v1.0.0.json
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/179
> jsonschema: adapt to changes in internal data model

- invenio_rdm_records/errors.py
- invenio_rdm_records/marshmallow/json.py
- invenio_rdm_records/resources.py
- invenio_rdm_records/vocabularies/__init__.py
- invenio_rdm_records/vocabularies/vocabularies.py
- invenio_rdm_records/vocabularies/vocabulary.py
- tests/new_api/test_schemas_json_load.py
- tests/new_api/test_upload_errors.py
Error generation so far. There is still some work to make sure each field is generating proper error paths, but the base is there and with this I was able to get some frontend errors, solve them and publish a record.
co need:
- https://github.com/inveniosoftware/invenio-app-rdm/pull/293
- https://github.com/inveniosoftware/react-invenio-deposit/pull/56 (see here for screenshot)
Merging this when Travis passes so master on each repo is ready to be double-checked on your side and released by you.
> errors: generate errors from backend

- invenio_rdm_records/resources.py
- invenio_rdm_records/schemas/__init__.py
- invenio_rdm_records/schemas/links.py
- invenio_rdm_records/services.py
- invenio_rdm_records/version.py
* Searches only in draft records currently
> resources: add user records resource

- invenio_rdm_records/services/services.py
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/310
> services: adds post filtering for access_right

- invenio_rdm_records/cli.py
- invenio_rdm_records/resources/serializers.py
- invenio_rdm_records/services/schemas/__init__.py
- invenio_rdm_records/services/schemas/metadata.py
- invenio_rdm_records/services/schemas/ui.py
- setup.py
Depends on https://github.com/inveniosoftware/marshmallow-utils/pull/18
> serializers: serialize localized pub date

- invenio_rdm_records/resources/serializers.py
- invenio_rdm_records/theme/templates/invenio_rdm_records/record_landing_page.html
- tests/resources/test_resources_serializers.py
Branch to use with others to get https://github.com/inveniosoftware/invenio-app-rdm/issues/349 to work.
This includes commits from PR https://github.com/inveniosoftware/invenio-rdm-records/pull/228 (rebase + fix to ui icon tests)
> 349 title metadata changes

- invenio_rdm_records/theme/templates/invenio_rdm_records/record_landing_page.html
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/335
> records-ui: makes version label dependant of the fields existence

- invenio_rdm_records/theme/templates/invenio_rdm_records/details/contributors.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/creators.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/description.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/keywords.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/licenses.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/list_entities.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/side_bar.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/record_landing_page.html
- invenio_rdm_records/theme/views.py
> [WIP] ui: fix landing page

- invenio_rdm_records/theme/assets/semantic-ui/js/invenio_rdm_records/recordManagement.js
- invenio_rdm_records/theme/assets/semantic-ui/less/invenio_rdm_records/theme.less
- invenio_rdm_records/theme/templates/invenio_rdm_records/record_landing_page.html
- invenio_rdm_records/theme/webpack.py
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/336
> ui: add managment section in record landing page

- invenio_rdm_records/theme/templates/invenio_rdm_records/record_landing_page.html
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/363
> ui: aligns publication date vertically in landing page

- invenio_rdm_records/resources/serializers.py
- invenio_rdm_records/theme/assets/semantic-ui/js/invenio_rdm_records/rdmrecords.js
- invenio_rdm_records/theme/assets/semantic-ui/less/invenio_rdm_records/theme.less
- invenio_rdm_records/theme/assets/semantic-ui/less/invenio_rdm_records/variables.less
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/creators.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/details.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/keywords.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/licenses.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/list_entities.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/side_bar.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/macros/detail.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/record_landing_page.html
- invenio_rdm_records/theme/views.py
- tests/conftest.py
- tests/resources/test_resources_serializers.py
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/252
**Open Question**:
- Visibility: Should it be calculated in a different way? Or using the access right title is okay?
- Dates: I opted for using the same format as in the rest. However, the mockups display it like YYYY-MM-DD. Which is preferred?
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/340
The UI serializer adds a `resource_type_short` property.
**Open Question**:
- Removed the `vocabulary_subtitle` filter. However, `vocabulary_title` cannot be removed until it is clear how to deal with contributor roles (i.e. a list of them).
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/251
In addition, it only displays fields when present:
Full:
Just with some:
It also works with …
> More on landing page

- invenio_rdm_records/theme/templates/invenio_rdm_records/details/contributors.html
* Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/271
> ui: fixes contributors affiliations in landing page

- invenio_rdm_records/resources/serializers/ui/schema.py
- tests/conftest.py
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/388
> serializers: makes contributors existance optional

- invenio_rdm_records/theme/templates/invenio_rdm_records/details/side_bar.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/macros/version.html
> ui: fix publication date on versions side bar

- invenio_rdm_records/theme/templates/invenio_rdm_records/details/description.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/macros/detail.html
* Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/268
> ui: allows html in additional descriptions

- invenio_rdm_records/theme/templates/invenio_rdm_records/details/description.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/licenses.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/subjects.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/record_landing_page.html
- invenio_rdm_records/version.py
> fix: no description shape

- invenio_rdm_records/config.py
- invenio_rdm_records/ext.py
- invenio_rdm_records/theme/assets/semantic-ui/less/invenio_rdm_records/theme.less
- invenio_rdm_records/theme/templates/invenio_rdm_records/macros/files.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/record_landing_page.html
- invenio_rdm_records/theme/views.py
- invenio_rdm_records/utils.py
- invenio_rdm_records/version.py
* Styling additions for previewer and file list box
> (WIP) previewer: adjusts previewer template to latest records

- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v1.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v1.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v1.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v1.0.0.json
- invenio_rdm_records/resources/serializers/ui/schema.py
- invenio_rdm_records/services/schemas/metadata.py
- invenio_rdm_records/services/services.py
- invenio_rdm_records/version.py
- setup.py
- tests/resources/conftest.py
- tests/resources/test_resources_serializers.py
Inter dependent with https://github.com/inveniosoftware/invenio-app-rdm/pull/442 since
> service: add aggregations for languages

- LICENSE
- invenio_rdm_records/services/schemas/communities.py
- invenio_rdm_records/services/schemas/files.py
- invenio_rdm_records/services/schemas/metadata_extensions.py
- setup.py
- tests/records/test_elasticsearch_mapping.py
- tests/services/test_schemas_json_load.py
- tests/services/test_serializers.py
> Remove Invenio-Communities as a dependency

- invenio_rdm_records/cli.py
> cli: separate vocabulary and (demo) record creation

- invenio_rdm_records/services/schemas/metadata.py
- invenio_rdm_records/vocabularies/resource_type.py
- tests/conftest.py
- tests/services/schemas/conftest.py
- tests/services/schemas/test_metadata.py
- tests/services/schemas/test_resource_type.py
> schema: fix error message for resource_type

- invenio_rdm_records/cli.py
- invenio_rdm_records/records/jsonschemas/records/record-v1.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v1.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v1.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v1.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v1.0.0.json
- invenio_rdm_records/services/schemas/access.py
- tests/conftest.py
- tests/records/full-record.json
- tests/resources/conftest.py
- tests/services/schemas/test_access.py
- tests/services/test_demo_cli.py
closes #371 
updated for the new access schema:
* jsonschemas
* ES mappings
also started working on (still to be discussed):
* marshmallow schemas
* test data & test cases
> 371 access data structure

- MANIFEST.in
- invenio_rdm_records/fixtures/data/vocabularies/languages.py
- invenio_rdm_records/fixtures/data/vocabularies/languages.yaml
> Languages: create 'languages.yml' file

- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/systemfields/__init__.py
- invenio_rdm_records/records/systemfields/access/__init__.py
- invenio_rdm_records/records/systemfields/access/embargo.py
- invenio_rdm_records/records/systemfields/access/field.py
- invenio_rdm_records/records/systemfields/access/grants.py
- invenio_rdm_records/records/systemfields/access/owners.py
- invenio_rdm_records/records/systemfields/access/protection.py
- tests/conftest.py
- tests/records/systemfields/conftest.py
- tests/records/systemfields/test_access_systemfield.py
closes #372 
requires https://github.com/inveniosoftware/invenio-rdm-records/pull/379, because the system field uses the new data structures
> 372 access system field

- invenio_rdm_records/records/systemfields/access/field.py
- invenio_rdm_records/services/generators.py
- tests/services/test_generators.py
partially closes #376
**test failing reason**: requires new version of [invenio-records-permissions](https://github.com/inveniosoftware/invenio-records-permissions) to access ```AuthenticatedUser``` generator.
> generator: IfRestricted

- invenio_rdm_records/records/systemfields/access/field.py
- invenio_rdm_records/records/systemfields/access/grants.py
- invenio_rdm_records/services/components.py
- tests/conftest.py
- tests/records/systemfields/test_access_systemfield.py
- tests/services/components/conftest.py
- tests/services/components/test_access_component.py
> Access: service component for access control #374 

- invenio_rdm_records/records/systemfields/access/grants.py
- invenio_rdm_records/records/systemfields/access/owners.py
- invenio_rdm_records/services/generators.py
- setup.py
- tests/services/test_generators.py
> permissions: adds recordOwners need generator

- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/dumpers/__init__.py
- invenio_rdm_records/records/dumpers/access.py
- invenio_rdm_records/records/systemfields/access/grants.py
- invenio_rdm_records/services/schemas/access.py
- tests/records/dumpers/test_access_dumpers.py
closes #373 
**note**: requires the issue with `draft.dump()` in https://github.com/inveniosoftware/invenio-drafts-resources/blob/master/invenio_drafts_resources/services/records/service.py#L189 to be resolved, in order to work
> 373 es grant token dumper

- invenio_rdm_records/cli.py
- invenio_rdm_records/config.py
- invenio_rdm_records/fixtures/__init__.py
- invenio_rdm_records/fixtures/data/users.yaml
- invenio_rdm_records/fixtures/users.py
* since the AccessComponent checks if the record owners actually exist
and each record has to have at least one owner, at least one user is
required for demo records
> fixtures: add UsersFixture for setting up required users

- invenio_rdm_records/records/jsonschemas/records/record-v1.0.0.json
- invenio_rdm_records/records/systemfields/access/embargo.py
- invenio_rdm_records/services/schemas/access.py
> access: allow embargo properties to not be set

- invenio_rdm_records/services/permissions.py
- tests/conftest.py
- tests/resources/test_draft_file_permissions.py
- tests/resources/test_record_file_permissions.py
- tests/services/components/test_access_component.py
- closes #406 
- part of https://github.com/inveniosoftware/invenio-app-rdm/issues/577
> permissions: test files endpoints are protected

- invenio_rdm_records/cli.py
fix some issues in the demo-records setup
> cli: update creation of demo records

- invenio_rdm_records/services/permissions.py
add `SystemProcess()` to all permissions, except for `can_update` and `can_delete` that are still `Disable()`'d
> permissions: give most permissions to SystemProcess

- invenio_rdm_records/services/schemas/metadata.py
partially closes inveniosoftware/invenio-app-rdm#596
* use SanitizedHTML instead of SanitizedUnicode
> schema: change field type of metadata.description

- invenio_rdm_records/services/generators.py
- invenio_rdm_records/version.py
:warning: this is a critical fix otherwise publish fails
will release after tests pass
> critical fix for ifdraft

- invenio_rdm_records/services/schemas/metadata.py
- tests/services/schemas/test_creator_contributor.py
> schema: require at least 1 creator

- invenio_rdm_records/services/schemas/access.py
- invenio_rdm_records/services/schemas/utils.py
- tests/records/test_elasticsearch_mapping.py
- tests/services/schemas/test_access.py
- requires https://github.com/inveniosoftware/marshmallow-utils/pull/31
- closes https://github.com/inveniosoftware/marshmallow-utils/issues/28
> schema: use updated ISODateString for Embargo

- .github/workflows/tests.yml
- invenio_rdm_records/resources/serializers/ui/schema.py
- invenio_rdm_records/version.py
- tests/resources/test_resources_serializers.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/592
requires release of https://github.com/inveniosoftware/marshmallow-utils/pull/32
> serializer: add stripped description in UI json serializer

- AUTHORS.rst
- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/dumpers/access.py
- invenio_rdm_records/records/jsonschemas/records/parent-v1.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v2.0.0.json
- invenio_rdm_records/records/systemfields/__init__.py
- invenio_rdm_records/records/systemfields/access/__init__.py
- invenio_rdm_records/records/systemfields/access/field/__init__.py
- invenio_rdm_records/records/systemfields/access/field/parent.py
- invenio_rdm_records/records/systemfields/access/field/record.py
- invenio_rdm_records/records/systemfields/access/protection.py
- invenio_rdm_records/services/components.py
- invenio_rdm_records/services/generators.py
- invenio_rdm_records/services/schemas/access.py
- tests/conftest.py
- tests/records/dumpers/test_access_dumpers.py
- tests/records/full-record.json
- tests/records/systemfields/test_access_systemfield.py
- tests/resources/conftest.py
- tests/resources/test_resources.py
- tests/secret_links/test_sharing.py
- tests/services/components/test_access_component.py
- tests/services/schemas/test_access.py
- tests/services/test_generators.py
- tests/services/test_permissions_policy.py
> 434 split access

- invenio_rdm_records/resources/config.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/686
> record-versions: add response serializers

- invenio_rdm_records/services/components.py
- setup.py
- tests/services/components/test_metadata_component.py
> service: new version should not copy all fields

- invenio_rdm_records/resources/config.py
- invenio_rdm_records/services/config.py
closes inveniosoftware/invenio-app-rdm#707
> records-versions: add links for record

- invenio_rdm_records/services/schemas/__init__.py
- invenio_rdm_records/services/schemas/versions.py
> schemas: require edit permissions to dump versions.is_latest_draft

- invenio_rdm_records/resources/config.py
- tests/services/test_serialized_links.py
closes #438 
* add links to the secret links endpoint, as well as versions-related endpoints
> resources: add more links to record serialization

- invenio_rdm_records/resources/serializers/ui/schema.py
- tests/resources/test_resources_serializers.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/701
> ui: add serialization of version

- invenio_rdm_records/services/generators.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/719
> versions: fix version list when access with secret link

- invenio_rdm_records/resources/config.py
- tests/resources/test_serialized_links.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/725
> links: fix latest_html links

- invenio_rdm_records/services/schemas/parent/__init__.py
- invenio_rdm_records/services/schemas/parent/access.py
> 478 dont dump parent access

- invenio_rdm_records/resources/serializers/ui/schema.py
(closes inveniosoftware/invenio-app-rdm#652)
> serializers: fix aggregation labels

- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/result_items.py
- invenio_rdm_records/services/search_params.py
- invenio_rdm_records/services/services.py
- tests/records/dumpers/test_edtf_dumpers.py
- tests/services/test_sort.py
- depends on https://github.com/inveniosoftware/invenio-records-resources/pull/217
- depends on https://github.com/inveniosoftware/invenio-drafts-resources/pull/125
- just making it clearer
- probably merge along with other refactorings
> schemas: account for ServiceSchemaWrapper refactor

- invenio_rdm_records/cli.py
Fixes https://github.com/inveniosoftware/invenio-app-rdm/issues/717 (thus this could still happen if we disallow this from the backend)
> Set files as public and remove the embargo on the demo records

- invenio_rdm_records/services/schemas/parent/access.py
- tests/resources/test_resources.py
* Ensures that created/updated dates have UTC timezone information and
are ISO formatted.
Closes inveniosoftware/invenio-app-rdm#741
> services: fix created/updated REST API output

- invenio_rdm_records/services/components.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/pids/__init__.py
- invenio_rdm_records/services/pids/providers/__init__.py
- invenio_rdm_records/services/pids/providers/base.py
- invenio_rdm_records/services/pids/providers/datacite.py
- invenio_rdm_records/services/pids/providers/external.py
- invenio_rdm_records/services/schemas/__init__.py
- setup.py
- tests/services/components/test_external_pids_component.py
External PIDs component hooks using providers...
closes #507
> [WIP] service components: create pids using providers

- invenio_rdm_records/ext.py
- invenio_rdm_records/resources/__init__.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/services.py
- invenio_rdm_records/views.py
- setup.py
- tests/resources/test_resources.py
closes https://github.com/inveniosoftware/invenio-records-resources/issues/224
> resources: add pid reserve endpoint

- invenio_rdm_records/cli.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/dumpers/__init__.py
- invenio_rdm_records/records/dumpers/edtf.py
- invenio_rdm_records/records/dumpers/locations.py
- invenio_rdm_records/records/dumpers/pids.py
- invenio_rdm_records/records/jsonschemas/records/record-v2.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v2.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v2.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v2.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v2.0.0.json
- invenio_rdm_records/services/components.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/pids/__init__.py
- invenio_rdm_records/services/pids/providers/__init__.py
- invenio_rdm_records/services/pids/providers/base.py
- invenio_rdm_records/services/pids/providers/datacite.py
- invenio_rdm_records/services/pids/providers/external.py
- invenio_rdm_records/services/schemas/__init__.py
- setup.py
- tests/conftest.py
- tests/records/dumpers/test_pids_dumper.py
- tests/services/components/test_external_pids_component.py
- tests/services/schemas/test_pids.py
- tests/services/schemas/test_rdm_record_schema.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/508
This PR merges the ExternalPIDs functionality **disabled**, until more tests and integration is performed. In order to enable it follow the `PIDS-FIXME` comments and uncomment the corresponding code.
> External PIDs

- invenio_rdm_records/services/config.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/440
> search: Added nested_terms_filter for nested aggregations

- invenio_rdm_records/ext.py
- invenio_rdm_records/resources/__init__.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/services.py
- tests/resources/test_draft_file_permissions.py
- tests/resources/test_record_file_permissions.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/457
> services: allow to snapshot parent record files on new version

- invenio_rdm_records/services/schemas/__init__.py
- invenio_rdm_records/services/schemas/files.py
- tests/resources/test_resources.py
- tests/test_cli.py
fix the original nested attribute PR
> Nestedattr

- invenio_rdm_records/records/dumpers/access.py
- invenio_rdm_records/records/dumpers/edtf.py
- invenio_rdm_records/records/dumpers/locations.py
- invenio_rdm_records/records/dumpers/pids.py
> fix typos in docstrings

- invenio_rdm_records/resources/serializers/ui/schema.py
- tests/resources/serializers/test_ui_serializer.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/653
> UIserializer: Add embargo end date

- invenio_rdm_records/records/systemfields/access/field/record.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/536
> landingPage: Fix wrong classification of records

- invenio_rdm_records/services/services.py
* Fixes an issue where when import files from a previous version the
object versions would be created in the wrong bucket.
closes #553
> serivce: fix issue with importing files

- invenio_rdm_records/config.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/services/components.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/pids/providers/__init__.py
- invenio_rdm_records/services/pids/providers/base.py
- invenio_rdm_records/services/pids/providers/datacite.py
- invenio_rdm_records/services/pids/providers/unmanaged.py
- invenio_rdm_records/services/services.py
- tests/conftest.py
- tests/records/full-record.json
- tests/resources/test_resources.py
- tests/services/components/test_external_pids_component.py
- tests/services/pids/providers/test_base_pid_provider.py
- tests/services/pids/providers/test_datacite_pid_provider.py
- tests/services/schemas/test_rdm_record_schema.py
Requires #526 
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/544
> DOI testing and refactor

- invenio_rdm_records/records/systemfields/access/field/record.py
- needed for rdmv2 records to display in v3
> access: fix status pop (for version transition)

- invenio_rdm_records/services/pids/providers/datacite.py
closes #581 
Fixes two things:
- Sends only the `metadata` to DataCite
- In case of error, logs the specific error returned by DataCite in order to allow the user to know which field errored e.g.
```
WARNING:root:DataCite provider errored when updating DOI for 10.81088/datacite.bcv6s-a7034
WARNING:root:Error in publication_year: DOI 10.81088/datacite.bcv6s-a7034: [facet 'pattern'] The value '' is not accepted by the pattern '[\d]{4}'. at line 15, column 0
```
> pids: enhance error logging of datacite provider

- invenio_rdm_records/services/components/__init__.py
- invenio_rdm_records/services/components/access.py
- invenio_rdm_records/services/components/metadata.py
- invenio_rdm_records/services/components/parent.py
- invenio_rdm_records/services/components/pids.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/531
> Move components from file to package

- invenio_rdm_records/ext.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/__init__.py
- invenio_rdm_records/services/secret_links/__init__.py
- invenio_rdm_records/services/secret_links/service.py
- invenio_rdm_records/services/services.py
- tests/secret_links/test_sharing.py
closes #https://github.com/inveniosoftware/invenio-rdm-records/issues/530
> Secret Link as a subservice

- invenio_rdm_records/version.py
- invenio_rdm_records/views.py
- setup.py
- tests/test_invenio_rdm_records.py
closes inveniosoftware/invenio-records-resources#246
> ext: register services

- invenio_rdm_records/fixtures/__init__.py
- invenio_rdm_records/fixtures/demo.py
- invenio_rdm_records/fixtures/users.py
- invenio_rdm_records/fixtures/vocabularies.py
- invenio_rdm_records/vocabularies/convert_to_new_vocabulary.py
- tests/fixtures/app_data/users.yaml
- tests/fixtures/app_data/vocabularies.yaml
- tests/fixtures/app_data/vocabularies/resource_types.yaml
- tests/fixtures/conftest.py
- tests/fixtures/test_cli.py
- tests/fixtures/test_fixtures.py
- closes #606 
- closes #425 
- closes #426
> vocabularies: load custom users fixtures in app_data/

- tests/resources/test_resources.py
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/295
(⚠️ does not but it has to be linked)
Not done at records-resources level because there was no file test existing there and it was a bit more complicated to set up. It shows that the error comes from the front end.
> tests: test multiple files upload

- invenio_rdm_records/cli.py
- invenio_rdm_records/fixtures/users.py
- invenio_rdm_records/fixtures/vocabularies.py
- setup.py
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/854
* NEEDS release from v2.3.0  of invenio-communities
> cli: Rebuild communities index

- invenio_rdm_records/fixtures/users.py
- invenio_rdm_records/fixtures/vocabularies.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/854
> fixtures: Logging errors

- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/serializers/__init__.py
- invenio_rdm_records/resources/serializers/csl/__init__.py
- invenio_rdm_records/resources/serializers/csl/schema.py
- tests/resources/serializers/test_csl_serializer.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/625
> serializer: add CSL JSON 

- invenio_rdm_records/services/errors.py
- invenio_rdm_records/services/permissions.py
- invenio_rdm_records/services/services.py
- invenio_rdm_records/services/tasks.py
- tests/services/test_rdm_service.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/400
> celery: embargo updater

- invenio_rdm_records/resources/serializers/csl/schema.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/892
> serializer: CSL fix

- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/serializers/__init__.py
- invenio_rdm_records/resources/serializers/csl/__init__.py
- invenio_rdm_records/resources/serializers/csl/schema.py
- setup.py
- tests/conftest.py
- tests/resources/serializers/test_csl_serializer.py
- tests/services/conftest.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/646
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/651
* Add citation string serializer.
> CSL string serializer

- invenio_rdm_records/fixtures/tasks.py
duplicatied with `invenio_rdm_records.services.tasks:....`
> fixtures: remove duplicated task code

- invenio_rdm_records/fixtures/__init__.py
- invenio_rdm_records/fixtures/demo.py
- invenio_rdm_records/fixtures/vocabularies.py
- tests/fixtures/conftest.py
- tests/fixtures/data/vocabularies.yaml
- tests/fixtures/load_error/conflicting_module_A/__init__.py
- tests/fixtures/load_error/conflicting_module_A/fixtures/vocabularies/__init__.py
- tests/fixtures/load_error/conflicting_module_A/fixtures/vocabularies/vocabularies.yaml
- tests/fixtures/load_error/conflicting_module_B/fixtures/vocabularies/__init__.py
- tests/fixtures/load_error/conflicting_module_B/fixtures/vocabularies/vocabularies.yaml
- tests/fixtures/load_error/conftest.py
- tests/fixtures/load_error/test_vocabularies_load_error.py
- tests/fixtures/mock_module_A/__init__.py
- tests/fixtures/mock_module_A/fixtures/vocabularies/__init__.py
- tests/fixtures/mock_module_A/fixtures/vocabularies/subjects.yaml
- tests/fixtures/mock_module_A/fixtures/vocabularies/vocabularies.yaml
- tests/fixtures/mock_module_B/fixtures/vocabularies/__init__.py
- tests/fixtures/mock_module_B/fixtures/vocabularies/subjects.yaml
- tests/fixtures/mock_module_B/fixtures/vocabularies/vocabularies.yaml
- tests/fixtures/test_cli.py
- tests/fixtures/test_fixtures.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/677
> subjects: load from 1-app_data 2-extenions 3-this

- invenio_rdm_records/records/api.py
- invenio_rdm_records/resources/serializers/ui/schema.py
- tests/resources/serializers/test_ui_serializer.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/695
* needs https://github.com/inveniosoftware/invenio-records/pull/259
> vocabularies: adds resource_type for related_identifiers

- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/serializers/__init__.py
- invenio_rdm_records/resources/serializers/datacite/__init__.py
> serializers: datacite xml-serializer added

- invenio_rdm_records/ext.py
- invenio_rdm_records/records/dumpers/edtf.py
- invenio_rdm_records/resources/serializers/csl/__init__.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/secret_links/models.py
- invenio_rdm_records/services/components/pids.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/pids/providers/base.py
- invenio_rdm_records/services/pids/providers/datacite.py
- invenio_rdm_records/services/pids/providers/unmanaged.py
- invenio_rdm_records/services/schemas/metadata.py
- invenio_rdm_records/services/schemas/utils.py
- invenio_rdm_records/services/secret_links/service.py
- invenio_rdm_records/vocabularies/resource_type.py
- invenio_rdm_records/vocabularies/vocabularies.py
- invenio_rdm_records/vocabularies/vocabulary.py
- tests/services/components/test_external_pids_component.py
- tests/services/pids/providers/conftest.py
- tests/services/pids/providers/test_base_pid_provider.py
- tests/services/pids/providers/test_datacite_pid_provider.py
- tests/services/pids/providers/test_unmanaged_pid_provider.py
- tests/services/schemas/test_rdm_record_schema.py
- tests/services/test_rdm_service.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/580
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/847
> components, providers: implement PID duplicates validation

- invenio_rdm_records/fixtures/data/vocabularies.yaml
- invenio_rdm_records/fixtures/data/vocabularies/title_types.yaml
- invenio_rdm_records/fixtures/demo.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/jsonschemas/records/definitions-v1.2.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v4.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v4.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v4.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v4.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v4.0.0.json
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/resources/serializers/ui/schema.py
- invenio_rdm_records/services/schemas/metadata.py
- tests/conftest.py
- tests/fixtures/app_data/vocabularies.yaml
- tests/fixtures/app_data/vocabularies/title_types.yaml
- tests/fixtures/data/vocabularies/title_types.yaml
- tests/fixtures/test_cli.py
- tests/records/full-record.json
- tests/records/test_jsonschema.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/serializers/test_ui_serializer.py
- tests/resources/test_publish_errors.py
- tests/services/schemas/test_additional_title.py
- tests/services/test_rdm_service.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/691
> vocabularies: title type

- invenio_rdm_records/fixtures/data/vocabularies.yaml
- invenio_rdm_records/fixtures/data/vocabularies/description_types.yaml
- invenio_rdm_records/fixtures/demo.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/jsonschemas/records/definitions-v1.2.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v4.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v4.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v4.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v4.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v4.0.0.json
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/resources/serializers/ui/schema.py
- invenio_rdm_records/services/schemas/metadata.py
- tests/conftest.py
- tests/fixtures/data/vocabularies/description_types.yaml
- tests/fixtures/test_cli.py
- tests/records/full-record.json
- tests/records/test_jsonschema.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/serializers/test_ui_serializer.py
- tests/services/schemas/test_additional_description.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/696
> vocabularies: add description types

- invenio_rdm_records/fixtures/demo.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/jsonschemas/records/definitions-v2.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v4.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v4.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v4.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v4.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v4.0.0.json
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/services/schemas/metadata.py
- tests/conftest.py
- tests/records/full-record.json
- tests/records/test_jsonschema.py
- tests/records/test_relations_affiliations.py
- tests/records/test_relations_languages.py
- tests/resources/conftest.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/serializers/test_ui_serializer.py
- tests/services/schemas/test_affiliation.py
- tests/services/schemas/test_creator_contributor.py
requires https://github.com/inveniosoftware/invenio-records-resources/pull/271
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/680
> vocabularies: integrate affiliations with rdm data model

- invenio_rdm_records/fixtures/__init__.py
- invenio_rdm_records/fixtures/affiliations.py
- invenio_rdm_records/fixtures/data/affiliations.yaml
- invenio_rdm_records/fixtures/data/users.yaml
- invenio_rdm_records/fixtures/data/vocabularies.yaml
- invenio_rdm_records/fixtures/demo.py
- invenio_rdm_records/fixtures/fixture.py
- invenio_rdm_records/fixtures/users.py
- setup.py
- tests/fixtures/app_data/affiliations.yaml
- tests/fixtures/app_data/users.yaml
- tests/fixtures/test_fixtures.py
requires https://github.com/inveniosoftware/invenio-rdm-records/pull/684
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/681
demo affiliations with partners ROR, missing Data Futures, Cottage Labs, OpenAire, GEO, National Center for Data to Health (cd2h)
> affiliations loading

- invenio_rdm_records/fixtures/data/vocabularies.yaml
- invenio_rdm_records/fixtures/data/vocabularies/date_types.yaml
- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/jsonschemas/records/definitions-v2.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v4.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v4.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v4.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v4.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v4.0.0.json
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/resources/serializers/ui/schema.py
- invenio_rdm_records/services/schemas/metadata.py
- tests/conftest.py
- tests/records/full-record.json
- tests/records/test_jsonschema.py
- tests/resources/conftest.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/serializers/test_ui_serializer.py
- tests/resources/test_resources.py
- tests/services/schemas/test_dates.py
- tests/services/schemas/test_subject.py
- tests/services/schemas/test_vocabulary.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/700
> dates: Convert dates type to vocabulary

- invenio_rdm_records/records/api.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/706
> relations: share cache for affiliations

- invenio_rdm_records/fixtures/data/vocabularies.yaml
- invenio_rdm_records/fixtures/demo.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/resources/serializers/csl/schema.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/services/config.py
- tests/conftest.py
- tests/fixtures/app_data/vocabularies.yaml
- tests/fixtures/data/vocabularies.yaml
- tests/fixtures/load_error/conflicting_module_A/fixtures/vocabularies/vocabularies.yaml
- tests/fixtures/load_error/conflicting_module_B/fixtures/vocabularies/vocabularies.yaml
- tests/fixtures/load_error/test_vocabularies_load_error.py
- tests/fixtures/test_cli.py
- tests/fixtures/test_fixtures.py
- tests/resources/conftest.py
- tests/resources/serializers/test_datacite_serializer.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/705
> vocabulary: rename resourcetype

- invenio_rdm_records/fixtures/data/vocabularies.yaml
- invenio_rdm_records/fixtures/data/vocabularies/relation_types.yaml
- invenio_rdm_records/fixtures/demo.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/jsonschemas/records/definitions-v2.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v4.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v4.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v4.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v4.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v4.0.0.json
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/resources/serializers/ui/schema.py
- invenio_rdm_records/services/schemas/metadata.py
- tests/conftest.py
- tests/fixtures/data/vocabularies/relation_types.yaml
- tests/fixtures/test_cli.py
- tests/records/full-record.json
- tests/records/test_jsonschema.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/serializers/test_ui_serializer.py
- tests/services/schemas/test_related_identifier.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/695
> vocabulary: Converst relation_type to vocabulary

- invenio_rdm_records/resources/serializers/datacite/schema.py
* closes  https://github.com/inveniosoftware/invenio-rdm-records/issues/717
Subjects was not updated because will be change to custom vocabulary, if I am not mistaken.
> datacite: reuse read_all method

- invenio_rdm_records/ext.py
- invenio_rdm_records/fixtures/__init__.py
- invenio_rdm_records/fixtures/data/vocabularies.yaml
- invenio_rdm_records/fixtures/subjects.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/jsonschemas/records/definitions-v2.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v4.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v4.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v4.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v4.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v4.0.0.json
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/resources/serializers/ui/schema.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/schemas/metadata.py
- setup.py
- tests/conftest.py
- tests/records/full-record.json
- tests/records/test_relations_subjects.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/serializers/test_ui_serializer.py
- tests/resources/vocabularies/test_affiliations_vocabulary.py
- tests/resources/vocabularies/test_subjects_vocabulary.py
- tests/services/schemas/test_affiliation.py
- tests/services/schemas/test_subject.py
- requires https://github.com/inveniosoftware/invenio-vocabularies/issues/63
- closes #722
> vocabularies: integrate subjects as a custom vocabulary

- invenio_rdm_records/services/schemas/metadata.py
> schema: add missing translation

- invenio_rdm_records/resources/serializers/datacite/schema.py
- tests/resources/serializers/test_datacite_serializer.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/716
> serializer: DataCite affiliation uses read_many

- AUTHORS.rst
- invenio_rdm_records/services/components/pids.py
- invenio_rdm_records/services/pids/providers/base.py
- invenio_rdm_records/services/schemas/__init__.py
- invenio_rdm_records/services/schemas/access.py
- invenio_rdm_records/services/schemas/metadata.py
- invenio_rdm_records/services/services.py
- invenio_rdm_records/translations/messages.pot
- invenio_rdm_records/vocabularies/resource_type.py
- invenio_rdm_records/vocabularies/vocabulary.py
Todo:
* create a new resource for this module in transifex
* push the `.pot` file to created resource on transifex
> I18n: removing f-strings in order to extract messages

- invenio_rdm_records/config.py
- invenio_rdm_records/services/schemas/__init__.py
- invenio_rdm_records/services/schemas/metadata.py
- setup.py
- tests/conftest.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/services/schemas/test_creator_contributor.py
- tests/services/schemas/test_identifier.py
- tests/services/schemas/test_location.py
- tests/services/schemas/test_metadata.py
- tests/services/schemas/test_reference.py
- tests/services/schemas/test_related_identifier.py
- tests/services/schemas/test_rights.py
- tests/services/test_rdm_service.py
- requires https://github.com/inveniosoftware/marshmallow-utils/pull/40
- requires https://github.com/inveniosoftware/invenio-vocabularies/pull/71
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/535
> service: migrate schema to new IdentifierSchema api

- invenio_rdm_records/fixtures/data/vocabularies/relation_types.yaml
- tests/conftest.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/serializers/test_ui_serializer.py
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/741
> serialization: fix relation type datacite mapping

- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/jsonschemas/records/record-v4.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v4.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v4.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v4.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v4.0.0.json
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/resources/serializers/dublincore/schema.py
- invenio_rdm_records/resources/serializers/ui/schema.py
- invenio_rdm_records/services/schemas/metadata.py
- tests/conftest.py
- tests/records/full-record.json
- tests/records/test_jsonschema.py
- tests/resources/conftest.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/serializers/test_dublincore_serializer.py
- tests/resources/serializers/test_ui_serializer.py
- tests/services/schemas/test_rights.py
> rigths: allow vocab and free text values

- setup.py
reason: translations were not rendering.
> entypoint: adds i18n entypoint

- invenio_rdm_records/services/schemas/access.py
- invenio_rdm_records/translations/messages.pot
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/766
> embargo: fix error message

- invenio_rdm_records/resources/serializers/csl/schema.py
- tests/resources/serializers/test_csl_serializer.py
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/764
> serializers: fix csl creator schema name

- invenio_rdm_records/fixtures/data/vocabularies/date_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/description_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/relation_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/roles.yaml
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/resources/serializers/dublincore/schema.py
- invenio_rdm_records/resources/serializers/utils.py
- tests/fixtures/data/vocabularies/description_types.yaml
- tests/fixtures/data/vocabularies/relation_types.yaml
- tests/fixtures/data/vocabularies/roles.yaml
- closes #762
- refactor some methods
- fix a couple of subtle errors
> datacite: fix controlled vocabularies conversions

- invenio_rdm_records/config.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
- tests/resources/serializers/test_datacite_serializer.py
- identifiers correspondances added
- if no link, then no rightsURI key-value at all
> 762 more datacite controlled vocab

- invenio_rdm_records/records/api.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/760
* needs https://github.com/inveniosoftware/invenio-records/pull/264
> relation field: add check_value

- invenio_rdm_records/services/result_items.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/782
> services: remove SITE_HOSTNAME

- invenio_rdm_records/resources/serializers/ui/schema.py
- tests/resources/serializers/test_ui_serializer.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/984
> UIschema: add id to affiliations

- invenio_rdm_records/services/schemas/metadata.py
- tests/services/schemas/test_rights.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/751
> schema: adds locale validation to rights field

- invenio_rdm_records/fixtures/data/vocabularies/resource_types.yaml
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/785
> fixtures: add linkable/depositable tags to resource types

- invenio_rdm_records/services/schemas/metadata.py
* closes https://github.com/inveniosoftware/react-invenio-deposit/issues/367
* needs https://github.com/inveniosoftware/marshmallow-utils/pull/47
> schemas: allow error grouping in related identifiers

- invenio_rdm_records/fixtures/data/vocabularies/resource_types.yaml
- invenio_rdm_records/records/api.py
- invenio_rdm_records/version.py
- setup.py
- tests/conftest.py
- tests/fixtures/app_data/vocabularies/resource_types.yaml
- tests/fixtures/data/vocabularies/resource_types.yaml
- tests/resources/conftest.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/services/schemas/test_creator_contributor.py
* closes https://github.com/inveniosoftware/invenio-records/issues/266
* depends on https://github.com/inveniosoftware/invenio-records/pull/267
> relations: update value_check value

- invenio_rdm_records/proxies.py
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1044
> proxies: add proxy to records service

- invenio_rdm_records/services/secret_links/service.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/468
* needs https://github.com/inveniosoftware/invenio-drafts-resources/pull/157
> services: Drafts can manage secret_links

- invenio_rdm_records/services/config.py
- tests/resources/test_serialized_links.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/470
> config: Remove latest links from draft

- invenio_rdm_records/version.py
- setup.py
- setup: update celery tasks entrypoints
- release: v0.32.5
> cherry pick 0.32.5

- invenio_rdm_records/services/schemas/metadata.py
- schema: fix award validation message
> fix award validation msg

- invenio_rdm_records/resources/serializers/csl/__init__.py
- invenio_rdm_records/services/schemas/access.py
Addresses deprecation of 'missing' from https://github.com/inveniosoftware/invenio-app-rdm/issues/1112 .
> schema: use load_default instead of missing

- .github/workflows/tests.yml
- invenio_rdm_records/alembic/9e0ac518b9df_create_records_communities_m2m_table.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/jsonschemas/records/parent-v1.0.0.json
- invenio_rdm_records/records/models.py
- invenio_rdm_records/services/schemas/metadata.py
- invenio_rdm_records/services/schemas/parent/access.py
- setup.py
- tests/records/test_records_communities.py
- tests/test_alembic.py
Still missing updates of the index mappings.
Depends on https://github.com/inveniosoftware/invenio-communities/pull/361
> records: initial integration of communities

- invenio_rdm_records/requests/base.py
- invenio_rdm_records/requests/community_submission.py
- invenio_rdm_records/services/generators.py
- invenio_rdm_records/services/permissions.py
- run-tests.sh
- tests/services/test_service_review.py
will close https://github.com/inveniosoftware/invenio-rdm-records/issues/835
requires https://github.com/inveniosoftware/invenio-requests/pull/93
requires https://github.com/inveniosoftware/invenio-communities/pull/370
> Community submission permissions

- invenio_rdm_records/resources/config.py
> relations: handle api exception

- invenio_rdm_records/oai.py
- invenio_rdm_records/requests/community_submission.py
- invenio_rdm_records/resources/iiif.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/resources/serializers/csl/schema.py
- invenio_rdm_records/services/pids/service.py
- invenio_rdm_records/services/review/service.py
- invenio_rdm_records/services/secret_links/service.py
- invenio_rdm_records/services/services.py
- invenio_rdm_records/version.py
- setup.py
- tests/fixtures/test_fixtures.py
- tests/resources/serializers/test_csl_serializer.py
- tests/resources/test_iiif.py
- tests/resources/vocabularies/test_affiliations_vocabulary.py
- tests/secret_links/test_sharing.py
- tests/services/components/test_relations_component.py
- tests/services/pids/providers/test_datacite_pid_provider.py
- tests/services/pids/test_pids_service.py
- tests/services/pids/test_pids_tasks.py
- tests/services/test_service_review.py
- tests/services/test_sort.py
- services: order methods to pass identity first
- release: v0.34.2
> 258 refactor service method parameters order

- invenio_rdm_records/resources/serializers/ui/schema.py
Related to the issue **having english as non-default language.** [see also:](https://github.com/orgs/inveniosoftware/projects/84#card-72406948=)
> i18n: bugfix - the func was not called properly.

- invenio_rdm_records/translations/de/LC_MESSAGES/messages.po
- invenio_rdm_records/translations/messages.pot
- setup.cfg
i18n: extract & push tranlations
> babel: set use fuzzy true

- invenio_rdm_records/config.py
closes inveniosoftware/invenio-app-rdm#1303
> babelex: use lazy_gettext instead of _= lambda x:x

- invenio_rdm_records/resources/serializers/ui/schema.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1297
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details. …
> UISchema: add is_draft

- setup.cfg
- tests/conftest.py
> installation: bump communities and test deps

- .gitignore
- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/systemfields/__init__.py
- invenio_rdm_records/records/systemfields/draft_status.py
- invenio_rdm_records/requests/community_submission.py
- invenio_rdm_records/services/review/service.py
- invenio_rdm_records/services/schemas/__init__.py
- tests/services/test_service_review.py
> add draft status systemfield

- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v4.0.0.json
- invenio_rdm_records/requests/community_submission.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/services.py
- tests/resources/test_resources.py
- tests/services/conftest.py
- tests/services/test_rdm_service.py
Define tests for the created endpoint.
closes: inveniosoftware/invenio-communities#408
> Communities: create search community records endpoint

- invenio_rdm_records/fixtures/tasks.py
- tests/fixtures/test_cli.py
You can run `pipenv run invenio rdm-records demo invitation-requests` to create fake invitation requests.
> fixtures: add fake invitation requests

- invenio_rdm_records/__init__.py
> release: v0.35.6

- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/jsonschemas/records/record-v5.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v5.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v5.0.0.json
> add record v5

- invenio_rdm_records/fixtures/data/vocabularies.yaml
- invenio_rdm_records/fixtures/data/vocabularies/funders.yaml
- invenio_rdm_records/fixtures/vocabularies.py
- closes https://github.com/inveniosoftware/invenio-communities/issues/587
> fixtures: add funders and awards

- invenio_rdm_records/__init__.py
> release: v0.35.11

- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/pids/service.py
- invenio_rdm_records/services/results.py
- invenio_rdm_records/services/services.py
Missing draft expansion on PID/Review services
> service: allows record fields expansion

- invenio_rdm_records/resources/serializers/datacite/schema.py
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1555
The export was failing because the serialization was giving a `KeyError "number"` since the demo records have a funder but not an award.
> resources: fix award requirement in datacite serialization

- invenio_rdm_records/requests/community_submission.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1546
> request: index draft after request update

- babel.ini
- invenio_rdm_records/oaiserver/services/errors.py
- invenio_rdm_records/records/systemfields/draft_status.py
- invenio_rdm_records/translations/messages.pot
* remove jinja extensions
* update `.pot`
* use of `.format` instead of `f-string`
related inveniosoftware/invenio-app-rdm#1664
> i18n: update translation files

- invenio_rdm_records/cli.py
- invenio_rdm_records/fixtures/users.py
profile information will now be added if specified 
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1658
documentation updated in https://github.com/inveniosoftware/docs-invenio-rdm/pull/347
> users: add profile information to user fixture

- invenio_rdm_records/translations/de/LC_MESSAGES/messages.po
* add german translations
related inveniosoftware/invenio-app-rdm/issues/1664
> i18n: add german translations

- invenio_rdm_records/services/errors.py
- invenio_rdm_records/services/review/service.py
- tests/conftest.py
- tests/services/test_service_review.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1651
> review: verify record and community restrictions on submit

- invenio_rdm_records/resources/serializers/iiif/schema.py
- tests/resources/test_iiif_presentation_api.py
> IIIF: Put correct @id on image service sections

- invenio_rdm_records/fixtures/data/vocabularies.yaml
- invenio_rdm_records/resources/serializers/ui/__init__.py
- invenio_rdm_records/resources/serializers/ui/schema.py
- tests/resources/serializers/test_ui_serializer.py
* remove duplicated vocabularies definitio
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1518
> [NEEDS #invenio-vocabularies/pull/199]serializer: add constructor to UIJSONSerializer

- invenio_rdm_records/__init__.py
> release: v0.35.19

- AUTHORS.rst
- invenio_rdm_records/fixtures/data/vocabularies/community_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/date_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/description_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/relation_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/resource_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/title_types.yaml
Translation to German in the following files:
community_types.yaml
date_types.yaml
description_types.yaml
relation_types.yaml
resource_types.yaml
title_types.yaml
I only did some translations. Nothing else.
> i18n: Adds German translation for vocabularies

- invenio_rdm_records/resources/config.py
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/549
> errors: added error handler for inconsistent record access.

- invenio_rdm_records/fixtures/data/vocabularies/roles.yaml
Since @utnapischtim is busy, we agreed that I'm taking over fixing the issues mentioned in https://github.com/inveniosoftware/invenio-rdm-records/pull/889
Thus, the translations are reviewed and ready to be merged.
This PR substitutes https://github.com/inveniosoftware/invenio-rdm-records/pull/889 which can be closed after successfully merging this PR here.
> I18n: German translation of roles.yaml

- docs/api.rst
- invenio_rdm_records/cli.py
- invenio_rdm_records/ext.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/custom_fields.py
- invenio_rdm_records/services/components/custom_fields.py
- invenio_rdm_records/services/schemas/__init__.py
- invenio_rdm_records/services/schemas/metadata.py
- invenio_rdm_records/services/services.py
- tests/records/full-record.json
- tests/records/test_jsonschema.py
- requires https://github.com/inveniosoftware/invenio-communities/pull/770
- closes https://github.com/inveniosoftware/invenio-vocabularies/issues/205
Tests are passing in local except those also broken in master, see #1008
> custom fields: use vocabulary schema and fix tests

- .gitignore
- invenio_rdm_records/resources/resources.py
- tests/resources/test_publish_errors.py
> wip fix tests

- invenio_rdm_records/cli.py
- invenio_rdm_records/config.py
- tests/conftest.py
- tests/fixtures/test_cli.py
> config: convert dict to list

- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v5.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v5.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v5.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v5.0.0.json
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/993
> mappings: remove metadata extensions

- invenio_rdm_records/oaiserver/services/services.py
closes https://github.com/inveniosoftware/invenio-administration/issues/49
Note: set base branch to `feature/administration-oai` so it can be integrated with the most recent implementation of oai sets views. It can be changed later on when this PR is finished
> add query parameters to search OAI sets

- invenio_rdm_records/records/api.py
- requires https://github.com/inveniosoftware/invenio-records-resources/pull/387 (all testing is shown in this PR)
- closes https://github.com/inveniosoftware/invenio-records-resources/issues/385
> records: add custom fields dumper extension

- invenio_rdm_records/cli.py
> cli: fix cf validation on given fields

- invenio_rdm_records/__init__.py
> release: v0.36.4

- invenio_rdm_records/__init__.py
- invenio_rdm_records/cli.py
> cli: add support for prefix indices in custom fields commands

- invenio_rdm_records/administration/views/oai.py
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/LinksTable.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oai-details.js
* closes https://github.com/inveniosoftware/invenio-administration/issues/65
> administration: add form field ordering

- invenio_rdm_records/administration/views/oai.py
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/search/SearchResultItem.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/search/index.js
- invenio_rdm_records/fixtures/demo.py
- invenio_rdm_records/templates/semantic-ui/invenio_rdm_records/oai-details.html
- invenio_rdm_records/templates/semantic-ui/invenio_rdm_records/oai-search.html
* closes: inveniosoftware/invenio-administration#97
> Administration: fix broken profile menu in oai-pmh pages

- setup.cfg
> cli: remove custom fields from base commands

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/search/SearchResultItem.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/search/index.js
* https://github.com/inveniosoftware/invenio-administration/issues/94
> oaipmh: update admin list view

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/search/SearchResultItem.js
* closes https://github.com/inveniosoftware/invenio-administration/issues/106
* needs https://github.com/inveniosoftware/invenio-administration/pull/113
> [REQUIRES #inveniosoftware/invenio-administration/pull/113] oaipmh: add popup message to disable buttons

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/details/index.js
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1081
* needs https://github.com/inveniosoftware/invenio-administration/pull/116
> Oai administration detail

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/details/LinksTable.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/search/index.js
* Needs https://github.com/inveniosoftware/invenio-administration/pull/126
> [NEEDS #inveniosoftware/invenio-administration/pull/126]administration: fix import error

- invenio_rdm_records/__init__.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
- tests/conftest.py
Ported issue https://github.com/inveniosoftware/invenio-app-rdm/issues/1904
> release: v0.35.22

- invenio_rdm_records/requests/community_submission.py
* closes https://github.com/inveniosoftware/invenio-requests/issues/280
> requests: fix expire action

- invenio_rdm_records/oaiserver/services/permissions.py
* closes https://github.com/inveniosoftware/invenio-administration/issues/128
* needs https://github.com/inveniosoftware/invenio-administration/pull/131
> permissions: add administration to OAI

- invenio_rdm_records/administration/views/oai.py
- invenio_rdm_records/config.py
- setup.cfg
> OAI-PMH: Improve labelling

- invenio_rdm_records/__init__.py
- invenio_rdm_records/cli.py
Cherry picked to backport https://github.com/inveniosoftware/invenio-rdm-records/pull/1093
> release: v0.35.23

- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/deserializers/__init__.py
- invenio_rdm_records/resources/deserializers/errors.py
- invenio_rdm_records/resources/deserializers/rocrate/__init__.py
- invenio_rdm_records/resources/deserializers/rocrate/schema.py
- tests/resources/test_rocrate.py
* Closes #1100.
**Reminder**
2. You agree that you have the …
> resources: add RO-Crate deserializer

- .tx/config
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/details/CopyButton.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/details/LinksTable.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/details/index.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/search/DeleteModal.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/search/SearchResultItem.js
- invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records/i18next-scanner.config.js
- invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records/i18next.js
- invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records/messages/de/translations.json
- invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records/messages/el/translations.json
- invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records/messages/en/translations.json
- invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records/messages/index.js
- invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records/package-lock.json
- invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records/package.json
- invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records/scripts/compileCatalog.js
- invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records/scripts/initCatalog.js
- invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records/translations.pot
Reformat details links fetch
Add translations to javascript
closes: https://github.com/inveniosoftware/invenio-rdm-records/issues/1087
> Links: table refactor as class component 

- invenio_rdm_records/services/generators.py
- invenio_rdm_records/services/permissions.py
- setup.cfg
- tests/conftest.py
- closes #1119 
Tests are going to fail until the release chain is fixed (administration, drafts-resources and communities missing IIRC).
> Files fetching too

- invenio_rdm_records/records/jsonschemas/records/definitions-v2.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v4.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v5.0.0.json
- requires https://github.com/inveniosoftware/invenio-records-resources/pull/416
- closes https://github.com/inveniosoftware/invenio-records-resources/issues/408
> jsonschema: move file definition to records-resources

- invenio_rdm_records/oaiserver/services/config.py
- invenio_rdm_records/services/config.py
- related to https://github.com/inveniosoftware/invenio-records-resources/pull/424
- raises https://github.com/inveniosoftware/invenio-rdm-records/issues/1127
> services: fix service id config values

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/details/LinksTable.js
* closes: inveniosoftware/react-invenio-forms#168
> Axios: Centralize imports

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/details/index.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/search/SearchResultItem.js
* closes https://github.com/inveniosoftware/invenio-communities/issues/821
> administration: refactor oai sets view

- invenio_rdm_records/cli.py
- invenio_rdm_records/fixtures/__init__.py
- invenio_rdm_records/fixtures/communities.py
- invenio_rdm_records/fixtures/fixture.py
- invenio_rdm_records/fixtures/records.py
- invenio_rdm_records/fixtures/users.py
- invenio_rdm_records/utils.py
- tests/fixtures/app_data/communities.yaml
- tests/fixtures/app_data/records.yaml
- tests/fixtures/app_data/users.yaml
- tests/fixtures/conftest.py
- tests/fixtures/test_cli.py
- tests/fixtures/test_fixtures.py
* improve users fixtures by allowing user to be confirmed
* improved community fixtures by running the task as a celery task and allow to feature communities
* add records fixtures
* add and improved tests
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1132
* needs https://github.com/inveniosoftware/invenio-communities/pull/841
> fixtures: add records

- invenio_rdm_records/oaiserver/services/results.py
- invenio_rdm_records/services/pids/service.py
- invenio_rdm_records/services/results.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1987
> expand: pass identity when picking fields

- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/errors.py
- invenio_rdm_records/services/components/pids.py
- invenio_rdm_records/services/errors.py
- invenio_rdm_records/services/pids/manager.py
- invenio_rdm_records/services/pids/providers/base.py
- invenio_rdm_records/services/pids/providers/datacite.py
- invenio_rdm_records/services/pids/providers/external.py
- invenio_rdm_records/services/pids/service.py
- tests/conftest.py
- tests/resources/serializers/test_dublincore_serializer.py
- tests/resources/test_resources_pids.py
- tests/services/components/test_pids_component.py
- tests/services/pids/providers/test_datacite_pid_provider.py
- tests/services/pids/providers/test_external_pid_provider.py
- in turn this allows validation of publisher by DataciteProvider
- closes #1137
> providers: validate record according to provider [+]

- invenio_rdm_records/fixtures/tasks.py
Discussion on Discord: https://discord.com/channels/692989811736182844/704629170470125578/1042794935717478400
> Fix missing index prefix during creation of demo inclusion requests & invites

- invenio_rdm_records/services/pids/service.py
> doi: remove validation from discard action

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v1.3.0

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/config.py
- invenio_rdm_records/ext.py
- invenio_rdm_records/oaiserver/resources/config.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/services/config.py
- tests/resources/test_serialized_links.py
- resources: use ConfiguratorMixin for config
- records: add archive download feature flag
Depends on https://github.com/inveniosoftware/invenio-records-resources/pull/426.
Addresses https://github.com/inveniosoftware/invenio-app-rdm/issues/2037.
**Reminder** …
> Archive download feature flag

- invenio_rdm_records/services/services.py
*  closes inveniosoftware/invenio-app-rdm#1965
> communities: returns 404 when not found

- invenio_rdm_records/fixtures/demo.py
- invenio_rdm_records/oaiserver/services/services.py
- tests/services/pids/providers/test_datacite_pid_provider.py
- tests/services/schemas/test_access.py
- tests/services/schemas/test_metadata.py
* closes https://github.com/inveniosoftware/invenio-banners/issues/11
> utils: move search params parser to ivenio-records-resources

- invenio_rdm_records/fixtures/demo.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/serializers/__init__.py
- invenio_rdm_records/resources/serializers/geojson/__init__.py
- invenio_rdm_records/resources/serializers/geojson/schema.py
- invenio_rdm_records/services/services.py
- tests/resources/serializers/test_geojson_serializer.py
- tests/services/pids/providers/test_datacite_pid_provider.py
- tests/services/schemas/test_access.py
- tests/services/schemas/test_metadata.py
* can now export to geojson (for Points)
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1154
> serializers : geojson maping + testing

- invenio_rdm_records/ext.py
- invenio_rdm_records/resources/__init__.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/__init__.py
- invenio_rdm_records/services/communities/__init__.py
- invenio_rdm_records/services/communities/service.py
- invenio_rdm_records/services/iiif/__init__.py
- invenio_rdm_records/services/iiif/service.py
- invenio_rdm_records/services/services.py
- invenio_rdm_records/views.py
- setup.cfg
- tests/conftest.py
- tests/resources/test_resources_communities.py
- tests/resources/test_resources_review.py
- tests/services/test_service_communities.py
- tests/services/test_service_review.py
- tests/test_invenio_rdm_records.py
* adds a new resource /api/records/<pid>/communities
* creates stub methods
* extracts IIIF to a dedicated service
* extracts /api/communities/<pid>/records to a dedicated resource
> add record's communities new resource stubs

- invenio_rdm_records/resources/serializers/__init__.py
- invenio_rdm_records/resources/serializers/marcxml/__init__.py
- invenio_rdm_records/resources/serializers/marcxml/schema.py
- invenio_rdm_records/services/services.py
- tests/resources/serializers/test_marcxml_serializer.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1165
> serializer: marcxml + testing

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/details/LinksTable.js
- invenio_rdm_records/oai.py
- tests/conftest.py
- tests/test_oai.py
* added export for oai-pmh to marcxml
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1173
> oai-pmh: export for marcxml

- invenio_rdm_records/ext.py
- invenio_rdm_records/proxies.py
- invenio_rdm_records/resources/__init__.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/__init__.py
- invenio_rdm_records/services/communities/service.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/errors.py
- invenio_rdm_records/services/permissions.py
- invenio_rdm_records/services/schemas/community_records.py
- invenio_rdm_records/services/services.py
- invenio_rdm_records/views.py
- setup.cfg
- tests/conftest.py
- tests/resources/conftest.py
- tests/resources/test_resources_communities.py
- tests/resources/test_resources_review.py
- tests/services/test_service_communities.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1163
* needs https://github.com/inveniosoftware/invenio-records-resources/pull/441
> records: remove communities from record

- invenio_rdm_records/services/services.py
- tests/services/test_rdm_service.py
* Closes #1188.
**Reminder**
2. You agree that you have the …
> services: resolve community slugs for record search

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v2.2.0

- invenio_rdm_records/oai.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/serializers/csl/__init__.py
- invenio_rdm_records/resources/serializers/datacite/__init__.py
- invenio_rdm_records/resources/serializers/dublincore/__init__.py
- invenio_rdm_records/resources/serializers/geojson/__init__.py
- invenio_rdm_records/resources/serializers/iiif/__init__.py
- invenio_rdm_records/resources/serializers/marcxml/__init__.py
- invenio_rdm_records/resources/serializers/marcxml/schema.py
- invenio_rdm_records/services/pids/providers/datacite.py
- tests/resources/serializers/test_csl_serializer.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/serializers/test_dublincore_serializer.py
- tests/resources/serializers/test_geojson_serializer.py
- tests/resources/serializers/test_marcxml_serializer.py
- tests/resources/test_resources.py
- requires https://github.com/inveniosoftware/flask-resources/pull/107
- closes #1204
> resources: test record access and search for different content types

- invenio_rdm_records/contrib/thesis/__init__.py
- invenio_rdm_records/contrib/thesis/custom_fields.py
> contrib: added thesis custom field

- invenio_rdm_records/cli.py
- invenio_rdm_records/config.py
- invenio_rdm_records/ext.py
- invenio_rdm_records/resources/serializers/ui/fields.py
- invenio_rdm_records/services/generators.py
- invenio_rdm_records/services/permissions.py
- invenio_rdm_records/services/review/service.py
- tests/conftest.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/test_draft_file_permissions.py
Depends on https://github.com/inveniosoftware/invenio-drafts-resources/pull/221.
- global: fix misformatted strings
- services: add metadata-only toggle config
- Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2021.
**Reminder** …
> services: add metadata-only toggle config

- invenio_rdm_records/contrib/imprint/custom_fields.py
- invenio_rdm_records/contrib/journal/custom_fields.py
- invenio_rdm_records/contrib/meeting/custom_fields.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1230
> contrib: fixed title mappings to 'text'

- invenio_rdm_records/services/communities/components.py
- invenio_rdm_records/services/community_records/service.py
- invenio_rdm_records/services/errors.py
- invenio_rdm_records/services/review/service.py
- tests/conftest.py
- tests/services/conftest.py
- tests/services/test_service_communities.py
- requires https://github.com/inveniosoftware/invenio-communities/pull/895/
- requires https://github.com/inveniosoftware/invenio-communities/pull/913
- closes https://github.com/inveniosoftware/invenio-communities/issues/818
> communities: overwrite community access component

- invenio_rdm_records/ext.py
- invenio_rdm_records/requests/__init__.py
- invenio_rdm_records/requests/community_inclusion.py
- invenio_rdm_records/requests/decorators.py
- invenio_rdm_records/requests/resolver.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/resources/serializers/ui/schema.py
- invenio_rdm_records/services/communities/service.py
- invenio_rdm_records/services/community_inclusion/__init__.py
- invenio_rdm_records/services/community_inclusion/service.py
- invenio_rdm_records/services/community_records/service.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/errors.py
- invenio_rdm_records/services/permissions.py
- invenio_rdm_records/services/review/service.py
- setup.cfg
- tests/conftest.py
- tests/resources/conftest.py
- tests/resources/test_resources_communities.py
- tests/resources/test_resources_community_records.py
- tests/resources/test_resources_review.py
- tests/resources/test_serialized_links.py
- tests/services/conftest.py
- tests/services/test_service_communities.py
- tests/services/test_service_community_records.py
- tests/services/test_service_review.py
* closes inveniosoftware/invenio-app-rdm#2060
- https://github.com/inveniosoftware/invenio-rdm-records/pull/1178
- https://github.com/inveniosoftware/invenio-rdm-records/pull/1169
> records: add record to multiple communities

- invenio_rdm_records/resources/serializers/bibtex/schema.py
- invenio_rdm_records/resources/serializers/marcxml/schema.py
- invenio_rdm_records/resources/serializers/schemas.py
- tests/conftest.py
- tests/resources/serializers/test_bibtex_serializer.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/serializers/test_dublincore_serializer.py
- tests/resources/serializers/test_marcxml_serializer.py
- tests/test_oai.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2128
> serializers: fix legacy marcxml issue

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/details/LinksTable.js
- invenio_rdm_records/oai.py
- tests/conftest.py
- tests/test_oai.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1234
> OAI-PMH: export for DCAT-AP

- invenio_rdm_records/resources/config.py
- tests/conftest.py
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2149
> config: normalize names to plural (communities)

- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/communities/service.py
- invenio_rdm_records/services/schemas/community_records.py
- tests/services/test_service_communities.py
* adds comment and require_review to schema
* adds 400 http error on no added communities
* add test for comment and require_review
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2076
> services: update community records

- invenio_rdm_records/services/pids/errors.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2162
> translations: fix string format

- invenio_rdm_records/utils.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2069
> preferences: add support for preferences.locale

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/index.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2205
> deposit: export custom fields

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositRecordSerializer.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositRecordSerializer.test.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/errors/FormFeedback.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/ReferencesField/ReferencesField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/ReferencesField/ReferencesField.test.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/ReferencesField/index.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/ReferencesField/initialValues.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/index.js
- invenio_rdm_records/config.py
- invenio_rdm_records/services/schemas/metadata.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2169
Adds references field to deposit form
> deposit form: add references field to deposit form

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/ReferencesField/ReferencesField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/ReferencesField/initialValues.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2169
> deposit form: minor fix and clarification of naming

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunityListItem.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunitySelectionModal.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunitySelectionSearch.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/SubmitReviewModal.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2182
- Adds accessible close button to `<CommunitySelectionModal/>`
- Enables focusing on first input element when modal opens
> community modals: accessibility improvements

- invenio_rdm_records/contrib/imprint/processors.py
- invenio_rdm_records/contrib/journal/processors.py
- invenio_rdm_records/contrib/meeting/processors.py
- invenio_rdm_records/resources/serializers/csl/__init__.py
This PR adds the existing journal dumper to the citation string serializer, so it's consistent with the exported CSL file and formats correct citations on the landing page.
I also ported the CSL mappings for the book and event custom fields from Zenodo. https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/serializers/schemas/csl.py
I did an initial implementation straight in the CSL serializer, which is mostly a copy paste from Zenodo https://github.com/caltechlibrary/invenio-rdm-records/tree/zenodo-csl. Then I broke up the sections into the dumpers to generate this PR.
If you've added [third-party code (copy/pasted or new …
> Fix dumpers for citation and migrate Zenodo CSL

- invenio_rdm_records/records/mappings/os-v1/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v6.0.0.json
addresses https://github.com/zenodo/zenodo-rdm/issues/337
> files: change size mapping from integer to long

- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/jsonschemas/records/parent-v2.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/services/components/access.py
- tests/records/systemfields/test_permission_flags.py
* update jsonschema and mappings
* cover with tests
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1289
> Add permission_flags system field

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/fixtures/data/vocabularies/resource_types.yaml
- tests/fixtures/data/vocabularies/resource_types.yaml
> vocabularies: fix resourcetypes entries

- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/pids/providers/datacite.py
- tests/resources/test_serialized_links.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/57
> datacite: fix error logging

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.2.5

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.4.1

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/customFields/CustomField.js
* The issue here was that the serializer was not removing the _key property from CFs with nested Arrays.
* Adds recursive mapping function to properly remove _key property.
This PR fixes a bug where CustomFields that have nested Arrays fail to publish. This failure is due to the "_key" attribute that does not get removed as part of the serialization.
**Reminder**
By using GitHub, you …
> CustomFields: Fixes CF issues with nested Arrays

- invenio_rdm_records/fixtures/users.py
- invenio_rdm_records/utils.py
* made compatible with changes from this PR
* closes https://github.com/inveniosoftware/invenio-users-resources/issues/76
> refactor: changed method imput from element to list

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.5.0

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AccessField/components/ProtectionButtons.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2280
* closes https://github.com/inveniosoftware/react-invenio-deposit/issues/556
> DepositSerializer: fix deserialize record restriction

- invenio_rdm_records/config.py
- invenio_rdm_records/ext.py
- invenio_rdm_records/services/generators.py
- invenio_rdm_records/services/permissions.py
- invenio_rdm_records/tokens/__init__.py
- invenio_rdm_records/tokens/errors.py
- invenio_rdm_records/tokens/permissions.py
- invenio_rdm_records/tokens/resource_access.py
- invenio_rdm_records/tokens/scopes.py
- invenio_rdm_records/utils.py
- setup.cfg
- tests/conftest.py
- tests/tokens/conftest.py
- tests/tokens/test_feature_flag.py
- tests/tokens/test_resource_access.py
Note: tests still failing, but the feature itself works, so can be re-reviewed already.
* add feature flag
* handle token validation
* add corresponding permission and generator
* add corresponding scope
* cover with tests
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2233
Get image as anonymous user using valid RAT:
Get pdf file as anonymous user using valid RAT:
Some errors previews:
> tokens: implement resource access token

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.6.0

- .github/workflows/i18n-pull.yml
- .github/workflows/i18n-push.yml
- .tx/config
- run-i18n-tests.sh
ref https://github.com/inveniosoftware/invenio-i18n/issues/114
Migrate transifex config to be compatible with API v3.
Remove i18n workflows, which will be setup on the organization level.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including …
> transifex: update config

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/config.py
- invenio_rdm_records/services/config.py
* closes https://github.com/zenodo/who-rdm/issues/71
> conf: add variable to enable files by default

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.8.0

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.9.0

- invenio_rdm_records/requests/community_inclusion.py
- invenio_rdm_records/requests/community_submission.py
Closes https://github.com/inveniosoftware/invenio-requests/issues/328
Reorders actions to "accept", "decline", "cancel".
> available_actions: reorder actions

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.9.1

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.10.0

- invenio_rdm_records/services/pids/service.py
- Depends on https://github.com/inveniosoftware/invenio-drafts-resources/pull/237.
- Closes #1282.
> pids: resolve parent PIDs to latest record version

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.11.0

- invenio_rdm_records/records/jsonschemas/records/parent-v3.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/systemfields/access/field/parent.py
- invenio_rdm_records/services/schemas/parent/access.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1369
> Records: add `access settings` schema

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.12.0

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.12.1

- invenio_rdm_records/records/systemfields/access/__init__.py
- invenio_rdm_records/records/systemfields/access/access_settings.py
- invenio_rdm_records/records/systemfields/access/field/parent.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/access/service.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/schemas/parent/access.py
* implement service layer method to update parent access settings
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1384
> access: add endpoint for updating parent access settings

- tests/test_alembic.py
Skipping tests as suggested in: https://github.com/inveniosoftware/invenio-app-rdm/issues/2258
> tests: skip alembic tests

- setup.cfg
> celery: register access request task

- invenio_rdm_records/notifications/builders.py
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/community-submission.submit.jinja
- tests/conftest.py
- tests/services/test_service_review.py
closes #1380 
Remove request creator as explicit recipient.
Add filter for request creator. This will ensure that a user will not get notified, even if they are also an owner or a curator of the community.
Mark text for translation in template.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-servi …
> add userrecipientfilter to community inclusion notification builder

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunityListItem.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunitySelectionModal.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunitySelectionSearch.js
Closes https://github.com/zenodo/rdm-project/issues/171
Aligns community modal layout with the similar modals ("pending"/"manage").
> community modal: align layout with other community layouts

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/License/LicenseModal.js
* On submit now the values are removed
* 
Fixes the following:
https://github.com/inveniosoftware/invenio-rdm-records/assets/15194802/9f200ef7-62a9-406a-aea3-2cce5f769668
> deposit: fix license modal

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/DeleteButton/DeleteButton.js
closes https://github.com/zenodo/rdm-project/issues/196
Set color of discard button.
**Reminder**
2. You …
> deposit: set color of discard button

- invenio_rdm_records/services/generators.py
- invenio_rdm_records/services/permissions.py
> permissions: extract base permissions

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/NewVersionButton/NewVersionButton.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/FileUploader/FileUploader.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/FileUploader/FileUploaderArea.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/ReferencesField/ReferencesField.js
- invenio_rdm_records/config.py
- invenio_rdm_records/records/models.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/permissions.py
- tests/resources/test_files.py
- tests/services/files/conftest.py
- tests/services/files/test_revert_of_deleted_files_in_published_record.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2259
> service: lock record files conditionally

- invenio_rdm_records/services/permissions.py
> permissions: fix permissions about whom can add a record to community

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.14.0

- invenio_rdm_records/config.py
- invenio_rdm_records/services/communities/components.py
- invenio_rdm_records/services/components/verified.py
- invenio_rdm_records/services/permissions.py
- invenio_rdm_records/services/schemas/parent/__init__.py
- invenio_rdm_records/services/tasks.py
- tests/conftest.py
- tests/requests/conftest.py
- tests/requests/test_user_moderation_actions.py
- tests/services/components/conftest.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2359
> communities: add  moderation component

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.15.1

- invenio_rdm_records/resources/stats/event_builders.py
> stats: omit events from records without parent

- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/serializers/ui/schema.py
- invenio_rdm_records/services/components/__init__.py
- invenio_rdm_records/services/components/record_deletion.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/errors.py
- invenio_rdm_records/services/generators.py
- invenio_rdm_records/services/permissions.py
- invenio_rdm_records/services/schemas/record.py
- invenio_rdm_records/services/schemas/tombstone.py
- invenio_rdm_records/services/services.py
- tests/services/test_record_deletion.py
Requires https://github.com/inveniosoftware/invenio-drafts-resources/pull/246 in order to properly filter out deleted records from the user's dashboard.
> Record deletion: service workflows

- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/dumpers/__init__.py
- invenio_rdm_records/records/dumpers/files.py
- tests/conftest.py
- tests/records/dumpers/test_files_dumpers.py
requires https://github.com/inveniosoftware/invenio-records-resources/pull/492
requires https://github.com/inveniosoftware/invenio-records/pull/314
closes https://github.com/zenodo/rdm-project/issues/166
> systemfield: add files field that restricts files count dumping

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.17.0

- .github/workflows/tests-feature.yml
- .github/workflows/tests.yml
- invenio_rdm_records/requests/access/requests.py
- invenio_rdm_records/requests/community_inclusion.py
- invenio_rdm_records/requests/community_submission.py
- invenio_rdm_records/requests/entity_resolvers.py
- invenio_rdm_records/services/access/service.py
- invenio_rdm_records/services/communities/service.py
- invenio_rdm_records/services/components/pids.py
- invenio_rdm_records/services/review/service.py
- tests/resources/test_resources_communities.py
- tests/services/test_service_review.py
Requires: https://github.com/inveniosoftware/invenio-drafts-resources/pull/249
Tests are passing locally, they will pass here after PR in `drafts-resources` is merged and released.
> Resolve record instead of draft

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.18.0

- invenio_rdm_records/contrib/codemeta/custom_fields.py
- invenio_rdm_records/contrib/imprint/custom_fields.py
- invenio_rdm_records/contrib/journal/custom_fields.py
- invenio_rdm_records/contrib/thesis/custom_fields.py
Closes https://github.com/zenodo/rdm-project/issues/229
> custom fields: update namespace values

- invenio_rdm_records/contrib/imprint/custom_fields.py
- invenio_rdm_records/contrib/journal/custom_fields.py
Closes [Issue #201](https://github.com/zenodo/rdm-project/issues/201)
> fixed error message formatting issue

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.20.0

- invenio_rdm_records/requests/entity_resolvers.py
> entity_resolvers: add missing ghost_record representation

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.20.1

- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v6.0.0.json
Closes https://github.com/zenodo/rdm-project/issues/229
> Add acronym to awards

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.21.0

- invenio_rdm_records/alembic/faf0cefa79a0_create_record_quota_tables.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/models.py
- invenio_rdm_records/services/permissions.py
- invenio_rdm_records/services/services.py
> service: set records and user quota

- invenio_rdm_records/services/services.py
> service: refactor set_quota method

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositApiClient.js
- invenio_rdm_records/resources/resources.py
> resources: remove response handler from submit review

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.23.1

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/SubmitReviewModal.js
* closes https://github.com/zenodo/rdm-project/issues/168
Previews:
Case 1: record is already published
Case 2: record is not published yet (old logic)
Case 3: record is already published (community is direct publish)
Case 4: record is not published yet (community is direct publish):
> community submission: fix modal text for different cases

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.24.0

- invenio_rdm_records/services/permissions.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2430
> Quota drafts

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.25.0

- invenio_rdm_records/services/access/service.py
- invenio_rdm_records/tokens/errors.py
- invenio_rdm_records/tokens/resource_access.py
- invenio_rdm_records/utils.py
- tests/tokens/test_resource_access.py
- access: remove duplicate record resolve
- rat: improve error handling for secret link clashes
> RAT handling fixes

- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/resources.py
closes https://github.com/zenodo/rdm-project/issues/258
> resources: add etag headers

- invenio_rdm_records/records/systemfields/deletion_status.py
- invenio_rdm_records/resources/args.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/generators.py
- invenio_rdm_records/services/permissions.py
- invenio_rdm_records/services/search_params.py
- invenio_rdm_records/services/services.py
- tests/requests/test_user_moderation_actions.py
* services: config admin parameter to allow seeing deleted records
only on the administration panel
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1494
> services: filter deleted records in search by permissions

- invenio_rdm_records/services/config.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2443
> links: return parent_doi for both records and drafts

- invenio_rdm_records/records/api.py
- invenio_rdm_records/services/components/__init__.py
- invenio_rdm_records/services/config.py
closes https://github.com/zenodo/rdm-project/issues/42
> services: added record components config support.

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.27.0

- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/communities/components.py
- invenio_rdm_records/services/services.py
So that the community deletion actually works
> Communities: Add community deletion service component

- invenio_rdm_records/services/sort.py
* partially closes https://github.com/zenodo/rdm-project/issues/177
> service: fix config sort object being wrongly updated

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsModal.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/License/LicenseModal.js
- invenio_rdm_records/resources/serializers/marcxml/schema.py
Partially Closes Issue [#2455](https://github.com/inveniosoftware/invenio-app-rdm/issues/2455)
**Reminder**
1. You license your contribution under the same terms as the current repository’s …
> ui: added focus to input fields in modals

- invenio_rdm_records/records/stats/templates/aggregations/aggr_file_download/os-v1/aggr-file-download-v1.0.0.json
- invenio_rdm_records/records/stats/templates/aggregations/aggr_file_download/os-v2/aggr-file-download-v1.0.0.json
- invenio_rdm_records/records/stats/templates/aggregations/aggr_file_download/v7/aggr-file-download-v1.0.0.json
- invenio_rdm_records/records/stats/templates/aggregations/aggr_record_view/os-v1/aggr-record-view-v1.0.0.json
- invenio_rdm_records/records/stats/templates/aggregations/aggr_record_view/os-v2/aggr-record-view-v1.0.0.json
- invenio_rdm_records/records/stats/templates/aggregations/aggr_record_view/v7/aggr-record-view-v1.0.0.json
- invenio_rdm_records/records/stats/templates/events/file_download/os-v1/file-download-v1.0.0.json
- invenio_rdm_records/records/stats/templates/events/file_download/os-v2/file-download-v1.0.0.json
- invenio_rdm_records/records/stats/templates/events/file_download/v7/file-download-v1.0.0.json
- invenio_rdm_records/records/stats/templates/events/record_view/os-v1/record-view-v1.0.0.json
- invenio_rdm_records/records/stats/templates/events/record_view/os-v2/record-view-v1.0.0.json
- invenio_rdm_records/records/stats/templates/events/record_view/v7/record-view-v1.0.0.json
- invenio_rdm_records/services/tasks.py
- setup.cfg
This addresses https://github.com/zenodo/rdm-project/issues/203
It requires changes in three modules.
* Stats: create a new index keeping track of the statistics that have been recalculated
* Rdm-record: create a new task that reindexes all the documents identified in the previous step
* invenio-app-rdm: Define the task
Please, let me know it things should be moved around
**Reminder** …
> stats: Reindex documents after the stats have been calculated

- invenio_rdm_records/services/config.py
> communities-records: set correct links

- invenio_rdm_records/services/config.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2467
> versions: add status param interpreter

- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/communities/service.py
- invenio_rdm_records/services/config.py
* closes https://github.com/zenodo/rdm-project/issues/188
> communities: add resource and service handlers for setting default community

- invenio_rdm_records/ext.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/services/files/__init__.py
- invenio_rdm_records/services/files/service.py
- invenio_rdm_records/services/permissions.py
- tests/resources/test_files.py
- tests/resources/test_media_files.py
- tests/services/files/test_deleted_record_files.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1479
> global: move exceptions to invenio-records-resources

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.31.0

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/state/actions/deposit.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/state/reducers/deposit.js
* closes https://github.com/zenodo/rdm-project/issues/244
> deposit form: report invalid value errors on each draft save

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AffiliationsField/AffiliationsField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsIdentifiers.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsModal.js
Closes Issue #1506 
https://github.com/inveniosoftware/invenio-rdm-records/assets/51617644/82118f25-e022-45a1-9ffe-12765b16815d
**Reminder**
1. You license your contribution under the same terms …
> deposit form: Added ror selection in organization

- invenio_rdm_records/resources/serializers/ui/schema.py
Partially closes Issue [#263](https://github.com/zenodo/rdm-project/issues/263)
**Reminder**
2. You …
> tombstone: changed removed_by return value

- invenio_rdm_records/cli.py
- invenio_rdm_records/oaiserver/services/services.py
- tests/services/test_oai_service.py
- Closes https://github.com/zenodo/rdm-project/issues/193
- Addresses https://github.com/zenodo/rdm-project/issues/277
> oaiserver: add rebuild index method

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsModal.js
Removed the organization from being added to it's own affiliation
**Reminder** …
> ui: removed organization from affiliation

- invenio_rdm_records/oai.py
Part of https://github.com/zenodo/rdm-project/issues/278
> oai: rename format etree methods logically

- invenio_rdm_records/services/components/pids.py
- invenio_rdm_records/services/github/metadata.py
- invenio_rdm_records/services/pids/manager.py
- invenio_rdm_records/services/pids/providers/base.py
- invenio_rdm_records/services/pids/providers/datacite.py
- invenio_rdm_records/services/services.py
- tests/fake_datacite_client.py
- tests/services/pids/test_pids_tasks.py
* datacite: restore DOI on restore record
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1531
> datacite: hide DOI on delete record

- invenio_rdm_records/records/systemfields/access/grants.py
- invenio_rdm_records/utils.py
* closes https://github.com/zenodo/zenodo-rdm/issues/590
> datastore: prevent autoflush on search

- invenio_rdm_records/services/services.py
Fixes issue where published records with a draft is not showing up under My uploads.
> services: fix search_drafts query

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/services/services.py
> release: v4.36.3

- invenio_rdm_records/services/search_params.py
> service: remove dependency on current_user

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.36.4

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/.prettierrc
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositBootstrap.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/FileUploader/FileUploaderArea.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/state/actions/files.js
closes https://github.com/zenodo/rdm-project/issues/370
> Allow users to delete pending files

- .gitignore
- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.36.5

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.36.6

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.36.8

- invenio_rdm_records/resources/serializers/ui/fields.py
- invenio_rdm_records/services/github/metadata.py
* https://zenodo-sentry.web.cern.ch/sentry/zenodo-rdm/issues/29447744/?environment=production&referrer=alert_email
> serializers: fix wrongly used get

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsModal.js
- invenio_rdm_records/resources/serializers/ui/schema.py
> deposit: fix required identifiers for creators

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.36.9

- invenio_rdm_records/records/mappings/os-v1/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v6.0.0.json
*closes https://github.com/zenodo/rdm-project/issues/303
> search: add list of default fields used in a query

- invenio_rdm_records/resources/serializers/ui/fields.py
> access: relax serialization check

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.36.10

- invenio_rdm_records/records/dumpers/edtf.py
- invenio_rdm_records/resources/serializers/csl/schema.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/resources/serializers/schemaorg/schema.py
- invenio_rdm_records/resources/serializers/ui/schema.py
- setup.cfg
Closes https://github.com/zenodo/rdm-project/issues/328
> Use parse_edtf from babel-edtf

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/errors/FormFeedback.js
closes https://github.com/zenodo/rdm-project/issues/345
> subjects: validate that values are unique

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.37.3

- invenio_rdm_records/notifications/builders.py
- invenio_rdm_records/services/review/service.py
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/community-submission.accept.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/community-submission.cancel.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/community-submission.decline.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/community-submission.expire.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/community-submission.submit.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/guest-access-request-token.create.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/guest-access-request.accept.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/guest-access-request.submit.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/user-access-request.accept.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/user-access-request.decline.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/user-access-request.submit.jinja
Updated the templates for notification emails
e.g.
**Reminder** …
> emails: updated templates

- invenio_rdm_records/resources/serializers/marcxml/schema.py
- tests/resources/serializers/test_marcxml_serializer.py
* closes https://github.com/zenodo/rdm-project/issues/448
> serializers: fix marcxml awards serializer

- invenio_rdm_records/templates/semantic-ui/invenio_notifications/user-access-request.submit.jinja
Closes https://github.com/zenodo/rdm-project/issues/408
> user access request e-mail: include requestor email address

- invenio_rdm_records/requests/entity_resolvers.py
> entity: catch soft deleted draft

- invenio_rdm_records/resources/config.py
- invenio_rdm_records/services/config.py
- tests/resources/test_files.py
- tests/resources/test_iiif_image_api.py
- tests/resources/test_iiif_presentation_api.py
Closes Issue [#363](https://github.com/zenodo/rdm-project/issues/363)
**Reminder** …
> files: updating url  encoding

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.38.1

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v4.38.2

- invenio_rdm_records/oai.py
- invenio_rdm_records/services/services.py
- tests/conftest.py
- tests/oaiserver/test_oaipmh.py
- tests/resources/serializers/test_marcxml_serializer.py
- oaiserver: fix record loading for DB results
- tests: add OAI-PMH endpoint smoke tests
- closes: https://github.com/zenodo/rdm-project/issues/484
> OAI-PMH fix and tests

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsModal.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/FileUploader/FileUploaderArea.js
Closes [#476](https://github.com/zenodo/rdm-project/issues/476)
**Reminder**
2. You agree that you have …
> fix: upload going blank on translation

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/License/LicenseModal.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/License/LicenseSearchBar.js
Closes https://github.com/zenodo/rdm-project/issues/213
**Reminder**
2. You agree that you have the …
> ui: deposit: fields: license: Custom SearchBar

- invenio_rdm_records/records/jsonschemas/records/definitions-v2.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v6.0.0.json
- tests/records/test_jsonschema.py
- tests/records/test_relations_languages.py
* closes https://github.com/zenodo/rdm-project/issues/437
> jsonschema: remove unique items constrainsts

- invenio_rdm_records/resources/serializers/bibtex/schema.py
- invenio_rdm_records/resources/serializers/bibtex/schema_formats.py
- tests/resources/serializers/test_bibtex_serializer.py
closes https://github.com/zenodo/rdm-project/issues/494
> bibtex: added doi and url fields.

- invenio_rdm_records/resources/serializers/dcat/schema.py
* closes https://github.com/zenodo/rdm-project/issues/518
> resources: fix dcat serializer for restricted record files

- invenio_rdm_records/notifications/builders.py
* closes https://github.com/zenodo/rdm-project/issues/411
> notifications: send community inclusion emails to community managers

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AffiliationsField/AffiliationsField.js
* closes https://github.com/zenodo/rdm-project/issues/539
> affiliations: fix serialization

- tests/conftest.py
- tests/oaiserver/test_oaipmh.py
Update following: https://github.com/inveniosoftware/invenio-app-rdm/pull/2536
> tests: config: update OAISERVER_RECORD_SETS_FETCHER

- invenio_rdm_records/resources/resources.py
* adds custom_response_handler based on flask response_handler but accepting a flask Response
* closes https://github.com/zenodo/rdm-project/issues/545
> resources: add parent doi redirection

- invenio_rdm_records/services/access/service.py
- invenio_rdm_records/services/communities/service.py
- invenio_rdm_records/services/generators.py
- invenio_rdm_records/services/permissions.py
* adds generator to allow community curators to curate the (restricted) records
* closes https://github.com/zenodo/rdm-project/issues/482
> generators: add community inclusion reviewers

- invenio_rdm_records/services/services.py
The current embargo release process only queries the latest version, so embargoes on other versions don't get released. This PR changes the query to look at all versions.
**Reminder**
1. You …
> services: extend embargo check to all versions

- invenio_rdm_records/contrib/imprint/custom_fields.py
This PR makes the imprint fields on the deposit form easier to understand. It explains what "Imprint" means, and labels the pages metadata field "pagination" to indicate that it can take either a page range or the total number of pages in the item.
Current:
This PR:
**Reminder** …
> contrib: update imprint labels to be more descriptive

- invenio_rdm_records/records/jsonschemas/records/record-v2.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v3.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v4.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v5.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v6.0.0.json
- invenio_rdm_records/services/schemas/metadata.py
* closes https://github.com/zenodo/rdm-project/issues/558
> metadata: configure publication_date to disallow DateAndTime format

- invenio_rdm_records/contrib/codemeta/custom_fields.py
- invenio_rdm_records/contrib/codemeta/processors.py
- invenio_rdm_records/fixtures/data/vocabularies.yaml
- invenio_rdm_records/fixtures/data/vocabularies/contrib/codemeta/programming_languages.yaml
- invenio_rdm_records/resources/serializers/__init__.py
- invenio_rdm_records/resources/serializers/codemeta/__init__.py
- invenio_rdm_records/resources/serializers/codemeta/schema.py
- invenio_rdm_records/resources/serializers/schemaorg/schema.py
- invenio_rdm_records/services/components/signal.py
- invenio_rdm_records/services/signals/__init__.py
- invenio_rdm_records/services/signals/signals.py
- invenio_rdm_records/services/tasks.py
- tests/conftest.py
- tests/services/components/test_signal_component.py
Note to reviewers: 4.2k changes come from the vocabulary for programming languages.
closes https://github.com/inveniosoftware/invenio-swh/issues/20
> Faircore4eosc

- invenio_rdm_records/resources/serializers/dcat/schema.py
- invenio_rdm_records/resources/serializers/marcxml/schema.py
Fixes Issue [#592](https://github.com/zenodo/rdm-project/issues/592)
**Reminder** …
> Updated export format schema to sanitize filename

- invenio_rdm_records/cli.py
- invenio_rdm_records/fixtures/__init__.py
- invenio_rdm_records/fixtures/tasks.py
- invenio_rdm_records/fixtures/vocabularies.py
The documentation indicates that new fixtures can be added https://inveniordm.docs.cern.ch/customize/vocabularies/, but that's not the case. I've added a new command line option `add_to_fixture` which adds new fixtures to a given vocabulary.
This seems to work fine, but feedback is much appreciated because I'm sure there are better approaches.
**Reminder**
By using GitHub, you have …
> fixtures: method to add entries to fixtures

- invenio_rdm_records/config.py
- invenio_rdm_records/services/config.py
* closes https://github.com/zenodo/rdm-project/issues/514
> config: add max files count configs for files and media files

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/DescriptionsField/DescriptionsField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/DescriptionsField/components/AdditionalDescriptionsField.js
Partially Closes [#421](https://github.com/zenodo/rdm-project/issues/421)
**Reminder**
2. You agree that …
> editor: replaced ckeditor with tinymce

- CHANGES.rst
- invenio_rdm_records/__init__.py
> release: v5.0.0

- invenio_rdm_records/resources/serializers/schemaorg/schema.py
closes https://github.com/zenodo/rdm-project/issues/525
Example:
> schema: add dataset specific fields to jsonld 

- invenio_rdm_records/resources/deserializers/rocrate/schema.py
- invenio_rdm_records/services/components/pids.py
- tests/conftest.py
- tests/resources/conftest.py
- tests/resources/test_resources_pids.py
- tests/services/files/conftest.py
- Closes https://github.com/zenodo/ops/issues/325
- pids: restore required PIDs on publish
- global: black formatting
> Restore required PIDs on publish

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/customFields/CustomField.js
Closes Issue [#632](https://github.com/zenodo/rdm-project/issues/632)
**Reminder** …
> custom fields: added check for float value

- invenio_rdm_records/oai.py
* closes https://github.com/zenodo/rdm-project/issues/585
> oai: exclude deleted records from search

- invenio_rdm_records/records/mappings/os-v1/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v6.0.0.json
* closes https://github.com/inveniosoftware/invenio-communities/issues/1099
> mapping: add children

- invenio_rdm_records/config.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
closes https://github.com/zenodo/ops/issues/315
> datacite: updated schema.

- invenio_rdm_records/services/communities/components.py
Introduced in inveniosoftware/invenio-communities#1088
> services: communities: add CommunityParentComponent

- invenio_rdm_records/fixtures/data/vocabularies/resource_types.yaml
- tests/fixtures/data/vocabularies/resource_types.yaml
… resource_type
As discussed with @lnielsen. @peter-cornwell and I feel the current 'Video/Audio' resource type is a little misleading - the internal type is 'video' and it is exported (where applicable) as types that are explicitly intended for visual media. 
This PR renames 'Video/Audio' to simply 'Video', and adds the new 'Audio' type intended for use with audio files.
If happy, I will check docs for any need to clarify this distinction. I guess would also need to be flagged in next release as a potentially breaking change. 
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practi …
> Resource types: rename "Audio/Video" to "Video", add new "Audio" type.

- invenio_rdm_records/resources/serializers/datacite/schema.py
This FIXME was resolved https://github.com/inveniosoftware/invenio-rdm-records/commit/eae931827fd4b6abeaade2dc610d78521b59f1a1, but never got removed
**Reminder**
1. You license your contribution …
> datacite: remove outdated fixme

- invenio_rdm_records/resources/serializers/datacite/schema.py
- tests/conftest.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/serializers/test_dcat_serializer.py
closes https://github.com/zenodo/ops/issues/312
> serializers: updated datacite schema rights.

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
- tests/conftest.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/serializers/test_dcat_serializer.py
- **Revert "serializers: updated datacite schema rights."**
- **release: v8.1.1**
> Fix DataCite serialization and release v8.1.1

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/SubjectsField/SubjectsField.js
Closes Issue [#733](https://github.com/zenodo/zenodo-rdm/issues/733)
**Reminder** …
> subjects: added dropdown component

- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/search_params.py
closes https://github.com/zenodo/zenodo-rdm/issues/747
> services: add metrics param interpreter

- invenio_rdm_records/contrib/journal/custom_fields.py
This PR changes the label for the pages field in the deposit form. The motivation is that users misinterpret the field, by putting in incorrect metadata (total number of physical pages) or not understanding that article numbers can also be put into this field. An example of some issues:
Article number in the issue field and total number of pages in pages field [Search for radio jets from massive young stellar objects. Association of radio jets with H2O and CH3OH masers](https://zenodo.org/record/4438759) 
Missing article number [Visible and near-infrared spectro-interferometric analysis of the edge-on Be star o Aquarii](https://zenodo.org/record/4673798)  …
> contrib: update journal field labels

- invenio_rdm_records/resources/serializers/datacite/schema.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/serializers/test_dcat_serializer.py
Resolves #1026 and #1095. This PR also fixes a bug in the serializer where geolocation point mapped the longitude and latitude incorrectly for geojson (https://github.com/inveniosoftware/docs-invenio-rdm/pull/460).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repo …
> serializers: fix coordinates and add geolocation box and polygon to datacite

- invenio_rdm_records/fixtures/data/vocabularies/resource_types.yaml
- tests/fixtures/data/vocabularies/resource_types.yaml
Improvements to the Schema.org properties on Resource Types. There are three changes in this PR:
- publication-dissertation: schema.org/thesis (lowercase t) is a 404, use schema.org/Thesis instead
- event: schema.org/event is an event _property_ not event _Thing_, should be schema.org/Event instead
- publication-thesis: use schema.org/Thesis like the publication-dissertation instead of https://schema.org/ScholarlyArticle
Aside, I did `./run-tests.sh` afterwards (I also updated these resource types values in a testing fixture), but there seem to be several modules missing for the tests script to actually work. I had to `pipenv run pip install docker-services-cli check_manifest sphinx` before they would complete.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to …
> resource-types: schema.org improvements

- invenio_rdm_records/services/pids/providers/external.py
- tests/conftest.py
- tests/resources/test_resources_pids.py
- tests/services/pids/test_pids_service.py
Fix https://github.com/zenodo/ops/issues/334
Before:
After:
**Reminder** …
> ux: DOI prefix error message improvement

- invenio_rdm_records/resources/serializers/marcxml/schema.py
- tests/resources/serializers/test_marcxml_serializer.py
Closes part of https://github.com/zenodo/ops/issues/367
> serializers: marcxml: Add leader to schema

- invenio_rdm_records/resources/serializers/marcxml/schema.py
- tests/resources/serializers/test_marcxml_serializer.py
Fixes https://github.com/zenodo/ops/issues/395
Current state of this Pull request, split by commit:
1. Do not remove whitespaces to make test failure diffs easier to read
2. Fix updated field (005) date format -> reported in linked issue
3. Add university (name of granting institution) to dissertation_note (502) -> reported in linked issue
4. Add identifiers to creators and contributors -> not reported by anybody, but still a difference with legacy
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an …
> MARCXML: Renamed/moved fields

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsModal.js
Closes Issue https://github.com/zenodo/ops/issues/363
**Reminder**
2. You agree that you have the right …
> creatibutors: filtering out grid from identifiers

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunitySelectionSearch.js
Closes Issue https://github.com/zenodo/ops/issues/378
**Reminder**
2. You agree that you have the right …
> community: set sortBy as bestmatch in search

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/FileUploader/FileUploaderArea.js
Closes https://github.com/zenodo/ops/issues/382
Closes https://github.com/zenodo/rdm-project/issues/626
**Reminder** …
> files: add word break for long filenames

- invenio_rdm_records/contrib/codemeta/custom_fields.py
Closes Issue https://github.com/zenodo/ops/issues/385
**Reminder**
2. You agree that you have the right …
> code: added check for repository identifier

- invenio_rdm_records/resources/serializers/marcxml/schema.py
- tests/resources/serializers/test_marcxml_serializer.py
Closes https://github.com/zenodo/ops/issues/407
```
<datafield tag="520" ind1=" " ind2=" " >
<subfield code="a" >&lt;p&gt;This is description&lt;/p&gt;</subfield>
</datafield>
<datafield tag="500" ind1=" " ind2=" " >
<subfield code="a" >&lt;p&gt;This is notes&lt;/p&gt;</subfield>
</datafield>
<datafield tag="500" ind1=" " ind2=" " >
<subfield code="a" >&lt;p&gt;This is abstract&lt;/p&gt;</subfield>
</datafield>
<datafield tag="500" ind1=" " ind2=" " >
<subfield code="a" >&lt;p&gt;This is method&lt;/p&gt;</subfield>
</datafield>
<datafield tag="500" ind1=" " ind2=" " >
<subfield code="a" >&lt;p&gt;This is table&lt;/p&gt;</subfield>
</datafield>
<datafield tag="500" ind1=" " ind2=" " >
<subfield code="a" >&lt;p&gt;This is other&lt;/p&gt;</subfield> …
```
> marcxml: moved notes form 520 to 500

- invenio_rdm_records/resources/serializers/marcxml/schema.py
- tests/resources/serializers/test_marcxml_serializer.py
Closes https://github.com/zenodo/ops/issues/409
**Reminder** …
> marcxml: removed parent_id and version

- invenio_rdm_records/fixtures/data/vocabularies/affiliations_ror.yaml
We now have an ROR, I would apprecaite adding this to the standard vocabularies. 
**Reminder**
2. You …
> Add ROR for Data Futures

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/details/LinksTable.js
- invenio_rdm_records/notifications/builders.py
- invenio_rdm_records/requests/access/requests.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/access/service.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/schemas/parent/access.py
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/grant-user-access.create.jinja
- tests/conftest.py
- tests/resources/test_access_requests.py
- tests/resources/test_resources_user_access.py
- tests/services/test_service_access.py
* implement bulk create grants
* add grants list marshmallow schema
* add a notification builder
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2593
Email preview:
Subject:
Main body:
In plain text:
> api: create new endpoint for access/users

- invenio_rdm_records/resources/serializers/marcxml/schema.py
Close https://github.com/zenodo/ops/issues/423
The license data is already indexed in the record itself and we were calling to get the license vocabulary every time which was expensive and is unnecessary. 
**Reminder** …
> MARC: remove read_many call to vocab service

- invenio_rdm_records/fixtures/data/vocabularies/roles.yaml
- invenio_rdm_records/resources/serializers/marcxml/schema.py
- tests/conftest.py
- tests/fixtures/data/vocabularies/roles.yaml
- tests/resources/serializers/test_marcxml_serializer.py
Close https://github.com/zenodo/ops/issues/410
Add a `4` subfield for the contributors role
**Reminder**
1. You license your contribution under the …
> MARC: Add contributors role subfield

- invenio_rdm_records/resources/serializers/marcxml/schema.py
- tests/conftest.py
- tests/resources/serializers/conftest.py
- tests/resources/serializers/test_marcxml_serializer.py
Closes https://github.com/zenodo/ops/issues/418
Closes https://github.com/zenodo/ops/issues/414
Closes https://github.com/zenodo/ops/issues/415
**Reminder**
1. You license your contribution under …
> marcxml: moved funding from 856 to 536

- invenio_rdm_records/resources/serializers/csl/schema.py
This change adds a DOI value in alternative identifiers to the CSL serialized output, if a record DOI is not present in pids. In a standard install this won't be used, but is helpful when a repo needs to manage multiple records with the same DOI. I also fixed some bugs in the CSL handling of ISBN and ISSN identifiers.
**Reminder**
By using GitHub, you have already agreed to the …
> Add alternative identifier DOI to CSL

- invenio_rdm_records/resources/serializers/datacite/schema.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/serializers/test_dcat_serializer.py
Resolves #1027. This is complete and ready for review.
**Reminder**
2. You agree that you have the right …
> serializers: add system updated data to datacite

- invenio_rdm_records/fixtures/data/vocabularies/community_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/contrib/codemeta/development_status.yaml
- invenio_rdm_records/fixtures/data/vocabularies/date_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/description_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/relation_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/removal_reasons.yaml
- invenio_rdm_records/fixtures/data/vocabularies/resource_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/roles.yaml
- invenio_rdm_records/fixtures/data/vocabularies/title_types.yaml
Added Swedsih translations for the vocabularies.
**Reminder** …
> Added Swedish translation for vocabularies

- invenio_rdm_records/fixtures/data/vocabularies/licenses.csv
- invenio_rdm_records/fixtures/vocabularies.py
- Change delimiter of CSV to comma
- Update license URLs:
Use base URLs `creativecommons.org` and `opensource.org` wherever possible with `spdx.dev` as fallback.
Tested with invenio-app-rdm `v12.0.0b1`
> vocabularies: update existing licenses

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/resources/iiif.py
- **resources: make IIIF proxy configurable via import string**
- **📦 release: v10.3.1**
> IIIF Proxy config via import string and release v10.3.1

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/resources/iiif.py
- **iiif: fix proxy path generation**
- **📦 release: v10.3.2**
> Fix IIIF path proxy generation and release v10.3.2

- invenio_rdm_records/fixtures/vocabularies.py
* Read a larger sample size to improve detection as smaller values fail to detect previous delimiters like `;`.
* Closes <https://github.com/inveniosoftware/invenio-app-rdm/issues/2658>
**Frontend**
**Reminder** …
> Licenses: Fix Some Delimiters Not Been Recognized.

- invenio_rdm_records/config.py
- invenio_rdm_records/resources/iiif.py
- invenio_rdm_records/resources/serializers/iiif/schema.py
- invenio_rdm_records/services/iiif/service.py
Partially Closes https://github.com/zenodo/zenodo-rdm/issues/840
Depends on https://github.com/inveniosoftware/invenio-app-rdm/pull/2657 for failing tests
**Frontend**
**Reminder**
1. You license your …
> resources: added fallback for iip server

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/config.py
- invenio_rdm_records/services/iiif/storage.py
- **config: format IIIF valid extensions**
- **iiif: resolve relative tiles storage against instance path**
- **📦 release: v10.4.2**
> Fix tiles path resolution and release v10.4.2

- invenio_rdm_records/config.py
- invenio_rdm_records/services/config.py
closes https://github.com/zenodo/zenodo-rdm/issues/852
> services: fix permission for file edit.

- invenio_rdm_records/requests/entity_resolvers.py
- invenio_rdm_records/services/pids/service.py
- invenio_rdm_records/services/schemas/utils.py
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/grant-user-access.create.jinja
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2667
* closes https://github.com/zenodo/zenodo/issues/151
> email templates: adjust the template to share draft

- invenio_rdm_records/access_requests_ui/views.py
- invenio_rdm_records/notifications/builders.py
- invenio_rdm_records/requests/access/requests.py
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/guest-access-request.cancel.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/guest-access-request.decline.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/guest-access-request.submitted.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/user-access-request.cancel.jinja
* move submitted notification to a template in submit action
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/153
> notifications: add user/guest cancel and decline

- invenio_rdm_records/utils.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2684
> secret links: set csrf token for all requests with secret links

- tests/services/conftest.py
- tests/services/test_service_review.py
* fixes the identity for open review policy (community owner gets auto accept) tests should be running with regular users
> tests: update the uploader of reviews

- invenio_rdm_records/records/processors/tiles.py
- invenio_rdm_records/resources/serializers/iiif/schema.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/iiif/storage.py
- invenio_rdm_records/services/iiif/tasks.py
Closes Issue https://github.com/zenodo/zenodo-rdm/issues/931 & https://github.com/zenodo/zenodo-rdm/issues/930
**Frontend**
**Reminder** …
> media-files: generate ptif and include in manifest

- invenio_rdm_records/resources/serializers/codemeta/schema.py
closes https://github.com/inveniosoftware/invenio-swh/issues/33
> codemeta: added identifier to schema

- invenio_rdm_records/config.py
- invenio_rdm_records/records/processors/tiles.py
- invenio_rdm_records/resources/iiif.py
- invenio_rdm_records/resources/serializers/codemeta/schema.py
- invenio_rdm_records/resources/serializers/iiif/schema.py
- invenio_rdm_records/resources/serializers/signposting/schema.py
- invenio_rdm_records/services/communities/service.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/customizations.py
- invenio_rdm_records/services/iiif/storage.py
- invenio_rdm_records/services/iiif/tasks.py
- invenio_rdm_records/services/results.py
- tests/resources/serializers/test_signposting_serializer.py
- tests/services/test_rdm_service.py
this PR incorporates commits from master into the maint-v10 branch to be included into v12 of app-rdm
> Maint 10 cherry picked

- invenio_rdm_records/requests/user_moderation/actions.py
- invenio_rdm_records/requests/user_moderation/tasks.py
- setup.cfg
- Closes https://github.com/zenodo/zenodo-rdm/issues/939
- **user_moderation: improve DB queries and use Celery tasks**
> User moderation reliability fixes

- invenio_rdm_records/services/pids/service.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2685
> permissions: change error handler for resolving pid permission denied

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsFieldItem.js
> creatibutors: fix buttons

- .tx/config
Update path for transifex ui messages
**Frontend**
**Reminder**
2. You agree …
> transifex: update file path for ui strings

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositApiClient.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AffiliationsField/AffiliationsField.js
- invenio_rdm_records/oaiserver/resources/config.py
- invenio_rdm_records/resources/config.py
* closes https://github.com/zenodo/rdm-project/issues/598
> http headers: use and adjust vnd.inveniordm.v1+json http accept header

- invenio_rdm_records/webpack.py
* closes https://github.com/zenodo/rdm-project/issues/657
> package: bump react-invenio-forms

- invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records/package-lock.json
Add `package-lock.json` for assets. Allows to recreate the same environment with same packages.
**Frontend**
**Reminder**
1. You license your contribution under the …
> assets: add package-lock.json

- invenio_rdm_records/resources/serializers/schemaorg/schema.py
- tests/resources/serializers/test_schemaorg_serializer.py
> schemaorg: add dateCreated field

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunityListItem.js
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/services/communities/service.py
- invenio_rdm_records/services/errors.py
- invenio_rdm_records/services/review/service.py
- tests/conftest.py
- tests/resources/serializers/test_marcxml_serializer.py
- tests/resources/test_resources_communities.py
- tests/resources/test_resources_review.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/158
CommunityListItem:
Error that is shown when clicking on "Submit for review"
> communities: add permission checks for submission policy

- invenio_rdm_records/resources/resources.py
*  closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2821
> resource: fix add record to community

- invenio_rdm_records/fixtures/vocabularies.py
- invenio_rdm_records/oaiserver/services/services.py
- deps: change for flask-sqlalchemy >=3.0.0
- deps: change for flask >=3.0.0
- sql: remove DeprecationWarning
> remove flask upper pin

- invenio_rdm_records/services/communities/service.py
- invenio_rdm_records/services/config.py
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2857
**Frontend**
**Reminder** …
> records: Add support for resolving draft PIDs in RecordCommunitiesService

- CHANGES.rst
- invenio_rdm_records/__init__.py
Release v10.8.5
**Frontend**
**Reminder** …
> release: v10.8.5

- invenio_rdm_records/collections/__init__.py
- invenio_rdm_records/collections/api.py
- invenio_rdm_records/collections/config.py
- invenio_rdm_records/collections/errors.py
- invenio_rdm_records/collections/links.py
- invenio_rdm_records/collections/models.py
- invenio_rdm_records/collections/results.py
- invenio_rdm_records/collections/schema.py
- invenio_rdm_records/collections/service.py
- invenio_rdm_records/ext.py
- invenio_rdm_records/resources/args.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/services/community_records/service.py
- tests/collections/test_collections_api.py
- tests/services/test_collections_service.py
- tests/services/test_service_community_records.py
closes https://github.com/zenodo/zenodo-rdm/issues/1006
> Add collections to browse

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunitySelectionSearch.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/index.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/index.js
Closes Issue: https://github.com/inveniosoftware/invenio-communities/issues/1227
**Previously Used Here:**
**Additional Usage:**
**Frontend**
**Reminder**
1. You license your contribution under the same terms as …
> community: added props to make CommunitySelectionSearch reusable

- invenio_rdm_records/services/config.py
> DOI: fix wrong parent DOI link

- invenio_rdm_records/templates/semantic-ui/invenio_notifications/grant-user-access.create.jinja
- tests/services/test_service_access.py
closes inveniosoftware/invenio-app-rdm#2827
> access notification: provide correct draft preview link

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AccessField/AccessRightField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AccessField/components/MetadataAccess.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AccessField/components/ProtectionButtons.js
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/grant-user-access.create.jinja
- tests/services/test_service_access.py
- **access notification: provide correct draft preview link**
- **fix: propTypes warning**
- **fix: propTypes warning**
- **release: v10.8.7**
> backport preview draft link + propTypes warning fixes

- invenio_rdm_records/services/config.py
At TU Graz, we'd want to customize file-upload.
Namely we'd like to forbid "weird" filenames from being uploaded (as that would complicate integrating with systems that expect "nice" filenames).
This could be done with custom components for file-services.
However, invenio's file-service components aren't configurable currently.
This PR makes file-service components configurable.
**Frontend** …
> services: make file-service components configurable

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AffiliationsField/AffiliationsField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsModal.js
Close #1805
Relies on https://github.com/inveniosoftware/react-invenio-forms/pull/255
(I don't know why the dropdown boxes are so small in the screenshots)
In person view I fixed the margin above "Role", removed the extra space to the left of the ORCID logo, and added the affiliations. 
Before and after:
In the organisation view I removed the ROR icon which shouldn't be there (according to ROR) and added the new information we have added to the API
Before and after:
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedepend …
> Improve display of ROR information in deposit form

- invenio_rdm_records/records/systemfields/access/owners.py
- invenio_rdm_records/secret_links/serializers.py
- fix: DeprecationWarning of SQLAlchemy
- setup: forward compatibility to itsdangerous>=2.1
> remove flask upper pin 2

- invenio_rdm_records/requests/community_submission.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/203
> community submission: remove notification about request auto-accept

- invenio_rdm_records/services/github/release.py
* Add `repositoryCode` as a custom field
> github: add repositoryCode

- invenio_rdm_records/services/github/metadata.py
- invenio_rdm_records/services/github/release.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1887
> github: added default license from Github API

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/serializers/RightsVocabularyField.js
Closes Issue: https://github.com/inveniosoftware/invenio-rdm-records/issues/1912
**Frontend**
**Reminder**
2. You agree …
> rights: fix serialize condition for controlled license

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AffiliationsField/AffiliationsField.js
Partially Closes: https://github.com/inveniosoftware/react-invenio-forms/issues/268
**Frontend**
**Reminder**
2. You …
> affiliations: update AffiliationsField value

- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/permissions.py
- invenio_rdm_records/services/results.py
- invenio_rdm_records/services/services.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2968
> resources: expose record revisions

- invenio_rdm_records/resources/serializers/dcat/datacite-to-dcat-ap.xsl
- tests/conftest.py
- tests/resources/serializers/test_dcat_serializer.py
* Closes #1949
* See linked issue for a description of the bug
**Frontend**
**Reminder**
2. You agree that you have the …
> serializers: DataCite to DCAT-AP: fix undefined variable $cheme for relation type has metadata

- invenio_rdm_records/records/systemfields/access/grants.py
- invenio_rdm_records/utils.py
- setup.cfg
- tests/conftest.py
- tests/contrib/__init__.py
- tests/contrib/codemeta/__init__.py
- tests/fixtures/__init__.py
- tests/fixtures/conftest.py
- tests/fixtures/load_error/__init__.py
- tests/fixtures/load_error/conftest.py
- tests/fixtures/load_error/test_vocabularies_load_error.py
- tests/oaiserver/__init__.py
- tests/records/__init__.py
- tests/records/dumpers/__init__.py
- tests/records/systemfields/__init__.py
- tests/requests/__init__.py
- tests/resources/__init__.py
- tests/resources/serializers/__init__.py
- tests/resources/vocabularies/__init__.py
- tests/secret_links/__init__.py
- tests/services/__init__.py
- tests/services/components/__init__.py
- tests/services/files/__init__.py
- tests/services/pids/__init__.py
- tests/services/pids/providers/__init__.py
- tests/tokens/__init__.py
* This is necessary for pytest v8.x to be able to detect all unique
tests.
> Various tests fixes

- invenio_rdm_records/resources/serializers/schemaorg/schema.py
This is the remnant of a dead-end investigation in providing more VideoObject structured
data per https://developers.google.com/search/docs/appearance/structured-data/video
since we were getting 'chided' by Google search console. Unfortunately, the
reality is that a record page is not a video watch page (it may contain multiple
videos + focus of page is on wider metadata) and a generic instance doesn't
have video thumbnails and perhaps doesn't want to expose video content file too
much. All of this resulted in only implementing the uploadDate field :shrug: .
> schema.org: add uploadDate for VideoObject serialization [+]

- invenio_rdm_records/resources/serializers/cff/schema.py
- tests/resources/serializers/test_cff_serializer.py
* Addresses https://github.com/zenodo/zenodo-rdm/issues/960
> cff: add default "message" field

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/package.json
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositRecordSerializer.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/errors/FormFeedback.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AccessField/AccessRightField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsFieldItem.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/FileUploader/FileUploader.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/FileUploader/FileUploaderArea.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/License/LicenseField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/state/actions/deposit.js
- invenio_rdm_records/webpack.py
* Fixes inveniosoftware/react-invenio-forms#277
> - Updates FormFeedback messages and structure to show relevant sections and count, with directed links to them
> - Doesn't stop publishing in case of severity checks
> - Updates files upload button to have error class
> form: revamp errors/warning in feedback 

- babel.ini
* Currently when you run `python setup.py extract_messages` it will Not include *.jinja template files.
This one will fix that.
**Frontend**
**Reminder**
1. You license your contribution under the same terms as …
> i18n: Include `*.jinja` File Encoding in `babel.ini`

- invenio_rdm_records/fixtures/data/vocabularies/community_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/date_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/description_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/relation_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/removal_reasons.yaml
- invenio_rdm_records/fixtures/data/vocabularies/resource_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/roles.yaml
- invenio_rdm_records/fixtures/data/vocabularies/title_types.yaml
Vocabulary translations for the czech language
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the current …
> Czech vocabulary translations

- invenio_rdm_records/administration/views/oai.py
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunityListItem.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/ComingSoonField/ComingSoonField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsFieldItem.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/FileUploader/FileUploaderArea.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/License/LicenseModal.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/TitlesField/AdditionalTitlesField.js
- invenio_rdm_records/contrib/codemeta/custom_fields.py
- invenio_rdm_records/contrib/journal/custom_fields.py
- invenio_rdm_records/contrib/meeting/custom_fields.py
- invenio_rdm_records/oaiserver/services/schema.py
- invenio_rdm_records/requests/access/requests.py
- invenio_rdm_records/resources/serializers/cff/schema.py
- invenio_rdm_records/resources/serializers/schemaorg/schema.py
- invenio_rdm_records/resources/serializers/utils.py
- invenio_rdm_records/services/communities/service.py
- invenio_rdm_records/services/community_inclusion/service.py
- invenio_rdm_records/services/github/release.py
- invenio_rdm_records/services/pids/errors.py
- invenio_rdm_records/services/pids/providers/base.py
- invenio_rdm_records/services/services.py
* Checked the spelling or embargoes here: https://dictionary.cambridge.org/dictionary/english/embargoes
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the …
> I18n: Mark Missing Translations Backport

- babel.ini
* Currently when you run `python setup.py extract_messages` it will Not include *.jinja template files.
This one will fix that.
**Frontend**
**Reminder**
1. You license your contribution under …
> I18n-include-jinja-in-babelini

- invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records/package-lock.json
> translations: update package-lock.json

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositRecordSerializer.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/errors/FormFeedback.js
> deposit-ui: show icon and tooltip for new error format with severity error

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/Identifiers/PIDField/OptionalPIDField.js
- invenio_rdm_records/config.py
- invenio_rdm_records/services/components/pids.py
- invenio_rdm_records/services/pids/manager.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/2011
> pids: change optional DOI validation

- invenio_rdm_records/records/api.py
- invenio_rdm_records/services/services.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/352
> user quota: accomodate system user

- invenio_rdm_records/services/permissions.py
* the Disabled permission does not allow admins to perform operations
> permissions: replace Disabled with SystemProcess

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/services/tasks.py
* closes https://github.com/inveniosoftware/invenio-jobs/issues/67
> logging: add basic logging for expired embargoes

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/package.json
- invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records/package-lock.json
- invenio_rdm_records/webpack.py
related to https://github.com/inveniosoftware/invenio-search-ui/pull/215
⚠️ Still need relock `invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records/package-lock.json`
after branch maint-2.x merged and released[ react-searchkit](https://github.com/inveniosoftware/react-searchkit).
**Frontend**
**Reminder** …
> Bump axios and babel runtime versions

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/customFields/Meeting.js
- invenio_rdm_records/contrib/meeting/custom_fields.py
- invenio_rdm_records/templates/semantic-ui/meeting.html
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/2025
> contrib: meeting identifiers backwards compatibility

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CopyrightsField/CopyrightsField.js
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/381
* Placeholder and help text changes proposed by @lnielsen
> metadata: copyrights placeholder and help text changes

- invenio_rdm_records/resources/serializers/ui/schema.py
* partially addresses https://github.com/CERNDocumentServer/cds-rdm/issues/243
> ui serializer: display more thesis information

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/FileUploader/FileUploader.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/FileUploader/FileUploaderArea.js
Closes https://github.com/inveniosoftware/invenio-checks/issues/27
**Frontend**
**Reminder**
2. You …
> ui: add feedback messages on the file level

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/errors/FormFeedback.js
> feedback-ui: Add specific ID to disconnected feedback form

- tests/records/systemfields/test_tombstone.py
Fix tests to match changes in https://github.com/inveniosoftware/invenio-users-resources/commit/13c6ba9663dc4ae53c4d844298b320287b993582
**Reminder**
1. You license your contribution under the same terms as the current repository’s …
> tests: email is now present in system user

- invenio_rdm_records/fixtures/data/vocabularies/licenses.csv
SPDX has added the Creative Commons Public Domain Mark https://github.com/spdx/license-list-XML/pull/2571, which is a very relevant license for repository content. https://github.com/inveniosoftware/invenio-rdm-records/issues/1017
I've re-used the pddc logo because that's what creative commons uses. The pddc text is technically deprecated but it's still on spdx....so I don't think it's worth the effort of renaming the logo file.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on …
> licenses: add creative commons public domain mark from spdx

- invenio_rdm_records/checks/__init__.py
- invenio_rdm_records/checks/requests.py
- invenio_rdm_records/config.py
- invenio_rdm_records/services/components/__init__.py
- setup.cfg
- **chore: format config docstring**
- **checks: integrate service component and community requests**
> checks integration

- invenio_rdm_records/contrib/imprint/custom_fields.py
Updated version of https://github.com/inveniosoftware/invenio-rdm-records/pull/1923. Conference proceeding mapping is already in the metadata, this updates the labels to match. 
**Reminder**
1. You license your contribution under the same …
> contrib: specify proceedings in imprint title label

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/PublishButton.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/SubmitReviewModal.js
- invenio_rdm_records/ext.py
resolves: https://github.com/CERNDocumentServer/cds-rdm/issues/137
> assets: PublishButton: Make submit and publish utility overridable

- invenio_rdm_records/fixtures/data/vocabularies/contrib/codemeta/development_status.yaml
- invenio_rdm_records/fixtures/data/vocabularies/relation_types.yaml
* adds and corrects cs translations in vocabulary fixtures
**Frontend**
**Reminder**
2. You agree that …
> i18n: cs vocabulary translations

- invenio_rdm_records/resources/iiif.py
- invenio_rdm_records/services/iiif/service.py
Replaced `importlib_metadata` with `importlib.metadata`.
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the current repository’s license.
> chores: replacing importlib_metadata with importlib.metadata

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/PublishButton.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/PublishCheckboxComponent.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/PublishModal.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/SubmitReviewModal.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/index.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/index.js
fixes: https://github.com/CERNDocumentServer/cds-rdm/issues/137
> PublishButton: Separate PublishModal and add checkbox easily via params

- invenio_rdm_records/resources/serializers/bibtex/__init__.py
- invenio_rdm_records/resources/serializers/bibtex/schema.py
- invenio_rdm_records/resources/serializers/schemas.py
- tests/resources/serializers/test_bibtex_serializer.py
fixes: https://github.com/CERNDocumentServer/cds-rdm/issues/291
> serializers: bibtex: Add all versions export support

- invenio_rdm_records/resources/serializers/ui/schema.py
fixes: https://github.com/CERNDocumentServer/cds-rdm/issues/527
> serializers: ui: Strip none and trailing whitespace for thesis

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/PublishButton.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/SubmitReviewButton.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/SubmitReviewOrPublishButton.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/Identifiers/PIDField/OptionalPIDField.js
fixes: https://github.com/CERNDocumentServer/cds-rdm/issues/523
- When a published record with default field as `No, I need one` is re-published, the state is not set for the validation check on the optional DOI field.
- On Submit for review button, there was no validation for DOI reservation for optional DOIs.
> fix: raise validation errors for publish without reserving DOI

- invenio_rdm_records/services/components/review.py
fixes: https://github.com/CERNDocumentServer/cds-rdm/issues/518
> fix(review): add message for review exists error

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/details/LinksTable.js
* `URLSearchParams` does not parse URLs, https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#no_url_parsing, preventing the `metadataPrefix` from changing when a new value is selected on the dropdown.
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributio …
> fix (oaipmh): properly change output format

- invenio_rdm_records/config.py
- invenio_rdm_records/records/jsonschemas/records/definitions-v2.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/records/record-v7.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v7.0.0.json
- invenio_rdm_records/records/systemfields/tombstone.py
- invenio_rdm_records/requests/__init__.py
- invenio_rdm_records/requests/record_deletion.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/components/record_deletion.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/deletion_policy.py
- invenio_rdm_records/services/schemas/tombstone.py
- invenio_rdm_records/services/services.py
- setup.cfg
- tests/conftest.py
- tests/requests/test_record_deletion.py
- tests/resources/test_request_deletion.py
- tests/resources/test_serialized_links.py
- tests/services/test_deletion_policy.py
- tests/services/test_record_deletion_request.py
Initial implementation of record deletion.
> feat: add support to request deletion of a record

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/Identifiers/PIDField/OptionalPIDField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/Identifiers/PIDField/PIDFieldCmp.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/Identifiers/PIDField/components/OptionalDOIoptions.js
- invenio_rdm_records/services/components/pids.py
- tests/services/test_rdm_service.py
> Optional doi discard version fix

- invenio_rdm_records/services/deletion_policy.py
> fix(record-deletion): check for authenticated users only

- invenio_rdm_records/notifications/builders.py
- invenio_rdm_records/requests/record_deletion.py
- invenio_rdm_records/services/services.py
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/record-deletion.accept.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/record-deletion.decline.jinja
- tests/conftest.py
Add notifications to record deletion requests
> feat(record-deletion): add notifications; minor fixes

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsModal.js
fixes: https://github.com/inveniosoftware/invenio-app-rdm/issues/2999
> fix(CreatibutorsModal): get identifier scheme from recent suggestions

- invenio_rdm_records/config.py
Splits the config variable `RDM_RECORD_DELETION_CHECKLIST` in 2 variables:
* `RDM_IMMEDIATE_RECORD_DELETION_CHECKLIST`
* `RDM_REQUEST_RECORD_DELETION_CHECKLIST`
**Frontend**
**Reminder**
1. You license your contribution under the same …
> feat(deletion-request): different checklist for immediate and request

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/package.json
> chore(js-tests): upgrade react-overridable major version
