inveniosoftware/invenio-rdm-records

- invenio_rdm_records/config.py
- invenio_rdm_records/data/objecttypes.json
- invenio_rdm_records/jsonschemas/records/record-v1.0.0.json
- invenio_rdm_records/mappings/v6/records/record-v1.0.0.json
- invenio_rdm_records/mappings/v7/records/record-v1.0.0.json
- invenio_rdm_records/marshmallow/json.py
- invenio_rdm_records/marshmallow/utils.py
- invenio_rdm_records/models.py
- invenio_rdm_records/permissions.py
- setup.py
- tests/unit/test_schemas_json_load.py
**Fields**:
- Resource type
- additional titles
- additional descriptions
- dates (Following Zenodo implementation, not DataCite)
- publication date
- embargo date
- language: Using ISO 639-3 (as Zenodo) instead of 639-1 (as DataCite). It's newer and uses 3 letters instead of 2.
- version
- rights_list
**Validation**:
- All *lang* attributes be validated and follow the ISO 639-3
- All *enums* are validated against their list of values in Marshmallow instead of the JSON Schema. This allows to define configurable control vocabularies.
Addreses part of https://github.com/inveniosoftware/invenio-rdm-records/issues/18
> datamodel: add non-issue fields based on zenodo/datacite

- invenio_rdm_records/config.py
- invenio_rdm_records/ext.py
- setup.py
Step in the right direction but ~~may be~~ is not enough yet. If it runs after invenio-records-rest config, that wouldn't do: I think we need to have invenio-app-rdm hard set the config from this module to close that loophole.
> config: use ext and only set defaults

- invenio_rdm_records/version.py
- setup.py
Changes:
- invenio-search
- invenio-db
- invenio-records-files
- invenio-records-rest
Requires https://github.com/inveniosoftware/invenio-records-permissions/pull/30
Ready for merge if all good (merge and release records-permissions).
> dependencies: bump dependencies to comply with Invenio 3.2 

- .travis.yml
- invenio_rdm_records/version.py
- setup.py
Changes:
* Remove support for Python 2
* Bump Python 3 version
* Bump some dependencies due to Werkzeug imports, and remove the latter
* Release with new versioning scheme
Requires: https://github.com/inveniosoftware/invenio-rdm-records/pull/55
Closes: https://github.com/inveniosoftware/invenio-rdm-records/issues/48
Closes: https://github.com/inveniosoftware/invenio-rdm-records/issues/13
> global: new versioning scheme

- invenio_rdm_records/cli.py
- invenio_rdm_records/jsonschemas/records/record-v1.0.0.json
- invenio_rdm_records/mappings/v6/records/record-v1.0.0.json
- invenio_rdm_records/mappings/v7/records/record-v1.0.0.json
- invenio_rdm_records/marshmallow/json.py
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/list_entities.html
- setup.py
- tests/conftest.py
- tests/unit/test_schemas_json_load.py
closes #52
closes #78 
closes #61
> datamodel: test/display organizational entity

- invenio_rdm_records/cli.py
- invenio_rdm_records/ext.py
- invenio_rdm_records/jsonschemas/records/record-v1.0.0.json
- invenio_rdm_records/mappings/v6/records/record-v1.0.0.json
- invenio_rdm_records/mappings/v7/records/record-v1.0.0.json
- invenio_rdm_records/marshmallow/fields.py
- invenio_rdm_records/marshmallow/json.py
- setup.py
- tests/api/test_api_flow.py
- tests/conftest.py
- tests/unit/test_elasticsearch_mapping.py
- tests/unit/test_schemas_json_load.py
> 23 publication date edtf lvl0

- invenio_rdm_records/theme/templates/invenio_rdm_records/details/side_bar.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/record_landing_page.html
- invenio_rdm_records/theme/views.py
* Fix `doi_identifier` template filter
* Create a template filter called `format_date`
to accept date strings without formatting them.
This is needed to handle edtf dates for now.
closes #80, #81
> views: fix template filters

- invenio_rdm_records/marshmallow/json.py
- tests/api/test_elasticsearch_mapping.py
- tests/api/test_serializers.py
Fixes issue with `'extensions'` showing up empty in serialization.
A discussion point this brought on is what layer to test... and as I am writing this I think this complexity is because the serialization output is controlled by the schema and the serializer class/mixin (per record and per overall response). The serializer uses the schema, but it's easier (right now) to setup schema level tests... Like the `test_jsonschema.py` file which is now obsoleted by `test_elasticsearch_mapping.py`, I think we might be able to obsolete schema-level tests when we move to testing `json_v1.transform_record` . I didn't use it directly because it needs a PersistentIdentifier object and there wasn't one linked in the record yet.
> datamodel: dump 'extensions'

- invenio_rdm_records/version.py
How is the registration of the resources going @ppanero?  Let's only bump the version after you have done that or if you deem it too intertwined and would rather wait.
This is blocking merging of invenio-app-rdm since it depends on functionality provided by invenio-rdm-records.
> release: v0.11.0

- setup.py
I had to remove the upper limits because they were blocking the integration. When things were more "beta" it was nice to restrict. However, I think now we should do things as they are in Invenio in order to avoid extra work. This means:
- Upper bounds are only set in bundles. In our case, this is set by the `invenio_version` in `invenio-app-rdm` setup.py.
- In modules (i.e. `invenio-rdm-records` and `invenio-records-permissions`) upper bounds are not set, unless they cause troubles (e.g. in Travis). If setting an upper bound we should try to address it because it is an incompatibility with a full Invenio version.
*Why this change?*
I was working on updating InvenioRDM to the v3.4.0a1, Semantic-UI, when the only part of the work in order to integrate it should be done in …
> update dependencies according to invenio 3.4.0a1 bundles

- invenio_rdm_records/theme/templates/invenio_rdm_records/record_landing_page.html
- run-tests.sh
Display access right on landing page using vocab. 
Closes `record landing page: title-ize the access right. Now is "open Access", but should be "Open Access` from https://github.com/inveniosoftware/invenio-app-rdm/issues/154
> Fix displayed access right

- invenio_rdm_records/resources.py
- invenio_rdm_records/services.py
These are the names of the config.py variables
that can be used to override the BibliogaphicResourceConfigs
and BibliographicServiceConfig.
- closes https://github.com/inveniosoftware/invenio-records-resources/issues/67
(needs https://github.com/inveniosoftware/invenio-records-resources/pull/76 but not for tests to pass)
> config: define config_names [more]

- invenio_rdm_records/config.py
- invenio_rdm_records/links.py
- invenio_rdm_records/services.py
- tests/new_api/test_serialized_links.py
This responsibility was simply moved from records-resources
and drafts-resources.
part of https://github.com/inveniosoftware/invenio-app-rdm/issues/232
> links: generate self_html links here [more]

- invenio_rdm_records/mappings/v6/rdmrecords/drafts/draft-v1.0.0.json
- invenio_rdm_records/mappings/v6/rdmrecords/records/record-v1.0.0.json
- invenio_rdm_records/mappings/v7/rdmrecords/drafts/draft-v1.0.0.json
- invenio_rdm_records/mappings/v7/rdmrecords/records/record-v1.0.0.json
- invenio_rdm_records/services.py
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/287
The mapping was not indexing things correctly and therefore aggregations where empty. Now they are working.
**NOTE I**: The mapping is not perfect. First metadata extensions need to be revised to crosscheck they still work. Second, some fields might be missing but this contains the minimum implementation needed for this release; we will go more in depth when implementing data model.
**NOTE II**: Facets are shown but are not working due to missing sort as param. https://github.com/inveniosoftware/invenio-app-rdm/issues/288
```
File "/Users/ppanero/.virtualenvs/api-october/lib/python3.7/site-packages/invenio_records_resources/resources/records/resource.py", line 40, in search
links_config=self.config.links_config,
File …
```
> mappings: adapt to new data model implementation and fix faceting

- invenio_rdm_records/theme/assets/semantic-ui/less/invenio_rdm_records/theme.less
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/side_bar.html
Trying to get familar with Semantic-UI. I couldn't find this in the documentation, but I think this approach with CSS is valid? 
(Attempting to close #62)
> toggle 'more/less' detail message when expanding/collapsing stats

- MANIFEST.in
- invenio_rdm_records/records/jsonschemas/records/record-v1.0.0.json
- invenio_rdm_records/services/schemas/__init__.py
- invenio_rdm_records/services/schemas/access.py
- invenio_rdm_records/services/schemas/communities.py
- invenio_rdm_records/services/schemas/files.py
- invenio_rdm_records/services/schemas/metadata.py
- invenio_rdm_records/services/schemas/pids.py
- invenio_rdm_records/services/schemas/relations.py
- invenio_rdm_records/services/schemas/stats.py
- invenio_rdm_records/services/services.py
- tests/conftest.py
- tests/records/full-record.json
- tests/records/test_jsonschema.py
- tests/records/tombstone.json
- tests/resources/test_resources.py
- tests/services/test_schemas/test_access.py
- tests/services/test_schemas/test_creators_contributors.py
- tests/services/test_schemas/test_resource_type.py
- tests/services/test_schemas/test_titles.py
- tests/services/test_upload_errors.py
- Removed `obj_type` and `pid_type` from internal-pid
- `file.file_id` --> `file.id` or even `file.identifier` (we have a definition for it)
- Use `identifier` definition for all identifiers occurences. Did the same for `scheme`.
- Removed `contact` from `provenance` and `access` until send message feature is implemented
- Made `notes` into a simple string on top level
**Open questions**
- In the JSONSchema states languages are ISO 639-**3**, however it is tested with strings of length 2 (it should fail, by definition this ISO has length 3). Should we allow both IS 639-2 and 3 or change tests?
- What about removing `title` from the type:
```diff
"titleType": {
"description": "Type of title.",
"type": "string",
"enum": [
-         "alternative_title",
+         "alternative",
"subtitle",
- …
```
> datamodel: update jsonschema, full flow and validation for minimal record

- invenio_rdm_records/services/schemas/metadata.py
- tests/services/schemas/test_creator_contributor.py
- There were 2 DateSchema in `metadata.py`. I removed the one that according to tests is not valid anymore.
- `CreatorSchema::type` was not explicitly required which was ambiguous when it came to implementing frontend field. Also, not passing a type would cause a KeyError, because validation assumed it was present.
This is probably a symptom of the lack of CI plus the frequent merging.
> schema: fix minor issues

- invenio_rdm_records/records/dumpers.py
- setup.py
Closes #232 
Arrow's `fromtimestamp` returns a datetime object, in contrast to the date object returned by datetime. From my perspective times are not really useful for the use cases we have now, so I kept it consistent with the previous behaviour.
> We don't support publication date following EDTF level above 0 in [marshmallow-utils](https://github.com/inveniosoftware/marshmallow-utils/blob/master/marshmallow_utils/fields/edtfdatestring.py#L60), because those levels allow for a lot more complex date scenarios. This reduces the publication dates to dates or intervals of dates.
This was discussed with @lnielsen when developing the EDTF dumper. The conclusion was that there is no need for using level 0 parser in the dumper since Marshmallow will not allow anything that is not level 0.
**How …
> dumpers: use arrow to avoid timezone bias on dates

- invenio_rdm_records/cli.py
- invenio_rdm_records/config.py
- invenio_rdm_records/resources/serializers.py
- invenio_rdm_records/theme/assets/semantic-ui/js/invenio_rdm_records/rdmrecords.js
- invenio_rdm_records/theme/assets/semantic-ui/less/invenio_rdm_records/theme.less
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/contributors.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/description.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/details.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/keywords.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/list_entities.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/side_bar.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/macros/detail.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/record_landing_page.html
- invenio_rdm_records/theme/views.py
- tests/ui/test_views.py
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/244
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/243
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/305
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/365
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/364
**Changes**
- Enriches the CLI demo records
- Cleans unused config, jinja filters, etc.
- Uses as much as possible the UI serialized object
- Adds bottom *details* section
**Current status/Remaining work** (In a different PR if agreed):
1- The publication date is formated as "long" according to flask-babelext. However, it does not seem to be the same "long" format we used to get from the babel jinja filter.
2- Resource type and access labels …
> landing page: add more fields and use ui serializer

- invenio_rdm_records/theme/assets/semantic-ui/less/invenio_rdm_records/theme.less
- invenio_rdm_records/theme/assets/semantic-ui/less/invenio_rdm_records/variables.less
- invenio_rdm_records/theme/templates/invenio_rdm_records/record_landing_page.html
Closes #249 
**What was the issue**
The inner `<i>` node had a bigger font-size (1rem vs 0.85rem).
**Solution**
Adding the `small` class forces the font-size.
**Extra**
Created font-sizes variables to make them easier to use across the theme files.
**Screenshots**
Specifically (Note that it also removes an extra margin that existed between the lock and the "open access" text)
**Still bothers me**
The lock starts on the bottom, while the text seems to have a slight padding-bottom (didn't find it upon inspection). However, I was not able to fix this with CSS.
> ui: fix labels alignment and size on the landing page

- invenio_rdm_records/theme/templates/invenio_rdm_records/details/creators.html
- invenio_rdm_records/theme/templates/invenio_rdm_records/details/list_entities.html
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/256
**NOTE** I was unable to reproduce the exact stacktrace of the issue (seems to be old code, since the mentioned line did not exist in the module's code base).
However, it was breaking on the footnotes. This PR fixes the issues. Still displays correctly:
No affiliations:
With affiliations:
> ui: fix landing page when creators have no affiliations

- invenio_rdm_records/cli.py
- invenio_rdm_records/records/jsonschemas/records/record-v1.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v1.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v1.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v1.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v1.0.0.json
- invenio_rdm_records/services/schemas/metadata.py
- invenio_rdm_records/version.py
- tests/records/full-record.json
- tests/records/test_jsonschema.py
- tests/services/schemas/test_location.py
- tests/services/test_schemas_json_load.py
Requires marshmallow-utils GeoJSONSchema merge and release https://github.com/inveniosoftware/marshmallow-utils/pull/21
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/231
**Important notes**
- The ES mappings `coordinates` field inside the `geometry` is of type`float`, however it correctly stores the locations for both `point` and `multipoint`
```
"coordinates": {
"type": "float"
}
```
indexed:
```
"locations" : [
{
"geometry" : {
"type" : "point",
"coordinates" : [
3.5480075,
165.577299
]
},
"identifiers" : {
"wikidata" : "12345abcde",
"geonames" : "12345abcde"
},
"place" : "Naga",
"description" : "Random place on land..."
},
{
"geometry" : {
"type" : "multipoint",
"coordinates" : [
[
1.973974,
49.308415
],
[
-9.508502,
-21.08845
]
]
},
"place" : "Losheim"
}
],
```
> schema: add locations

- invenio_rdm_records/records/dumpers.py
- invenio_rdm_records/services/schemas/__init__.py
- invenio_rdm_records/version.py
Why?
Because the partially saved draft with no content sends `metadata: {}` which gets removed by the `clear_none` function in the `services.update_draft` method. This has two consequences:
- Gets indexed without it (therefore the dumper try except)
- Needs to be set back to `{}` in the post_dump serialization. Due to a marshmallow issue the `default` value cannot be used (it does not work when the value is `None` on `Nested` fields).
> schema and dumper: account for empty partial metadata in drafts

- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/dumpers/__init__.py
- invenio_rdm_records/records/dumpers/edtf.py
- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v1.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v1.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v1.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v1.0.0.json
- tests/records/test_dumpers.py
Addresses issue #223
* add EDTFListDumperExt to handle arrays of dates (e.g. 'metadata.dates') in addition to the existing EDTFDumperExt, which handles scalar values (e.g. 'metadata.publication_date')
* remove the date-type ES mappings KEY_start and KEY_end
* replace them with the date_range-type ES mapping KEY_range
* allows for simple date range queries (e.g. q=date:[1939-01-01 TO 1945-12-31])
> dumpers: add EDTFListDumperExt, change mappings

- tests/conftest.py
- tests/records/dumpers/conftest.py
- tests/records/dumpers/test_edtf_dumpers.py
- tests/records/dumpers/test_location_dumpers.py
- tests/resources/conftest.py
- Splits dumpers' tests in several files to ease comprehension
- Adds a EDTF test case: search. With year-level range, day-level range, and a year-level range that should not return the result.
> tests: split dumpers tests and add edtf query

- invenio_rdm_records/services/schemas/metadata.py
- setup.py
- tests/conftest.py
- tests/services/schemas/test_affiliation.py
- tests/services/schemas/test_creator_contributor.py
- tests/services/schemas/test_identifier.py
- tests/services/schemas/test_location.py
- tests/services/schemas/test_reference.py
- tests/services/schemas/test_related_identifier.py
- tests/services/schemas/test_right.py
- tests/services/schemas/test_subject.py
Depends on https://github.com/inveniosoftware/marshmallow-utils/pull/25
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/331
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/458
Uses Marshmallow-Utils new `IdentifierScheme` which "guesses" the scheme if not given and supports allowing a specific set of schemes.
Migrates identifiers from `dict` to `list` of dicts for contributors, creators and affiliations.
Tests are passing with local installation of marshmallow-utils dependency.
> schema: use identifier scheme from marshmallow utils

- invenio_rdm_records/records/jsonschemas/records/record-v1.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v1.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v1.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v1.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v1.0.0.json
- invenio_rdm_records/services/schemas/metadata.py
- tests/conftest.py
- tests/records/dumpers/test_edtf_dumpers.py
- tests/records/full-record.json
- tests/records/test_jsonschema.py
- tests/resources/test_publish_errors.py
- tests/services/schemas/test_creator_contributor.py
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/460
Note that no value (e.g. roles) are made into vocabularies due to cross-works in invenio-vocabularies. In addition, there is a blocker at `Relations` field in `api.py` level. The relation should be set to `metadata.contributors.role` but contributors (and creators) are arrays.
> refactor contributors

- invenio_rdm_records/records/jsonschemas/records/record-v1.0.0.json
- tests/records/test_jsonschema.py
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/216
Restrictions will be set when migration to vocabularies happens
> jsonschema: remove enum restrictions

- setup.py
Closes an issue @dfdan ran into: our updated vocabularies package 0.2.x series was picked up by december release which resulted in incompatible dependencies. This fixes it for future release as long as we continue our practice of keeping pre 1.0 minor releases as demarcators between monthly releases.
> dependencies: plug invenio-vocabularies leak

- invenio_rdm_records/resources/serializers/ui/__init__.py
closes #367 
previously, UIJSONSerializer just called json.dumps() directly, without taking into account the dumps_options set through the constructor (via its superclass, JSONSerializer)
> serializers: call superclass methods in UIJSONSerializer

- invenio_rdm_records/services/schemas/__init__.py
- tests/resources/test_resources.py
should fix the issues described in https://github.com/inveniosoftware/invenio-drafts-resources/pull/94
the issues arose because i used the wrong nested type for the access schema (namely one that resulted in a dump of `record.access` instead of `record["access"]`).
> marshmallow: use correct nested type for access

- invenio_rdm_records/services/generators.py
- tests/services/test_generators.py
@lnielsen this should fix it - I tested , it works for ```can_read = [IfRestricted('record', RecordOwners(), else_=AnyUser())] ```.
> bugfix: adds user to the query

- tests/services/conftest.py
- tests/services/test_permissions_poliy.py
related to #376 
```python
class TestRDMPermissionPolicy(....):
"""Define permission policies for RDM Records."""
can_search = [AnyUser(), SystemProcess()]
can_create = [AuthenticatedUser(), SystemProcess()]
can_update = [Disable()]
can_delete = [Disable()]
can_read = [
IfRestricted('record',
then_=[RecordOwners()],
else_=[AnyUser(), SystemProcess()])
]
can_read_files = [
IfRestricted('files',
then_=[RecordOwners()],
else_=[AnyUser(), SystemProcess()])
]
can_update_files = [Disable()]
can_read_draft = [RecordOwners()]
can_update_draft = [RecordOwners()]
can_delete_draft = [RecordOwners()]
can_read_draft_files = [RecordOwners()]
can_read_update_files = [RecordOwners()]
can_publish = [RecordOwners()]
can_manage = [RecordOwners()]
```
----
> tests: permission policy

- invenio_rdm_records/services/schemas/metadata.py
- tests/services/schemas/test_right.py
partially closes inveniosoftware/invenio-app-rdm#588
by invalid url - the json will include these errors:
```json
"errors": [
{
"field": "metadata.rights.0.link",
"messages": [
"Not a valid URL."
]
}
]
```
> license-link: checks for valid url

- invenio_rdm_records/records/systemfields/access/embargo.py
- invenio_rdm_records/records/systemfields/access/field.py
- invenio_rdm_records/services/schemas/access.py
- invenio_rdm_records/services/schemas/utils.py
potentially fixes inveniosoftware/invenio-app-rdm#586
* create a null object for Embargo that is used instead of None
* relax the requirements for creating a 'null embargo' in from_dict to require all properties to be falsy (or not set) instead of being strictly None (or not set)
* change the field type of embargo.until in the AccessSchema, as that didn't allow dumping of null values
> access: introduce null object for Embargo

- invenio_rdm_records/services/components.py
- tests/conftest.py
- tests/services/components/test_access_component.py
* the only exception are system processes, which are allowed to set the
record owners explicitly
> access: silently prevent users from changing record owners

- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v2.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v2.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v2.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v2.0.0.json
* the properties 'owned_by', 'grants', 'grant_tokens' and 'links' are no
longer contained in the record's access, but rather in the record's
parent access field
> mappings: update ES mappings for the record/parent split

- invenio_rdm_records/alembic/a3957490361d_remove_pidrelations_tables.py
closes #444 
there's still a number of issues that need to be addressed, e.g. revision "1d4e361b7586" (from invenio-pidrelations) having no revision script but still being referenced from the DB table `alembic_versions` after uninstalling invenio-pidrelations
also, it seems like `alembic stamp` doesn't seem to work properly with the new revision script (it doesn't seem to find a parent?)
> alembic: add recipe to remove PIDRelations tables if they exist

- invenio_rdm_records/cli.py
closes #441 
requires https://github.com/inveniosoftware/invenio-drafts-resources/pull/112 and inveniosoftware/invenio-records-resources/pull/211
* add service methods for reindexing records and drafts
* add new CLI command for reindexing everything, using the new service
methods of the records service and the vocabularies service
> global: add functionality for reindexing everything

- invenio_rdm_records/alembic/88d1463de5c0_create_parent_record_table.py
- invenio_rdm_records/alembic/a3957490361d_remove_pidrelations_tables.py
- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v2.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v2.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v2.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v2.0.0.json
- invenio_rdm_records/services/config.py
- invenio_rdm_records/version.py
- tests/services/conftest.py
- tests/services/test_sort.py
- ~~:warning: requires versioning PR with ES indexing.~~
- closes #440 
Note: According to RFC
> `versioning_order` (`parent_order`) - Integer (4 bytes) defining the rank of the record among sibling versions.
is defined for the DB and we expect something similar in the ES index. Furthermore, we expect that every new version is from the latest record. That is:
**Good**
Time 1
```
Concept Record
|
|___ Record V1
```
Time 2
```
Concept Record
|
|___ Record V2
|
|___ Record V1
```
Time 3
```
Concept Record
|
|___ Record V3
|
|___ Record V2
|
|___ Record V1
```
Otherwise, it is extremely hard (I don't know how to) order versions. That is:
**Bad**
Time 4
```
Concept Record
|
|___ Record V3
|
|___ Record new version from V2  <-- how could this be ordered?
|
|___ Record V2
|
|___ Record V1
```
ES …
> search: sort by versions

- invenio_rdm_records/ext.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/jsonschemas/records/definitions-v1.0.0.json
- invenio_rdm_records/records/jsonschemas/records/parent-v1.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v1.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v2.0.0.json
- setup.py
- tests/conftest.py
- tests/records/full-record.json
- tests/records/test_jsonschema.py
- tests/records/tombstone.json
Closes #356.
To test you need to install in the same virtual environment the following packages/PRs:
```
~/invenio-vocabularies/ $ gh pr checkout 31
~/invenio-vocabularies/ $ cd invenio-rdm-records
~/invenio-rdm-records/ $ pyenv virtualenv 3.8.6 i-rdm-records
~/invenio-rdm-records/ $ pip install -e ".[all,elasticsearch7,postgresql]"
~/invenio-rdm-records/ $ ./run-tests.sh
```
Passing locally ✅
> records: change schemas to use local URI scheme

- invenio_rdm_records/resources/serializers/ui/schema.py
- invenio_rdm_records/services/schemas/__init__.py
- invenio_rdm_records/services/schemas/communities.py
- invenio_rdm_records/services/schemas/metadata.py
- invenio_rdm_records/services/schemas/parent/__init__.py
- invenio_rdm_records/services/schemas/pids.py
- tests/resources/test_resources.py
- tests/services/schemas/test_metadata.py
closes #496 
Although there was worry about making sure we don't
accept additional fields everywhere, it turns out that
the default is `unknown = RAISE` for any marshmallow Schema.
Some tests were added, but I didn't bother with adding
tests everywhere since this is functionality provided
by marshmallow.
Also note that `unknown` only applies to `load`. So it didn't really make sense for the UISchema which only dumps :).
> schemas: raise on additional fields to schemas [+]

- invenio_rdm_records/cli.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/services/components.py
- invenio_rdm_records/services/config.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/501
Preliminary works, this will allow getting in unmanaged pids. Works on provider and more complex operations on the component will come from the work on managed pids.
> services: add pids systemfield and component

- invenio_rdm_records/services/schemas/__init__.py
- tests/services/schemas/test_rdm_record_schema.py
Closes #504 
Issues pending:
marshmallow-utils::IdentifierScheme raises a ValidationError if the scheme cannot be validated (i.e. is not supported by idutils). Currently, this is the [list of supported schemes](https://idutils.readthedocs.io/en/latest/). This makes the following tests fail:
- test_valid_unknown_scheme: because the scheme is unknown (random) and idutils cannot detect it
- test_valid_pid: because OAI is not supported by idutils
Both cases end in the same question:
- Do we want to fail when idutils cannot validate?
- If yes, shall we study what possible identifiers will we have to validate? (e.g. it should not fail on OAI).
> enhance pids field validation

- invenio_rdm_records/resources/config.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/permissions.py
- tests/resources/test_record_file_permissions.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/498
- Prevent file manipulations on record resource
- Support differentiated permissions for drafts and records
Tests are failing since it depends on https://github.com/inveniosoftware/invenio-rdm-records/pull/505 PR
> records: ensure files cannot be manipulated

- invenio_rdm_records/services/schemas/__init__.py
- invenio_rdm_records/services/schemas/metadata.py
- tests/conftest.py
- tests/services/schemas/conftest.py
- tests/services/schemas/test_creator_contributor.py
- tests/services/schemas/test_location.py
- tests/services/schemas/test_metadata.py
- tests/services/schemas/test_rdm_record_schema.py
- tests/services/schemas/test_reference.py
- tests/services/schemas/test_related_identifier.py
- tests/services/schemas/test_right.py
- tests/services/schemas/test_subject.py
@lnielsen @diegodelemos The goal of this PR is to fix the broken schema validation when installing latest master of `invenio-records-resources`. However,  it will fail on CI because `invenio-records-resources` is not released. The issue comes from the bump on `Marshmallow-Utils`, where the constructor signature of `IdentifierSchema` was changed.
Due to the update in Marshmallow Utils, it is possible now to load data whose scheme is not recognized by IDUtils. This allows (appart from implementing the PIDs feature) to re-enable **MANY** tests at schema level (e.g. locations, funders, rights, etc.). Note that the scheme will not be validated (because IDUtils does not have it implemented). Logic behind this choice:
- Even if we have control over IDUtils, we cannot implement validation for …
> service: migrate to new IdentifierScheme API and enable skip tests

- invenio_rdm_records/ext.py
- invenio_rdm_records/resources/__init__.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/services.py
- invenio_rdm_records/views.py
- setup.py
- tests/resources/test_resources.py
**Important notes**
- The service part will be refactor at the same time than the `reserve_pid` and `delete_pid` and potentially all PID related operations should be in a sub-service. And be able to do `service.pids.reserve(...)`.
- The resource level is being refactored by @ntarocco, but in principle this will stay as a separate resource since it has nothing to do with `records` (i.e. no `/records/` in the URL).
- There are two endpoint needed, one is specifically meant for DOIs which have a slash (`prefix/client.recid`) in the PID value.
- I **did not** add the `RDM` prefix to all the new classes because I find it unnecessary and making longer names with no extra value. But I can add it if required.
> resources: add pid resolver endpoint

- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/links.py
- tests/resources/test_serialized_links.py
Note that the DOI value in the `self_doi` value will come already escaped (i.e. `/` --> `%2F`). However, this is the transformation what internally the browser/api would do and it works.
I tested to access a record through the `self_doi` link and it worked. Since it is UI, we are not expecting any REST endpoint to access it and this escaping should not pose any problem.
This issue comes from `URITemplate` and making a generic solution proved quite cumbersome. So I left the value escaped.
>  links: doi and other pids links

- invenio_rdm_records/services/schemas/__init__.py
- tests/services/schemas/test_rdm_record_schema.py
- tests/services/test_rdm_service.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/571
`test_valid_unknown_scheme` was removed in favor of "*if there is a custom scheme it should provide a way of validating*"... To be trated later on in https://github.com/inveniosoftware/marshmallow-utils/pull/39
> tests: add service level pids creation tests

- invenio_rdm_records/services/components.py
- invenio_rdm_records/services/pids/providers/datacite.py
- invenio_rdm_records/services/schemas/__init__.py
- tests/services/pids/providers/test_datacite_pid_provider.py
- tests/services/test_rdm_service.py
closes #576 
closes #575 
This PR tackles two issues:
**Disable local reservation of DOIs**
Do not reserve locally a DOI, to avoid having many soft deleted ones. I.e. a user reserves and discards, if we set status to `RESERVED` then will be soft deleted. With this change it will pass from `NEW` to `REGISTERED`.
**Bug fix: do not store invalid values for pids**
Avoid saving invalid identifiers. If the validation step notes any scheme as having an invalid value, this one will be stripped of the `pids` so they are not stored in db.
This issue has an extra catch.
- There can be several schemes with errors, so at `__init__.py.Schema:validate_pids` level we need to catch and re-raise at the end with *several* messages.
- This makes us not be able to assign a specific field. i.e. it will always …
> pids: disable reservation and saving of invalid values

- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/version.py
- tests/conftest.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/services/conftest.py
- tests/services/schemas/test_resource_type.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/585
This along with the previous fixes allowed me to register a test DOI successfully!
In Datacite test fabrica (note we use our own resource types):
> doi: serialize resource type for Datacite

- invenio_rdm_records/services/components.py
- invenio_rdm_records/services/pids/providers/base.py
- invenio_rdm_records/services/pids/providers/datacite.py
- invenio_rdm_records/services/pids/providers/unmanaged.py
- tests/services/pids/providers/test_base_pid_provider.py
- tests/services/pids/providers/test_unmanaged_pid_provider.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/514
**Design decission**:
The `provider.validate` method returns True/False (for success) and a list of errors, in a similar fashion that marshmallow with `raise_errors=False` (see `AccessComponent`). That way only the component needs to know about `ValidationError`.
> providers: consolidate error handling on validation steps

- invenio_rdm_records/resources/serializers/datacite/__init__.py
- invenio_rdm_records/resources/serializers/ui/__init__.py
- invenio_rdm_records/services/pids/providers/datacite.py
- tests/resources/serializers/test_datacite_serializer.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/812
Changes:
- UI serializer: copy to avoid modifying the original record. Otherwise, we should document and not return, just make the user use the passed record.
- DataCite serializer: return only the metadata since it is what's serializable to DataCite. The rest is data that makes no sense in this format.
> serializers: avoid modifications to the original record/obj

- setup.py
closes https://github.com/inveniosoftware/invenio-records-resources/issues/248
@lnielsen I know this is not optimal AT ALL... but there is no other way (that we know of 😅) at the moment to unblock the fact that we cannot upload a file via UI (`pre_commit` hook fails) 😓
> global: add service registration blueprint to ui app

- invenio_rdm_records/resources/iiif.py
- setup.py
- tests/resources/test_iiif.py
requires https://github.com/inveniosoftware/invenio-records-resources/pull/247
requires https://github.com/inveniosoftware/invenio-records-resources/pull/249
requires https://github.com/inveniosoftware/invenio-iiif/pull/39
requires https://github.com/inveniosoftware/invenio-rdm-records/pull/602
closes https://github.com/inveniosoftware/invenio-iiif/issues/38
Status with all other PR requirements - working use case e.g. `https://127.0.0.1:5000/api/iiif/v2/eq18w-nhc19:ouroboros.png/full/250,/0/default.jpg`
> handlers: implement image opener for iiif

- invenio_rdm_records/fixtures/demo.py
- invenio_rdm_records/records/mappings/v6/rdmrecords/drafts/draft-v3.0.0.json
- invenio_rdm_records/records/mappings/v6/rdmrecords/records/record-v3.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v3.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v3.0.0.json
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/services/config.py
- tests/conftest.py
- tests/fixtures/data/vocabularies/languages.yaml
- tests/fixtures/test_cli.py
- tests/resources/conftest.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/test_resources.py
> mappings: migrate resource_type to vocbulary style

- invenio_rdm_records/records/jsonschemas/records/definitions-v1.1.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v3.0.0.json
- invenio_rdm_records/services/schemas/metadata.py
- tests/records/test_jsonschema.py
- tests/records/test_relations_languages.py
* previously, missing required properties would lead to generic 500
errors during the upload of metadata for drafts without useful
information
* also, the draft would not be saved
* this was because during draft creation, marshmallow validation
errors wouldn't lead to an abort, but jsonschema validation errors
would
* as per discussion, the role of jsonschema is primarily for basic
structural validation nowadays
> schemas: remove 'required' properties from jsonschema

- invenio_rdm_records/fixtures/data/vocabularies/languages.py
- invenio_rdm_records/fixtures/data/vocabularies/languages.yaml
- invenio_rdm_records/resources/serializers/datacite/__init__.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
- tests/resources/conftest.py
- tests/resources/serializers/test_datacite_serializer.py
closes #629 
~~How do we deal with those that have no alpha_2? There are many...~~ --> `missing` since it's not a mandatory field in datacite
> datacite: serialize languages following ISO 639-1

- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/services/schemas/metadata.py
- tests/conftest.py
- tests/services/schemas/test_location.py
in the marshmallow schema, the `features` property was missing from `metadata.locations`, causing the locations to always be dropped on ingest.
this mismatch could be fixed by simply adding the missing intermediate `features` property.
example record:
```
{
"files": {
"enabled": false
},
"metadata": {
"resource_type": {
"id": "other"
},
"title": "Awesome Information",
"description": "Nothing really new, but now packaged as a single record!",
"creators": [
{
"person_or_org": {
"given_name": "Max",
"family_name": "Moser",
"type": "personal"
},
"affiliations": [
{
"name": "TU Wien",
"identifiers": [
{
"scheme": "ror",
"identifier": "04d836q62"
}
]
}
]
}
],
"publisher": "TU Data",
"publication_date": "2021-04-03",
"locations": {
"features": [
{
"place": "Alpbach",
"geometry": {
"type": …
```
> schemas: add missing 'features' property in 'metadata.locations'

- invenio_rdm_records/fixtures/data/vocabularies.yaml
- invenio_rdm_records/fixtures/data/vocabularies/description_types.yaml
- invenio_rdm_records/fixtures/data/vocabularies/roles.yaml
- invenio_rdm_records/fixtures/data/vocabularies/title_types.yaml
- invenio_rdm_records/fixtures/demo.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
- tests/conftest.py
- tests/fixtures/app_data/vocabularies.yaml
- tests/fixtures/app_data/vocabularies/subjects.yaml
- tests/fixtures/data/vocabularies/description_types.yaml
- tests/fixtures/data/vocabularies/roles.yaml
- tests/fixtures/data/vocabularies/title_types.yaml
- tests/fixtures/test_cli.py
- tests/resources/serializers/test_datacite_serializer.py
> serializers: DataCite serializer fixes

- invenio_rdm_records/resources/serializers/datacite/__init__.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
- tests/resources/serializers/test_datacite_serializer.py
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/703
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/727
Differences I can observe in comparison with the full example of [DataCite 4.3 XML](https://github.com/inveniosoftware/datacite/blob/master/tests/data/datacite-v4.3-full-example.xml), which are not yet implemented are:
- All languages should use the 2 letter encoding, instead of 3. This should be fixed for the JSON schema too.
- We do not have alternate identifiers, we put them in `identifiers`. This would differ from the JSON schema. We should:
- pids --> identifiers
- identifiers --> alternate identifiers
> serializers: minor fixes to datacite json and add tests for xml

- invenio_rdm_records/fixtures/data/vocabularies/relation_types.yaml
* Removes IsMetadataFor, HasMetadata relation type pair because they
require use of additional fields that we do not support.
> vocabularies: remove metadata relation types

- invenio_rdm_records/resources/serializers/datacite/schema.py
- tests/resources/serializers/test_datacite_serializer.py
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/967
The field name is `affiliation` in singular, even if the cardinality is `0-n`.
> serializers: fix datacite creatibutors affiliations

- invenio_rdm_records/fixtures/data/vocabularies/affiliations_ror.yaml
- invenio_rdm_records/resources/serializers/datacite/schema.py
this solution is not ideal... Maybe some logistics to include the `id` with scheme = to the file id (e.g. ROR.lower())... But then we also need the possibility of extra identifiers... For now I think is good like this even if it duplicates a tiny bit.
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/967
> fixture: add identifiers to affiliations

- invenio_rdm_records/config.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/version.py
- setup.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/services/schemas/test_creator_contributor.py
- tests/services/schemas/test_identifier.py
- requires https://github.com/inveniosoftware/invenio-vocabularies/pull/76
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/962
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/735
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/750 (incorporated changes from #756 to make things easier)
> schemas: use new allowed identifiers structure

- tests/conftest.py
- tests/services/test_rdm_service.py
- tests/services/test_service_tasks.py
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/758
Tests are sometimes failing sometimes not. It seems something does not get timely propagated but there is a `db.session.commit` so it should not be the issue.
> tests: add test for lift embargo task

- MANIFEST.in
- invenio_rdm_records/translations/en/LC_MESSAGES/messages.po
Reason of these changes - translations were not loaded after a pip install of the latest release.
* i18n: adds default english po file
* adds missing manifest extension for `.mo` files
> i18n: adds missing manifest extention

- invenio_rdm_records/resources/serializers/csl/schema.py
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/729
This PR makes the REST API return a validation error for the citation, as it should since the resource type is mandatory for CiteProc to work.
It is up to app-rdm to display one message or another.
> serializers: csl should validate existance of resource_type

- invenio_rdm_records/fixtures/data/vocabularies/licenses.csv
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/968
Crossreferenced with open definition: https://licenses.opendefinition.org/licenses/groups/all.json
List of licenses to be manually checked:
```
0bsd
adsl
afl-1.1
afl-1.2
afl-2.0
afl-2.1
agpl-1.0-only
agpl-1.0-or-later
agpl-3.0-only
agpl-3.0-or-later
amdplpa
aml
ampas
antlr-pd
antlr-pd-fallback
apafml
apsl-1.0
apsl-1.1
apsl-1.2
abstyles
adobe-2006
adobe-glyph
afmparse
aladdin
apache-1.0
apache-1.1
apache-2.0
artistic-1.0
artistic-1.0-perl
artistic-1.0-cl8
artistic-2.0
bsd-1-clause
bsd-2-clause
bsd-2-clause-patent
bsd-2-clause-views
bsd-3-clause
bsd-3-clause-attribution
bsd-3-clause-clear
bsd-3-clause-lbnl
bsd-3-clause-no-nuclear-license
bsd-3-clause-no-nuclear-license-2014
bsd-3-clause-no-nuclear-warranty …
```
> vocabularies: add tags for software and data licenses

- invenio_rdm_records/searchconfig.py
If 'sort' or 'facets' is omitted/forgotten in RDM_SEARCH the code breaks
because self._sort/self._facets are expected to be iterable. By setting
them to be [] by default, that interface is respected.
> search: fix internal _sort/_facet [+]

- setup.py
Previously, celery would complain about the unregistered task `invenio_rdm_records.services.tasks.update_expired_embargos`.
The task was not listed during celery startup:
```
[tasks]
. invenio_accounts.tasks.clean_session_table
. invenio_accounts.tasks.send_security_email
. invenio_communities.fixtures.tasks.create_demo_community
. invenio_drafts_resources.services.records.tasks.cleanup_drafts
. invenio_files_rest.tasks.merge_multipartobject
. invenio_files_rest.tasks.migrate_file
. invenio_files_rest.tasks.remove_expired_multipartobjects
. invenio_files_rest.tasks.remove_file_data
. invenio_files_rest.tasks.schedule_checksum_verification
. invenio_files_rest.tasks.verify_checksum
. invenio_iiif.tasks.create_thumbnail
. invenio_indexer.tasks.delete_record
. …
```
> Update celery tasks entrypoints

- invenio_rdm_records/records/api.py
Fixes the following complaint of `run-tests.sh`:
```
lists of files in version control and sdist match
Warning, treated as error:
autodoc: failed to import module 'ext' from module 'invenio_rdm_records'; the following exception was raised:
Traceback (most recent call last):
File "/home/maximus/.local/share/virtualenvs/invenio-rdm-records-D8MrXj0B/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 67, in import_module
return importlib.import_module(modname)
File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in …
```
> Fix use before definition (for Flask 2.x)

- invenio_rdm_records/resources/serializers/datacite/schema.py
- tests/resources/serializers/test_datacite_serializer.py
Resolves #811 by removing alternative identifiers that have type DOI from the DataCite serialization, since DataCite doesn't accept DOIs that are not the registered DOI.
> serializer: fix datacite alt identifier doi handling

- invenio_rdm_records/config.py
- invenio_rdm_records/ext.py
- invenio_rdm_records/services/pids/providers/__init__.py
- invenio_rdm_records/services/pids/providers/base.py
- invenio_rdm_records/services/pids/providers/external.py
- invenio_rdm_records/services/schemas/__init__.py
- tests/resources/test_resources_pids.py
- tests/services/components/test_pids_component.py
- tests/services/pids/providers/test_external_pid_provider.py
- tests/services/pids/test_pids_service.py
- Fixes an issue where the persistent identifier in PIDStore was not
completely deleted for external DOIs, and thus it was not possible for
new records to use the same DOI. (closes #845)
> services: remove external DOI when changed

- invenio_rdm_records/ext.py
make sure that the credentials, as well as the doi components are of type string, to avoid type errors in the minting process
otherwise, it could happen that some values are parsed in the wrong type (e.g. the DOI prefix as a float rather than a string), if the configuration is provided via environment variables
> datacite: enforce string type on some datacite config items

- invenio_rdm_records/resources/serializers/utils.py
adding filter to only match the provided id so it returns one or no item. 
iterating over all the items and comparing them with the provided id takes more time and the further back in the results the wanted item is, the longer it takes.
performance wise, this is at least 2 times quicker - even going up to 50 times quicker (as of right now) depending on the returned list. usually it is around 10 times quicker
> refactor: increase vocabulary prop lookup performance

- docs/conf.py
- invenio_rdm_records/config.py
- invenio_rdm_records/ext.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/customizations.py
- invenio_rdm_records/services/pids/service.py
At its core, service config.py (and others really) is a place to
- define the config interface
- define how those config attributes are populated with special attention to
the fact that InvenioRDM is inherently configurable per instance.
So the idea is to
- make that core functionality clear and predominant
- group related things together e.g. configuration customization is extracted
out of ext.py completely and placed in customization.py
- favor independent composition of reusable configuration attribute definition
(using data accessors, an already common pattern in InvenioRDM)
> services: refactor configuration customization

- invenio_rdm_records/services/components/pids.py
- tests/__init__.py
- tests/conftest.py
- tests/fake_datacite_client.py
- tests/services/pids/test_pids_service.py
closes #866 
This drops the test suite speed by ~45s from ~10min15sec to ~9min30sec .  This is good in a sense, but also underwhelming
given that the full test suite still takes that long :sob: . The app loading seems the biggest culprit.
> tests: remove network calls to datacite in tests

- .github/workflows/tests.yml
- invenio_rdm_records/ext.py
- invenio_rdm_records/oaiserver/__init__.py
- invenio_rdm_records/oaiserver/resources/__init__.py
- invenio_rdm_records/oaiserver/resources/config.py
- invenio_rdm_records/oaiserver/resources/resources.py
- invenio_rdm_records/oaiserver/services/__init__.py
- invenio_rdm_records/oaiserver/services/config.py
- invenio_rdm_records/oaiserver/services/errors.py
- invenio_rdm_records/oaiserver/services/links.py
- invenio_rdm_records/oaiserver/services/permissions.py
- invenio_rdm_records/oaiserver/services/results.py
- invenio_rdm_records/oaiserver/services/schema.py
- invenio_rdm_records/oaiserver/services/services.py
- invenio_rdm_records/oaiserver/services/uow.py
- invenio_rdm_records/views.py
- setup.py
- tests/conftest.py
- tests/resources/test_resources_oai.py
depends on https://github.com/inveniosoftware/invenio-oaiserver/pull/206
Adds API for OAI-PMH sets
> feature: add OAI-PMH API

- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/views.py
- tests/conftest.py
- tests/resources/vocabularies/test_affiliations_vocabulary.py
- tests/resources/vocabularies/test_names_vocabulary.py
- tests/resources/vocabularies/test_subjects_vocabulary.py
- requires https://github.com/inveniosoftware/invenio-indexer/pull/134
- requires a bump in invenio-records-resources to pass minor (`invenio-indexer>=1.2.3`), take the oppportunity to bump `invenio-records` too after https://github.com/inveniosoftware/invenio-records/pull/281.
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/931
> global: rename registered services

- invenio_rdm_records/services/review/service.py
now indexes the record after submitting it for review, otherwise it will be returned with an outdated status in search results
> review service: index record on review submission

- invenio_rdm_records/resources/serializers/csl/schema.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/resources/serializers/dublincore/schema.py
- invenio_rdm_records/resources/serializers/utils.py
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/958
Since all the occurrences happen at _resources_ level it is accepted to access the `g` object. The `current_user` does not provide an identity (it provides `id` and `roles`) and we would need to build the identity from it, which is already stored in `g.identity`.
> serializers: use g.identity instead of system

- invenio_rdm_records/oaiserver/services/services.py
- invenio_rdm_records/services/schemas/metadata.py
- tests/services/schemas/test_creator_contributor.py
- Using must instead of should (includes removing typo).
- Using "cannot be blank" as everywhere else.
Refs: inveniosoftware/invenio-app-rdm#1707
> global: Fixes strings marked for translation.

- invenio_rdm_records/services/components/custom_fields.py
- invenio_rdm_records/services/components/metadata.py
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1002
Failing tests are due to Werkzeug and Flask-Login v0.6.2, passing in local
> services: create generic component for custom fields and metadata

- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v5.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v5.0.0.json
- tests/fixtures/test_cli.py
- closes #1040 
Tested on an instance (services setup + run) and worked.
> mappings: disable dynamic fields at global level and enable on inner objects

- invenio_rdm_records/cli.py
- invenio_rdm_records/config.py
- tests/conftest.py
- requires https://github.com/inveniosoftware/invenio-records-resources/pull/393
- closes https://github.com/inveniosoftware/invenio-records-resources/issues/361
**Custom field not configured**
```shell
> invenio rdm-records custom-fields init -f test
Custom fields configuration is not valid. Custom fields {'test'} are not configured.
```
**Custom field with wrong namespace**
```shell
> invenio rdm-records custom-fields init -f cerm:experiment
Custom fields configuration is not valid. Namespace cerm is not valid for custom field cerm:experiment.
```
**Creating field by name**
```shell
> invenio rdm-records custom-fields init -f cerm:experiment
Creating custom fields...
Created all custom fields!
```
**Creating all**
```shell
> invenio rdm-records custom-fields init
Creating custom …
```
> cli: validate custom fields configuration before creating

- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v5.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v5.0.0.json
- closes #1051 
- closes #1052
Before we did not state the `strict` property on the mappings, therefore they defaulted to *true*. This means that any field we were sending was being indexed (as text + keyword). By chance, it worked. We had this way many of them like formats, sizes, uuid, review data in the parent, etc. Even some very basic fields like "title" and "description" which were missing from the mapping 🤦.
I made the mappings strict as part of the custom fields development, because "why not, since that way we would be covered of users not abusing the mappings and only adding custom where allowed (i.e. under the`custom_fields.` field). Result: I could not find anything (search) by title, description, etc. (because they were not being indexed).
Added all missing fields (hope I …
> mappings: add missing fields and make them strict

- invenio_rdm_records/administration/views/oai.py
- invenio_rdm_records/config.py
closes https://github.com/inveniosoftware/invenio-administration/issues/79
The issue was that sort options did not match the service's search and sort options. Therefore, sort was defaulting to `created, asc` for most of the fields. 
This implementation should be revisited in my opinion, there are too many implementations of the same thing. E.g.:
1. `invenio-rdm-records` has a config that sets search and sort options, however they are only used for `invenio-administration`. 
https://github.com/inveniosoftware/invenio-rdm-records/blob/5754cbd54171ace2ca54b02110272a5ce5795721/invenio_rdm_records/config.py#L243-L260
2. `invenio_rdm_records.oai_server.services` has a `SearchOptions` instance, whose config is completely independent of (1). …
> oai: sort options matches service search options

- run-tests.sh
This is to make sure all marked strings are actually extractable.
> tests: adds extract_messages dry command

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/search/SearchResultItem.js
Closes https://github.com/inveniosoftware/invenio-administration/issues/109
Adds `word-break-all` class to table cell to prevent overflowing.
Needs https://github.com/inveniosoftware/invenio-theme/pull/328
> search result item: add word-break class to table cell

- invenio_rdm_records/resources/serializers/datacite/schema.py
- tests/conftest.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1904
this needs to be properly analysed. Right now, export fails because award's id is stripped and when the award is resolved (for export) it's not found in the DB.
> datacite: fixed award id removal.

- invenio_rdm_records/resources/serializers/ui/schema.py
The **additional descriptions** input field on the deposit page allows for text formatting, but given that the UI JSON Serializer **stripped** the HTML from that field, no formatting was ever displayed on the landing/preview page of records for those inputs.
> Sanitize HTML in additional descriptions instead of stripping it

- invenio_rdm_records/views.py
Add the records service's new draft indexer to the central indexer registry provided by `invenio-indexer`.
Requires https://github.com/inveniosoftware/invenio-drafts-resources/pull/208.
> Add draft indexer to the registry

- invenio_rdm_records/services/components/pids.py
Closes https://github.com/zenodo/zenodo-rdm/issues/99.
depends on https://github.com/inveniosoftware/react-invenio-deposit/pull/612
**Reminder**
1. You …
> pids: skip modifications when no data is passed

- invenio_rdm_records/resources/serializers/datacite/schema.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/test_oai.py
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1157
This PR fixes a reversion in the DataCite serializer. In v9 ROR affiliations were serialized with the whole url https://ror.org/identifier. That changed in v10 to just the identifier portion due to other identifier cleanup. This is an issue because DataCite expects ROR affiliations to be in their url form and unceremoniously deletes them if not. I've asked DataCite to change this, but we can also fix this directly in our serializer.
I also did a bit of cleanup by using the same approach as funders for determining which identifier to use.
If you've added [third-party code …
> datacite: fix reversion in affiliation ROR handling and cleanup

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/details/index.js
* closes https://github.com/inveniosoftware/invenio-administration/issues/155
Before: using wrong schema (marshmallow) to display fields
After: display the fields corresponding to [the config](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/administration/views/oai.py#L146)
> add uiSchema to AdminDetailsView props

- invenio_rdm_records/services/permissions.py
- tests/resources/test_record_file_permissions.py
The permissions for getting the file content were a bit too restrictive, requiring `can_preview` (i.e. "can preview draft") permissions rather than `can_read_files` (i.e. "can read files") permissions.
This PR fixes that by setting the conditional generator's `then_` value to the same as `can_read_files`.
That being said, I have the feeling that the given check for the file having a `L`ocal storage class and giving out access based on that could be reworked into business logic rather than permissions...
At least that's what it feels like to me – WDYT?
> Update `get_content_files` permissions

- invenio_rdm_records/contrib/__init__.py
- invenio_rdm_records/contrib/codemeta/__init__.py
- invenio_rdm_records/contrib/codemeta/custom_fields.py
- invenio_rdm_records/fixtures/data/vocabularies.yaml
- invenio_rdm_records/fixtures/data/vocabularies/contrib/codemeta/development_status.yaml
- tests/conftest.py
- tests/contrib/codemeta/conftest.py
- tests/contrib/codemeta/test_codemeta_custom_fields.py
- tests/fixtures/conftest.py
> contrib: added codemeta custom fields.

- tests/resources/serializers/test_ui_serializer.py
* changes the UI serializer test for date interval to apply the unicode space char change as in Babel. See https://github.com/python-babel/babel/commit/d76db13414a6104019edc0dbafa82410e8d08e63
Babel 2.12 upgrades CLDR to v42, which introduces this change to the unicode `space` char.
> serializer: update tests for date intervals

- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/services/communities/service.py
- invenio_rdm_records/services/community_records/service.py
- invenio_rdm_records/services/generators.py
- invenio_rdm_records/services/permissions.py
- tests/conftest.py
- tests/resources/conftest.py
- tests/resources/test_resources_communities.py
- tests/resources/test_resources_community_records.py
- tests/services/conftest.py
- tests/services/test_service_communities.py
- tests/services/test_service_community_records.py
- tests/services/test_service_review.py
* adds an extra permission check to ensure that a community curator cannot remove records from communities where he is not a curator.
> records: fix permissions when removing records

- invenio_rdm_records/resources/serializers/bibtex/schema.py
- invenio_rdm_records/resources/serializers/csl/schema.py
- invenio_rdm_records/resources/serializers/dublincore/schema.py
- invenio_rdm_records/resources/serializers/marcxml/schema.py
- invenio_rdm_records/resources/serializers/schemas.py
We could even move actual fields to the base schema, but that was more complex and error prone work.
> serializers: replace fields.Method by attribute key with dotted access

- invenio_rdm_records/services/iiif/service.py
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1998
This PR basically just adds a little bit of documentation about the `FileKeyNotFoundError`.
The `IIIFService`  calls `file_service` methods that raise `FileKeyNotFoundError` in `get_file()` and `image_api()`.
It doesn't handle those exceptions, but rather passes them on.
The resources will catch these exceptions and return a 404, because of the error handler registered on a base resource class in https://github.com/inveniosoftware/invenio-records-resources/pull/454.
I verified that the resources have the error handlers registered in a `my-site` with the three PRs installed:
```python
(my-site) mmoser@mx ~/rdm/my-site $ invenio shell
* Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use …
```
> Document information about `FileKeyNotFoundError`

- invenio_rdm_records/config.py
- invenio_rdm_records/services/components/access.py
- invenio_rdm_records/services/permissions.py
- tests/conftest.py
- tests/resources/test_resources.py
- Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2022.
**Reminder**
1. You license your contribution under the same terms as the …
> services: configure record access via config

- invenio_rdm_records/contrib/codemeta/custom_fields.py
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1247
Renames the CodeMeta section from "CodeMeta" to "Software"
> custom_fields: rename CodeMeta to Software

- invenio_rdm_records/requests/community_inclusion.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/services/communities/components.py
- invenio_rdm_records/services/communities/service.py
- invenio_rdm_records/services/community_inclusion/service.py
- invenio_rdm_records/services/community_records/service.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/errors.py
- invenio_rdm_records/services/schemas/community_records.py
- invenio_rdm_records/services/schemas/record_communities.py
- invenio_rdm_records/services/tasks.py
- tests/conftest.py
- tests/resources/conftest.py
- tests/resources/test_resources_communities.py
- tests/services/conftest.py
- tests/services/test_rdm_service.py
- tests/services/test_service_communities.py
- tests/services/test_service_community_records.py
- tests/services/test_service_review.py
- ensure record and community restriction are valid when accepting the inclusion request
- add missing tests
- remove wrong `f-string` on translations
- closes #1246
> inclusion: fixes add missing tests

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/customFields/Thesis.js
Thesis data is already loaded under key `custom_fields.thesis:university`, e.g:
```javascript
"initialValues" = {
"custom_fields": {
"thesis:university": "MIT"
}
}
```
Therefore, it's a string and not an object (we were trying to access `custom_fields.thesis:university.university`)
> deposit: fixed thesis field.

- invenio_rdm_records/fixtures/records.py
- invenio_rdm_records/fixtures/tasks.py
Although that User doesn't have any privileges, its presence is
initially alarming and it does create an account that can be used
by anyone. Given that it's not necessary, we might as well not have it.
> don't create admin@inveniosoftware.org user by default

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/index.js
Closes https://github.com/zenodo/who-rdm/issues/68
This PR is needed for the deposit form to work in WHO after upgrading. The `FileUploaderArea` component is in use in the WHO deposit, but not exported from `invenio-rdm-records` (along with the other components in the FileUploader folder).
> fields: export all file-uploader components

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/PublicationDateField/PublicationDateField.js
Closes https://github.com/zenodo/who-rdm/issues/66
Adds `helpText` as prop in `<PublicationDateField />` to enable overriding of help text.
> PublicationDateField: add helpText as prop

- invenio_rdm_records/services/generators.py
- invenio_rdm_records/services/permissions.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2262
* Fixes the permission check for cases where there is no record object to make checks against (e.g. when rendering the empty draft form).
> permissions: fix checks when new record

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunityHeader/CommunityHeader.js
Closes https://github.com/zenodo/zenodo-rdm/issues/409
Removes the sizing class to align with the styling in similar headers.
> community header: align header logo styling with other community headers

- invenio_rdm_records/services/github/metadata.py
- invenio_rdm_records/services/github/release.py
* closes https://github.com/inveniosoftware/invenio-github/issues/114
> github: added badges support

- invenio_rdm_records/services/schemas/parent/__init__.py
- invenio_rdm_records/services/schemas/parent/access.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1374
> access: allow dump of parent.access.settings field

- invenio_rdm_records/records/jsonschemas/records/parent-v3.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/systemfields/access/access_settings.py
- invenio_rdm_records/services/schemas/parent/access.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1387
Note: only the last commit corresponds to the current task. Previous one will be squashed after merge of this https://github.com/inveniosoftware/invenio-rdm-records/pull/1385
> Implement access request link expiration setting

- invenio_rdm_records/services/components/__init__.py
- invenio_rdm_records/services/components/verified.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/tasks.py
- tests/conftest.py
- tests/requests/test_user_moderation_actions.py
- tests/services/components/test_verified_component.py
- tests/services/pids/test_pids_service.py
- tests/services/test_rdm_service.py
closes https://github.com/inveniosoftware/invenio-requests/issues/344
Needs:
- https://github.com/inveniosoftware/invenio-requests/pull/345
> Create moderation request on publish

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/records/systemfields/access/access_settings.py
- invenio_rdm_records/requests/access/requests.py
- invenio_rdm_records/requests/entity_resolvers.py
- invenio_rdm_records/services/access/service.py
- invenio_rdm_records/services/generators.py
- invenio_rdm_records/services/permissions.py
- invenio_rdm_records/services/schemas/parent/access.py
- invenio_rdm_records/utils.py
- invenio_rdm_records/views.py
- tests/conftest.py
* provide custom validation for datetime field
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1395
> access request: add secret_link_expiration to guest access request payload schema

- invenio_rdm_records/records/systemfields/access/field/record.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1825, https://github.com/inveniosoftware/invenio-app-rdm/issues/1233, https://github.com/zenodo/rdm-project/issues/195
The `has_files` attribute is used to define the record access status. Aligning this with the [AccessStatusField](https://github.com/inveniosoftware/invenio-rdm-records/blob/0728b74cfd98c92616485b71d259fc224a8a60f9/invenio_rdm_records/resources/serializers/ui/fields.py#L141) to ensure the access status is displayed correctly.
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-part …
> systemfields: assign has_files according to enabled files

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositApiClient.js
- invenio_rdm_records/config.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/schemas/files.py
- invenio_rdm_records/services/schemas/parent/access.py
- invenio_rdm_records/tokens/resource_access.py
- invenio_rdm_records/utils.py
- services: make record/draft API classes configurable
- schema: expose checksum and file ID
- resources: make record serializers configurable
- resources: add "x-bibtex" record serialization
- access: serialize "owned_by" field
- deposit-ui: use "vnd.inveniordm.v1+json" always
- services: handle no-value DOI for links
- tokens: make RAT subject schema configurable
> tokens: make RAT subject schema configurable

- invenio_rdm_records/requests/user_moderation/actions.py
- tests/requests/test_user_moderation_actions.py
Fixes https://github.com/inveniosoftware/invenio-app-rdm/issues/2379
Screenshot of a blocked user's deleted record:
> User moderation: Delete a user's records when blocking them

- invenio_rdm_records/resources/serializers/schemas.py
- invenio_rdm_records/resources/serializers/ui/schema.py
- tests/resources/serializers/test_ui_serializer.py
closes https://github.com/zenodo/rdm-project/issues/228
> serializers: added locations to ui serializer.

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositApiClient.js
We get the following error in the UI (and the review was correctly submitted)
and the following error in the console
The error happens in the response handler when it tries to apply the Record UI schema to a community record
> deposit: update headers for submit review action

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunityHeader/CommunityHeader.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunityListItem.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunitySelectionModal.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunitySelectionSearch.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/SubmitReviewOrPublishButton.js
- invenio_rdm_records/requests/community_inclusion.py
- invenio_rdm_records/requests/community_submission.py
- invenio_rdm_records/services/community_inclusion/service.py
- tests/resources/test_resources_communities.py
- tests/services/test_service_review.py
* Community selection modal checks if the community is restricted and disables it if the record is public
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2384
> service: prevent creating a request if invalid restrictions

- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/resources/serializers/dublincore/schema.py
- invenio_rdm_records/resources/serializers/marcxml/schema.py
* use the cached slug when fetching the community slug in the serializers
Requires: https://github.com/inveniosoftware/invenio-communities/pull/1036
> serializers: use cached communities slugs

- invenio_rdm_records/notifications/builders.py
- invenio_rdm_records/requests/community_inclusion.py
- invenio_rdm_records/requests/community_submission.py
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/community-submission.accept.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/community-submission.cancel.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/community-submission.decline.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/community-submission.expire.jinja
- tests/conftest.py
- tests/services/test_service_review.py
actions: send notification on submission accept action
closes https://github.com/inveniosoftware/invenio-requests/issues/339
Send notification when executing a submission request action.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including …
> notifications: add submission action notifications

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositFilesService.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositFilesService.test.js
- invenio_rdm_records/resources/serializers/marcxml/schema.py
- invenio_rdm_records/services/permissions.py
* chore: remove leftover permissions
* closes https://github.com/zenodo/rdm-project/issues/253
this and dependent PRs need to be reviewed and tested **very** thoroughly
> assets: remove redundant recover on file upload fail

- invenio_rdm_records/notifications/builders.py
- invenio_rdm_records/requests/access/requests.py
- invenio_rdm_records/requests/entity_resolvers.py
- invenio_rdm_records/services/access/service.py
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/guest-access-request-token.create.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/guest-access-request.accept.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/guest-access-request.submit.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/user-access-request.accept.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/user-access-request.submit.jinja
- tests/conftest.py
- tests/resources/test_access_requests.py
closes #1454 
addresses sending out emails on submit: https://github.com/zenodo/rdm-project/issues/11#issuecomment-1708483567 
depends on https://github.com/inveniosoftware/invenio-users-resources/pull/111
Replaces EmailOp with NotficationOp. This will allow easy customization of sent notifications.
Send notification on guest access submit action.
**Reminder**
By using GitHub, you …
> 1454 notifications replace guest access request notification

- invenio_rdm_records/resources/serializers/ui/schema.py
* closes https://github.com/zenodo/rdm-project/issues/192
> Journal formatting

- invenio_rdm_records/records/api.py
- invenio_rdm_records/services/services.py
- tests/services/test_record_deletion.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1522
requires https://github.com/inveniosoftware/invenio-drafts-resources/pull/259
> service: fix restore/delete of specific record version

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/services/github/release.py
closes https://github.com/zenodo/rdm-project/issues/339
> GitHub release fix

- tests/services/test_service_review.py
> tests: fix service review test

- invenio_rdm_records/services/tasks.py
See errors like [1]. Long story short, if there are too many records to reindex at the same time (more than 65k), the service complains. This patch ensures that the reindex is done in bulks of 10k.
[1] https://flower-zenodo-rdm.app.cern.ch/task/84739159-fb66-41a9-9741-c03918685c34
> stats: reindex in bunches of 10k entries at a time

- invenio_rdm_records/services/github/metadata.py
closes https://github.com/zenodo/rdm-project/issues/362
Since we removed `HumanName`, it is not easy to always extract the authors names "nicely" without implementing something like the library itself... 
See some examples for the function below:
```python
gh_data = {
"name": "Manuel",
"login": "alejandromumo",
"company": "CERN"
}
print(serialize_author(gh_data))
gh_data = {
"name": None,
"login": "alejandromumo",
"company": None
}
print(serialize_author(gh_data))
gh_data = {
"name": "Costa, Manuel",
"login": "alejandromumo",
"company": "CERN"
}
print(serialize_author(gh_data))
gh_data = {
"name": "Mr, Da Costa, Manuel Alejandro",
"login": "alejandromumo",
"company": "CERN"
}
print(serialize_author(gh_data))
```
There are some "ugly" scenarios. I opened an …
> github: fixed authors serialization.

- invenio_rdm_records/resources/serializers/bibtex/schema.py
- tests/resources/serializers/test_bibtex_serializer.py
Records created by GitHub release don't have `creator.given_name` field. `creator.name` is a computed field (`family_name` + `given_name`)
* closes https://github.com/zenodo/rdm-project/issues/403
> serializers: fix bibtex for github record-releases

- invenio_rdm_records/services/services.py
requires https://github.com/inveniosoftware/invenio-records-resources/pull/533
closes https://github.com/zenodo/rdm-project/issues/430
> Fix draft access when published record deleted

- invenio_rdm_records/resources/serializers/datacite/schema.py
- tests/resources/serializers/test_datacite_serializer.py
closes https://github.com/zenodo/rdm-project/issues/472
> datacite: fix related identifiers serialization.

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AffiliationsField/AffiliationsField.js
closes https://github.com/zenodo/rdm-project/issues/456
**NOTE** : this only closes the issue partially. The UI still has many inconsistencies that deteriorate the user experience. However, this fix at least allows the user to see both affiliations listed in the UI.
There other issues like rendering the affiliations accordion, which aggregates affiliations by name instead of ID
> deposit: fixed creatibutors affiliations select for duplicated entries.

- invenio_rdm_records/templates/semantic-ui/invenio_notifications/guest-access-request.submit.jinja
- invenio_rdm_records/templates/semantic-ui/invenio_notifications/user-access-request.submit.jinja
* closes https://github.com/zenodo/rdm-project/issues/513
During templates refactor [here](https://github.com/anikachurilova/invenio-rdm-records/commit/bc2feedbc399ea4bb24a85d04440477268cb2469?diff=split#diff-798f923640e33256f397f36ab6728df5791072e68e9295a538c3123566b160bbR17) the text of the email was changed 
Preview:
> email templates: fix access request submit templates

- invenio_rdm_records/resources/serializers/schemaorg/schema.py
- tests/resources/serializers/test_schemaorg_serializer.py
closes https://github.com/zenodo/rdm-project/issues/507
Notes:
1 - there are fields specific to some work types (e.g. `Dataset`) that we haven't implemented yet. We had them in [legacy](https://github.com/zenodo/zenodo/blob/2dbd8ca0ddf9f9ee8b73a7d8e91e6157ce187fab/zenodo/modules/records/serializers/schemas/schemaorg.py#L279) (example for Dataset). 
2 - I did not implement `access_details` as the user requested in the ticket. I could not find the definition except [this](https://f-uji.net/vocab/metadata/property/access_level). I was trying to look at their [source code](https://github.com/pangaea-data-publisher/fuji/tree/master) to see how they parse it. On this one, I also found these [docs](https://www.fairsfair.eu/fairsfair-data-object-assessment-metrics-request-comments)
> schemaorg: added fields to schema to improve fair score.

- invenio_rdm_records/resources/serializers/dublincore/schema.py
- invenio_rdm_records/resources/serializers/marcxml/schema.py
- tests/resources/serializers/test_dublincore_serializer.py
- tests/resources/serializers/test_marcxml_serializer.py
Fixes https://github.com/zenodo/rdm-project/issues/569
> serializers: don't strip html for dc and marcxml

- invenio_rdm_records/utils.py
* Skips setting the variable on every request.
> access: avoid setting `access_request_token`

- invenio_rdm_records/alembic/ff860d48fb4b_create_media_files_table.py
- invenio_rdm_records/alembic/ff9bec971d30_add_indexes.py
- invenio_rdm_records/records/models.py
* adds alembic recipe
* fixes old alembic recipe
* closes zenodo/rdm-project#640
> models: add bucket_id index

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunityListItem.js
* closes https://github.com/zenodo/zenodo-rdm/issues/727
"Verified" icon and the button preview:
Redirects to the community page:
> community selection: small ui fixes

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/FileUploader/FileUploaderArea.js
closes https://github.com/zenodo/ops/issues/359
It is not easy to display an error message from this component, therefore I just fixed the spinning wheel for now.
> files: fixed infinite spinning wheel on error.

- invenio_rdm_records/records/mappings/os-v1/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v6.0.0.json
- The mapping is stored as a string/enum in ES/OS. Using the same type
makes sure the mapping comparison is correct when performing a
mapping update.
> mappings: change "dynamic" values to string

- invenio_rdm_records/config.py
- invenio_rdm_records/services/pids/manager.py
- Closes https://github.com/zenodo/ops/issues/365
- config: safer parent PID conditional check
- pids: allow empty-string PIDs
> Fix parent PID checks

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/NewVersionButton/NewVersionButton.js
Closes https://github.com/zenodo/ops/issues/336
* The popup tooltip on the disabled "New version" button was not shown since disabled buttons do not trigger hover events.
* -> **Fixed by adding an extra `<span>` element around the button.**
* _Remark: the span is always included, even when the button is enabled._
Extra changes:
1. **Centered the tooltip** instead of the default left positioning.
2. ~~**Reworded the tooltip** to explain more in details the reason for the new versions to be disabled (as suggested in https://github.com/zenodo/ops/issues/336)~~
* ~~_Remark: I did not include a final dot `.` in the sentence (it seems that we sometimes do and sometimes don't)._~~
* ~~_Remark: The [JavaScript translations have not been updated for 2 …
> New version button disabled: add UI feedback

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsFieldItem.js
The current button order for editing creatributors is confusing, since users moving along the right hand side of the screen can accidentally delete a creatributor when they are editing a record. This PR swaps the order to put the safer (and more visually noticeable) editing option on the right hand side.
Current:
This PR:
**Reminder**
By using GitHub, you have already agreed to the …
> creatibutors: switch remove and edit button order

- invenio_rdm_records/resources/config.py
- invenio_rdm_records/resources/resources.py
- invenio_rdm_records/resources/serializers/__init__.py
- invenio_rdm_records/resources/serializers/signposting/__init__.py
- invenio_rdm_records/resources/serializers/signposting/schema.py
- invenio_rdm_records/resources/urls.py
- invenio_rdm_records/services/schemas/metadata.py
- tests/conftest.py
- tests/resources/conftest.py
- tests/resources/serializers/conftest.py
- tests/resources/serializers/test_signposting_serializer.py
- tests/resources/test_resources.py
- tests/resources/test_signposting.py
See https://github.com/inveniosoftware/rfcs/pull/73
> views: add signposting

- invenio_rdm_records/resources/serializers/dcat/datacite-to-dcat-ap.xsl
- tests/conftest.py
- tests/resources/serializers/test_dcat_serializer.py
Fixes https://github.com/zenodo/ops/issues/356
How to reproduce the problem:
* Create a record with a contributor having one of the roles: Project Leader, Project Manager, Project Member
* Try to export the report to DCAT
* You will get the error `XSLTApplyError: Undefined variable` in [`invenio_rdm_records/resources/serializers/dcat/__init__.py`](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/resources/serializers/dcat/__init__.py#L100)
This pull request fixes this bug.
FYI, I created a pull request upstream with the same fix: https://github.com/ec-jrc/datacite-to-dcat-ap/pull/8
_-> I did copy the code from …
> serializers: DataCite to DCAT-AP: fix missing prov namespace for contributors project roles

- invenio_rdm_records/resources/serializers/marcxml/schema.py
- tests/resources/serializers/test_marcxml_serializer.py
Fixes https://github.com/zenodo/ops/issues/395
* Wrong subfield code:
* According to the [MARC 21 documentation for 542](https://www.loc.gov/marc/bibliographic/bd542.html), the subfield `$a` currently used is for "Personal creator".
* We used to put the information is the subfield `$l` in the old Zenodo and it seems to be more correct.
* This pull request puts back this information in the correct subfield.
* Wrong value:
* The value for this tag used to be `open` in the old Zenodo.
* The value is now `public`.
* This pull request takes the information from `access.status` instead of `access.record` to get the right value.
* However, in the [old Zenodo we used to get this information from metadata.access_right](https://github.com/zenodo/zenodo/blob/m …
> serializers: marcxml: fix copyright status (542) wrong key and value

- tests/resources/serializers/test_marcxml_serializer.py
Close https://github.com/zenodo/ops/issues/417
Add test.
Note: this journal field is handled via https://github.com/inveniosoftware/invenio-rdm-records/blob/74216f996fc68f146fdca4f00c519250efb286ba/invenio_rdm_records/contrib/journal/processors.py#L91-L124
**Reminder** …
> test: add journal:journal custom field to full record test

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/oaipmh/details/LinksTable.js
Every pull request in this repository shows inline ESLint annotations for these two problems:
* fetchFormats should be placed after componentDidMount
* Array.prototype.map() expects a return value from arrow function
This pull requests solves these 2 issues.
:warning: **DISCLAIMER: I did not do any manual testing, but I feel like the changes are harmless.** :warning: 
**Reminder**
By …
> Fix ESLint problems on oaipmh/details/LinksTable.js

- invenio_rdm_records/config.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/dumpers/__init__.py
- invenio_rdm_records/records/dumpers/combined_subjects.py
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/services/facets.py
- setup.cfg
- tests/records/dumpers/test_combined_subjects_dumper.py
- tests/records/test_records_communities.py
- :warning: depends on https://github.com/inveniosoftware/invenio-records-resources/pull/549 being merged and released
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/798
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1529 (at least I was able to experience the absence of that problem :sweat_smile: )
> facets: integrate combined_subjects / fix nested subject faceting

- invenio_rdm_records/services/iiif/service.py
- tests/resources/conftest.py
- tests/services/files/conftest.py
- **tests: fix broken files lock fixtures**
- **iiif: add PyVIPS support for PDF thumnbail rendering**
- If PyVIPS is available, it will be used by default to generate PDF thumbnails.
- PyVIPS uses significantly less memory to do so, since it doesn't load the entire image/PDF in memory. See also https://github.com/inveniosoftware/invenio-records-resources/pull/576 for explanation.
> Add PyVIPS support

- .github/workflows/tests.yml
- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AccessField/AccessRightField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AccessField/components/MetadataAccess.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AccessField/components/ProtectionButtons.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/Identifiers/PIDField.js
- invenio_rdm_records/config.py
- invenio_rdm_records/services/components/pids.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/pids/manager.py
- invenio_rdm_records/services/pids/providers/base.py
- invenio_rdm_records/services/pids/providers/datacite.py
- invenio_rdm_records/services/pids/service.py
- invenio_rdm_records/services/services.py
- tests/conftest.py
- tests/secret_links/test_sharing.py
- tests/services/pids/test_pids_tasks.py
- tests/services/test_rdm_service.py
- tests/services/test_service_tasks.py
- test: update test workflows
- fix: don't mint doi's on restricted
this PR will close https://github.com/inveniosoftware/product-rdm/issues/178
still open Problem:
- ~~the DOI is shown on the landing page, because the PID exists in the database~~
- ~~the DOI widget in the frontend has to be grayed out if the access is set to restricted~~
- is it really necessary to gray it out? it complicates the code. it has to be done independent of DOI but for all other pids too, to be generic in that way. The problem is, that the DOI could be already there (entry in pidstore_pid), in the InvenioRDM instance, because the record is set to restricted in the end of the drafting process. there would be a lot of work to do to make that consistent.
ATTENTION:
- to make it clear for the user, a message …
> fix restricted dois problem

- invenio_rdm_records/services/github/release.py
We have the following scenario:
- Create version 1 of a release
- Create version 2 of a release
- Delete version 2 (e.g on support)
- A new release comes in and it fails because version 2 was deleted
The error is on the `read` call (`RecordDeletedException`)
> github: read previous version also from deleted records.

- invenio_rdm_records/config.py
- invenio_rdm_records/services/customizations.py
- invenio_rdm_records/services/pids/providers/base.py
- invenio_rdm_records/services/pids/providers/datacite.py
- invenio_rdm_records/services/pids/providers/external.py
- invenio_rdm_records/services/pids/providers/oai.py
should fix https://github.com/inveniosoftware/invenio-rdm-records/issues/1652
QUESTIONS:
- is this a valid approach?
- should the default be:
- yes create parent dois
- no parent doi should be created
- the PR implements it as DATACITE_ENABLE, where it has to be explicitly turned on
the problem with that is, that it is not backwards compatible to the actual code, BUT it would be backwards compatible to v11
- i added a check to the migration script, to only create parent DOI's if datacite is enabled ([PR](https://github.com/inveniosoftware/invenio-app-rdm/blob/027a3ad02c0c6617a91a88bff72b2a539fa82556/invenio_app_rdm/upgrade_scripts/migrate_11_0_to_12_0.py#L54)). if the `PARENT_DOI_ENABLE` config will be merged this should be added to the migration script too
> parent-doi: add configuration

- invenio_rdm_records/config.py
- invenio_rdm_records/resources/serializers/iiif/schema.py
IIIF Manifest should only serve images within minimum size constraints.
> iiif: schema: only return images within size limit in manifest

- invenio_rdm_records/resources/iiif.py
We sometimes get notifications about internal server errors from the IIIF endpoint, caused by an unhandled `PIL.Image.DecompressionBombError: Image size (5179329012 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.`
```
Exception on /iiif/record:zvvmh-nan78:first_flood_detection.tif/full/!800,800/0/default.jpg [GET]
Traceback (most recent call last):
File "/usr/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
response = self.full_dispatch_request()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
rv = self.handle_user_exception(e)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
rv = …
```
> IIIF: handle DecompressionBombError

- invenio_rdm_records/services/customizations.py
- tests/services/test_rdm_service.py
The fix for the parent doi configuration https://github.com/inveniosoftware/invenio-rdm-records/pull/1740 broke the "required" parameter for the pid provider. Previously you could have a pid provider that was active (shows up in the deposit form), but not required (pid would only be minted if something was entered). Because the check for "required" was removed, this stopped working. A test is also included.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/memb …
> Fix pid required feature

- invenio_rdm_records/records/processors/tiles.py
* Creates a copy of the files list to be iterated since we might be
modifying the underlying dictionary while processing tiles.
> processors: fix tiles files iteration

- invenio_rdm_records/resources/iiif.py
* this closes
https://github.com/inveniosoftware/invenio-app-rdm/issues/2472
* the RecordDeletedException should be catched and hided from the user
NOTE: this has to be backported to v10.7.X to be included into v12
> fix: abort on record deletion exception

- invenio_rdm_records/resources/serializers/signposting/schema.py
- tests/resources/serializers/test_signposting_serializer.py
- fix for v12
This will address the "glitch" mentioned in https://signposting.org/adopters/#invenio
> signposting: generate 1 link context object for metadata

- invenio_rdm_records/services/communities/service.py
* the set branding didn't work at all. it didn't work for rebranding if
a default already exists and it didn't work if no branding exists at
all.
* the default property of the CommunitiesRelationManager needs a string.
it can't handle a dict.
it close https://github.com/inveniosoftware/invenio-rdm-records/issues/1703
> fix(community): set branding

- invenio_rdm_records/services/community_inclusion/service.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/176
Request gets auto-submitted by system user
> record inclusion: use system identity to accept inclusion request when can_include_directly

- .github/workflows/tests.yml
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/package.json
- **ci: use reusable workflows**
- **js: fix jest missing globals**
It looks like the `enzyme-to-json` module was installing some weird mix of dependencies that didn't play well with how `react-scripts`/`jest` runs the tests. From what I understand, we're not doing snapshot testing, in which case I don't think we need this dependency at all.
> Fix JS tests

- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/pids/service.py
- tests/resources/test_serialized_links.py
- Closes https://github.com/zenodo/zenodo-rdm/issues/523
- **ci: use reusable workflows**
- **pids: fix parent DOI link generation**
- Adds a new `{self/parent}_doi_html` link, pointing to `{ui}/doi/{doi}`
Note that this PR is somewhat of a breaking change since it changes how `links.parent_doi` is generated:
- Before this PR: `https://my-site.com/doi/{parent_doi}`
- After this PR: `https://doi.org/{parent_doi}`
I think this was a bug/mistake to begin with since it doesn't make sense to render in the UI a link to `/doi/{doi}` for reuse/sharing purposes. The `/doi/{doi}` URL, though, is useful when registering the DOI with DataCite.
> Fix parent DOI link generation

- invenio_rdm_records/services/config.py
- tests/resources/test_serialized_links.py
Added links for thumbnails in RDMRecordServiceConfig
_/api/records/228_
```json
"thumbnails": {
"10": "https://127.0.0.1:5000/api/iiif/record:228:Screenshot 2024-08-15 at 17.24.39.png/full/^10,/0/default.png",
"50": "https://127.0.0.1:5000/api/iiif/record:228:Screenshot 2024-08-15 at 17.24.39.png/full/^50,/0/default.png",
"100": "https://127.0.0.1:5000/api/iiif/record:228:Screenshot 2024-08-15 at 17.24.39.png/full/^100,/0/default.png",
"250": "https://127.0.0.1:5000/api/iiif/record:228:Screenshot 2024-08-15 at 17.24.39.png/full/^250,/0/default.png",
"750": "https://127.0.0.1:5000/api/iiif/record:228:Screenshot 2024-08-15 at 17.24.39.png/full/^750,/0/default.png",
"1200": "https://127.0.0.1:5000/api/iiif/record:228:Screenshot 2024-08-15 at …
```
> config: added links for thumbnails

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/PublishButton.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/SubmitReviewButton.js
**Issue**
On Zenodo, we have seen multiple inclusion requests being created for records that have "Pending" files. When the receiver tries to accept the request - and publish the record - it fails and does not show any useful information for the user. 
**How to replicate**
1. Create a draft
2. Fill in the required metadata
3. Select a community
4. Add a file but don't let it finish (e.g. use network throttling or simply reload the page)
5. Validate that the button "Submit" is enabled
**Changes**
* Refactored isDisabled function in PublishButton and SubmitReviewButton components to check if all files are finished uploading before enabling the button.
* Passed filesState instead of just the number of files to the function.
* Added a check for non-finished files.
* Added early returns to …
> (UI) Publish buttons: refactored isDisabled function

- invenio_rdm_records/resources/serializers/csl/schema.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/resources/serializers/dublincore/schema.py
- invenio_rdm_records/resources/serializers/marcxml/schema.py
- invenio_rdm_records/resources/serializers/schemaorg/schema.py
- invenio_rdm_records/resources/serializers/schemas.py
- invenio_rdm_records/resources/serializers/ui/schema.py
- tests/conftest.py
- tests/resources/serializers/test_csl_serializer.py
- tests/resources/serializers/test_datacite_serializer.py
- tests/resources/serializers/test_dublincore_serializer.py
- tests/resources/serializers/test_schemaorg_serializer.py
Perform resource type vocabulary lookup only if resource type is set.
Parse dates only if they are set
**Reminder** …
> serializers: access values only if set

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/FileUploader/FileUploader.js
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2804
* Depends on https://github.com/inveniosoftware/invenio-app-rdm/pull/2815
* Display a warning for empty files, indicating they won't be included.
* Show a list of removed file names in the warning.
* This feature is controlled by `records-resources-allow-empty-files` config value.
* Continue uploading other files while showing the warning message.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/arch …
> UI: Handle Empty File Uploads in FileUploader

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/PublishButton.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/SubmitReviewOrPublishButton.js
Check the `can_publish` permission to determine the rendering of the publish button on the front end.
A tool tip will be shown on hover, when the publish button is disabled.
No permission:
Missing fields:
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license …
> deposit: check permission and set disable tooltip for publish button

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AccessField/AccessRightField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AccessField/components/MetadataAccess.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AccessField/components/ProtectionButtons.js
- fix: propTypes warning
- fix: propTypes warning
> js remove warnings

- invenio_rdm_records/records/mappings/os-v1/rdmrecords/records/record-v7.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v7.0.0.json
* Addresses #1807.
* Fixes that multiple values for ``metadata.locations.features``.
Switching `doc_values` off implies that we cannot perform aggregations on the `metadata.locations.features` field. That is fine since we're anyways not doing this at the moment, but should be addressed properly in the future.
> mappings: disable doc_values for geo_shape fields

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunitySelectionSearch.js
Partially closes inveniosoftware/invenio-communities#1227
The "Search in all communities" input in the community front page is currently auto-focused (see linked issue).
While it makes sense for the auto-focus to be present in a model, it does not in a community front page where this is not the only input and it is lower in the page.
**Frontend**
**Reminder**
By using GitHub, you have already agreed …
> community: added autofocus prop to CommunitySelectionSearch

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunitySelectionSearch.js
Partially fixes inveniosoftware/invenio-communities#1227
*!! MAKE SURE TO HIDE WHITESPACE !!*
Now that the `CommunitySelectionSearch` is used in the community front page (see linked issue), there might not be an authenticated user and the myCommunities tab might not make sense.
One option could be for the component to fetch an endpoint to determine if a user is authenticated or not, but here we are choosing to delegate this responsibility to the user of the component.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an …
> community: added myCommunitiesEnabled prop to CommunitySelectionSearch & 📦 release: v15.6.0

- invenio_rdm_records/requests/user_moderation/actions.py
- invenio_rdm_records/requests/user_moderation/tasks.py
- invenio_rdm_records/requests/user_moderation/utils.py
- invenio_rdm_records/services/communities/components.py
- invenio_rdm_records/services/components/verified.py
- tests/requests/test_user_moderation_actions.py
* Use search results to determine the user's list of records.
* Use a TaskOp and Unit of Work to avoid sending Celery tasks immediately.
* Add a cleanup task that will perform a more thorough check using the
DB to lookup the user's records.
> user_moderation: use search for faster actions

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositRecordSerializer.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositRecordSerializer.test.js
Add fields present in the response to record deserializer in the UI.
Added fields `created`, `updated`, `revision_id`
Two additional fields are part of the response but not part of the deserializer:
- `is_draft`: since the context is the deposit page, it should be clear we are dealing with a draft.
- `expires_at`: not relevant for a draft
Could still add these two fields just to be complete. …
> deposit: add missing fields to record deserializer

- invenio_rdm_records/config.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/services/communities/components.py
- invenio_rdm_records/services/communities/moderation.py
- tests/requests/conftest.py
- Closes #1861.
- Adds a new `RRM_CONTENT_MODERATION_HANDLERS` config variable to allow
for configuring multiple handlers for the different write actions.
> components: make content moderation configurable

- setup.cfg
- tests/services/schemas/test_publication_date.py
* tests: fix EDTF interval with unknown start/end
* After the v5.x release of the ``edtf`` package, EDTF intervals with
unknown start/end are valid.
* installation: bump babel-edtf to >=1.2.0
* This is to enforce `edtf>=5`, which has a fix for supporting EDTF
intervals with unknown start/end.
> tests: fix EDTF interval with unknown start/end

- invenio_rdm_records/config.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/jsonschemas/records/record-v6.0.0.json
- invenio_rdm_records/records/jsonschemas/records/record-v7.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v7.0.0.json
- invenio_rdm_records/services/components/__init__.py
- invenio_rdm_records/services/components/internal_notes.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/permissions.py
- invenio_rdm_records/services/queryparser.py
- invenio_rdm_records/services/schemas/metadata.py
- invenio_rdm_records/services/schemas/record.py
- tests/records/test_jsonschema.py
- tests/records/tombstone.json
- tests/resources/test_resources.py
- tests/services/components/test_internal_notes_component.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/227
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/240
> metadata: add internal notes

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AffiliationsField/AffiliationsField.js
* Fixes a bug where the selected affiliations from the dropdown do not
appear inside the input box.
NOTE: In the deposit form we still display only the first affiliation (which is fine). Also tested that publishing the record keeps the ROR ID relation link, so no problem with the serialization from/to the REST API
https://github.com/user-attachments/assets/e748db12-e22c-43c9-9486-0251c45301ba
> deposit-ui: fix creator affiliations selection display

- invenio_rdm_records/services/communities/service.py
- invenio_rdm_records/services/schemas/parent/communities.py
- tests/resources/test_resources_communities.py
- tests/resources/test_resources_record_communities.py
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2869
* Fixes the allowed values that can be passed to set/unset the default
community of a record.
* Part of the fix is to also accept an empty string ("") as a valid
value when setting the "default" field, which was a currently wrong
behavior in some UI logic.
> communities: fix set/unset of default record community

- invenio_rdm_records/collections/services/service.py
Search facets and sort options did not work with collections search, the search parameters were not passed to the record search
> search: pass search parameters

- invenio_rdm_records/requests/community_inclusion.py
- invenio_rdm_records/requests/community_submission.py
- invenio_rdm_records/services/community_inclusion/service.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/203
> requests: manage sending notifications

- invenio_rdm_records/resources/serializers/bibtex/schema.py
- invenio_rdm_records/resources/serializers/bibtex/schema_formats.py
- invenio_rdm_records/services/config.py
* Added the swhid field to the bibtex schema
closes https://github.com/zenodo/zenodo-rdm/issues/936
> config: added service schema from config

- invenio_rdm_records/services/community_records/service.py
- invenio_rdm_records/services/pids/providers/datacite.py
- tests/services/pids/providers/test_datacite_pid_provider.py
* Avoids f-strings in logging calls so that entries are easier to be
grouped.
* Adds exception info to the logged errors.
> datacite: improve error logging formatting and grouping

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositRecordSerializer.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/serializers/SchemaField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/state/actions/deposit.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/state/actions/files.js
- **deposit-ui: log errors on all deposit form actions**
* This can help with debugging unexpected non-network related errors
that might occur in the logic before/after a REST API requests.
- **deposit-ui: skip unecessary removal of empty values in serialization**
* This initial removal of empty values can be dangerous, since the
`record` at this point is a UI object representation that could
potentially include circular references or very deeply nested objects.
Since `_removeEmptyValues` is recursive this can lead to stack
overflow errors.
> deposit-ui: fix deposit form infinite recursion

- invenio_rdm_records/resources/serializers/datacite/schema.py
* Makes sure that we handle missing values for optional award fields
like "title" and "number".
> datacite: fix funding serialization for optional award fields

- invenio_rdm_records/services/github/metadata.py
For `other` type of licenses, Github sends a payload with the SPDX ID set to `NOASSERTION`. 
```python
'license': {
'key': 'other',
'name': 'Other',
'spdx_id': 'NOASSERTION',
'url': None,
}
```
> github: map license NOASSERTION to other

- invenio_rdm_records/records/api.py
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/records/record-v7.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v7.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v6.0.0.json
- invenio_rdm_records/resources/serializers/dcat/__init__.py
- invenio_rdm_records/resources/serializers/dcat/schema.py
- tests/resources/serializers/test_dcat_serializer.py
Included subject identifiers in datacite schema to extract the URI
Partially fixes: https://github.com/inveniosoftware/invenio-rdm-records/issues/1889
**Frontend**
**Reminder**
1. You license your contribution …
> serializer: updated subjects and affiliations links in dcat

- invenio_rdm_records/services/community_records/service.py
* Adds `scan` and `scan_params` arguments to
`CommunityRecordsService.search(...)`, to allow for serving scan
results (but only via the service).
> community-records: allow scan search

- invenio_rdm_records/resources/serializers/bibtex/schema.py
- tests/resources/serializers/test_bibtex_serializer.py
The output of a bibtex export is wrong right now. Note the field `url` does not have a comma in the end:
```
@software{daniel_hay_guest_2024_14276439,
author       = {Daniel Hay Guest and
Joshua Wyatt Smith and
Michela Paganini and
Michael Kagan and
Marie Lanfermann and
Attila Krasznahorkay and
Daniel Edison Marley and
Aishik Ghosh and
Benjamin Huth and
Matthew Feickert},
title        = {lwtnn/lwtnn: v2.14.1},
month        = dec,
year         = 2024,
publisher    = {Zenodo},
version      = {v2.14.1},
doi          = {10.5281/zenodo.14276439},
url          = {https://doi.org/10.5281/zenodo.14276439}
swhid        = {swh:1:dir:e8e8cd6fad6becd5e8b193c1148f94e023df3bae
;origin=https://doi.org/10.5281/zenodo.597221;visi
t=swh:1:snp:fe7e271159192d7ee02e85798322462a200620 …
```
> bibtex: add trailing comma in url field

- invenio_rdm_records/records/mappings/os-v1/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/records/record-v7.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v7.0.0.json
* Closes https://github.com/inveniosoftware/invenio-communities/issues/1264
* Adds the missing `identifiers` mapping field to community
organizations.
> mappings: add missing `identifiers` to community orgs

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositApiClient.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/PublishButton.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/Identifiers/PIDField.js
- invenio_rdm_records/config.py
- invenio_rdm_records/records/api.py
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/services/components/pids.py
- tests/services/components/test_pids_component.py
- tests/services/test_rdm_service.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/163
If DOI is required: 
If DOI is not required:
Different options overview:
Errors displaying that DOI was needed, but was not reserved (on publish of the draft):
> doi: handle UI for optional DOI feature

- invenio_rdm_records/resources/serializers/bibtex/schema.py
- tests/resources/serializers/test_bibtex_serializer.py
* Fixes #1910 
* See description in linked issue
**Frontend**
**Reminder** …
> serializers: bibtex: year and month using publication date

- invenio_rdm_records/resources/serializers/bibtex/schema.py
- tests/resources/serializers/test_bibtex_serializer.py
* Fixes #1914 
* See description in linked issue
**Frontend**
**Reminder** …
> serializers: bibtex: Conference proceeding to proceedings

- invenio_rdm_records/resources/serializers/bibtex/schema.py
- tests/resources/serializers/test_bibtex_serializer.py
* Fixes #1916 
* See description in linked issue
**Frontend**
**Reminder** …
> serializers: bibtex: Conference paper not falling back to proceedings

- invenio_rdm_records/services/communities/moderation.py
> fix: use uow not self.uow

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/Identifiers/PIDField/components/OptionalDOIoptions.js
On new upload, unreserving a local DOI was not re-enabling all options. This PR refactors the relevant code to fix that.
> optional-doi: fix new upload disabled states

- invenio_rdm_records/resources/serializers/ui/schema.py
- tests/resources/serializers/test_ui_serializer.py
This PR updates the UI Serializer's GeometrySchema to handle Polygon features.
It addresses the bug in #1918 
**Frontend**
> Allow UISerializer to serialize Polygon locations in addition to Points

- invenio_rdm_records/services/communities/components.py
- invenio_rdm_records/services/config.py
- tests/resources/test_iiif_image_api.py
- tests/services/schemas/test_version.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/320
* closes https://github.com/inveniosoftware/rfcs/issues/88
{+key} was keeping special characters unescaped by uritemplate
Tested locally upload of files within a directory, it seems to work fine.
> services: proper escape the fiels key in links generation

- invenio_rdm_records/resources/serializers/__init__.py
- invenio_rdm_records/resources/serializers/signposting/__init__.py
- invenio_rdm_records/resources/serializers/signposting/schema.py
- tests/resources/serializers/test_signposting_serializer.py
* Partially fixes inveniosoftware/invenio-app-rdm#2937
* Required for inveniosoftware/invenio-app-rdm#2938
* See description in linked ticket
**Frontend**
**Reminder**
1. You license your contribution under the …
> views: FAIR signposting level 1 support & remove linkset link to itself

- invenio_rdm_records/resources/iiif.py
I notcied that IIIF info requests are not being proxied, this is due to the wrong value of request.endpoint being checked in should_proxy(). 
Additionally, I don't see any issues in our testing with enabling the (currently commented out) iiif.image_base - which also works when corrected to iiif.base. I will update this PR switching that on if no objections? 
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s …
> IIIF: info request not being proxied

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunityHeader/CommunityHeader.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/SubmitReviewButton.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/SubmitReviewOrPublishButton.js
- invenio_rdm_records/requests/community_inclusion.py
- invenio_rdm_records/requests/community_submission.py
- invenio_rdm_records/requests/entity_resolvers.py
- invenio_rdm_records/resources/args.py
- invenio_rdm_records/services/access/service.py
- invenio_rdm_records/services/communities/components.py
- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/review/service.py
- invenio_rdm_records/services/search_params.py
- tests/resources/test_resources.py
- tests/resources/test_serialized_links.py
- tests/services/test_service_review.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1948
> resources: add param to filter shared with my uploads

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/customFields/Imprint.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/customFields/Thesis.js
- invenio_rdm_records/contrib/imprint/custom_fields.py
- invenio_rdm_records/contrib/imprint/processors.py
- invenio_rdm_records/contrib/thesis/custom_fields.py
- invenio_rdm_records/resources/serializers/ui/schema.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/310
This PR adds new fields to the imprint section
- Edition is important to characterize books
This PR also does an initial expansion of thesis fields.
- The awarding department and type of thesis are both important to identify a specific thesis 
This is a breaking change for thesis, since the thesis field was structured differently from the other publication custom fields and wasn't set up to support additional subfields. This change makes the thesis field consistent with the others, but will require current v12 users of this field to do an upgrade. I'm not sure what's needed to support that or if folks will think it's worth it.
Ticks in all boxes and 🟢 on all GitHub actions status …
> Add edition to imprint  fields and initial thesis fields

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsField.js
* Fixes inveniosoftware/invenio-rdm-records#1980
* Will be backported to the `maint-17.x` branch
**Frontend**
**Reminder** …
> deposit-ui: creatibutors: support general new error format with severity

- invenio_rdm_records/administration/views/oai.py
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/components/CommunitySelectionModal/CommunityListItem.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/ComingSoonField/ComingSoonField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsFieldItem.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/FileUploader/FileUploaderArea.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/License/LicenseModal.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/TitlesField/AdditionalTitlesField.js
- invenio_rdm_records/contrib/codemeta/custom_fields.py
- invenio_rdm_records/contrib/journal/custom_fields.py
- invenio_rdm_records/contrib/meeting/custom_fields.py
- invenio_rdm_records/jobs/jobs.py
- invenio_rdm_records/oaiserver/services/schema.py
- invenio_rdm_records/requests/access/requests.py
- invenio_rdm_records/resources/serializers/cff/schema.py
- invenio_rdm_records/resources/serializers/schemaorg/schema.py
- invenio_rdm_records/resources/serializers/utils.py
- invenio_rdm_records/services/communities/service.py
- invenio_rdm_records/services/community_inclusion/service.py
- invenio_rdm_records/services/github/release.py
- invenio_rdm_records/services/pids/errors.py
- invenio_rdm_records/services/pids/providers/base.py
- invenio_rdm_records/services/services.py
Mark missing strings for translations
**Frontend**
**Reminder**
2. You agree that you have the right to license your …
> i18n: Mark Strings for Translations

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/License/LicenseModal.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/License/NoLicenseResults.js
* add pagination and mode switch
* prevent modal jumping
* aligned styling with funding modal in invenio-vocabularies
* closes: https://github.com/inveniosoftware/invenio-app-rdm/issues/2691
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including …
> deposit-ui: align license with funding modal

- invenio_rdm_records/services/config.py
Invenio-records-resources will not provide default `file_links_{item,list}`
values anymore, because with the usage of `invenio_url_for` those default values cannot
be generic. Links need a specific endpoint which the default config
cannot provide (doesn't provide a blueprint for starters). So to prevent
breakage when invenio-records-resources is released and invenio-rdm-records
uses it (see usage change in this PR) before its own code has been changed, we need to make the pre-emptive change in this PR.
> file_links: prepare for changes in invenio-records-resources [+]

- invenio_rdm_records/tokens/resource_access.py
- tests/conftest.py
- tests/services/schemas/test_publication_date.py
- tests/tokens/test_resource_access.py
This backports https://github.com/inveniosoftware/invenio-rdm-records/pull/2005/commits/7184dca53d6a63b61ee931d54adcd2439f6771cb to fix tokens on PyJWT 2.1+
It also includes https://github.com/inveniosoftware/invenio-rdm-records/pull/2005/commits/03db56d9fcc0423f1c5b8d61fa22a6227916b31b and part of https://github.com/inveniosoftware/invenio-rdm-records/commit/f9b7a58bf7fd70020afdc3e0260e7aff7deabccf to fix CI tests. …
> Backport tokens: disable "sub" verification

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CopyrightsField/CopyrightsField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CopyrightsField/index.js
- invenio_rdm_records/records/jsonschemas/records/record-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v1/rdmrecords/records/record-v7.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/drafts/draft-v6.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v7.0.0.json
- invenio_rdm_records/resources/serializers/datacite/schema.py
- invenio_rdm_records/services/schemas/metadata.py
- tests/resources/serializers/test_datacite_serializer.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/381
* proposal of the solution to add copyrights field, discussed on the 8th of April telecon
* I tried to apply what we came up with in the breakout room and:
*  I explored the possibility of adding the field alongside license field. Unfortunately the current implementation of license field is a bit too rigid to handle this, license field would need to be refactored (unfortunately this is not feasible in the scope of this PR)
* putting the field inside the modal requires some thoughts and design on the UX of representing the current value when updating the record
* explored adding the value to datacite serializer, it seems we don't have a field to accommodate it at the moment …
> metadata: add copyrights

- invenio_rdm_records/services/results.py
Sometimes, keys relevant to the serialization process are not included inside ``_source``, i.e. "highlight." By adding ``hit.meta`` as part of the serializer context, we make them available without the risk of name collision.
> services: include Opensearch meta in the results

- CHANGES.rst
- invenio_rdm_records/services/schemas/quota.py
On the administration panel, the `notes` field is marked as optional:
However, if this value is omitted, this may result in the `data` not having a `notes` field at all, which crashes the service layer here: https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/services/services.py#L694
> schemas: set default value for notes in quota increases

- invenio_rdm_records/records/mappings/os-v1/rdmrecords/records/record-v7.0.0.json
- invenio_rdm_records/records/mappings/os-v2/rdmrecords/records/record-v7.0.0.json
- invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v6.0.0.json
* Having object-level fields in this setting caused issues with the
OAI-PMH percolator index complaining about "No field mapping can be
found for the field with name [metadata.funding.award.subjects]"
when indexing percolator queries to it.
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/388
> mappings: remove objectfields from "index.query.default_field" settings

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositApiClient.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/errors/FormFeedback.js
Global server errors of the format `{status: 400, message: 'Error'}` were not displaying in the deposit form. This PR fixes that.
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/2049
> deposit: fix global server errors in frontend

- CHANGES.rst
- invenio_rdm_records/__init__.py
- invenio_rdm_records/resources/config.py
- invenio_rdm_records/services/generators.py
- invenio_rdm_records/services/permissions.py
- setup.cfg
- tests/secret_links/test_sharing.py
This PR implements changes from RFC 0072 - introduction of pluggable transfer types. `IfFileIsLocal` has been
removed in favour of more generic `IfTransferType`. It handles only the backend part, frontend part is 
in PR #1930 .
Note: needs https://github.com/inveniosoftware/invenio-records-resources/pull/604
**Frontend**
**Reminder** …
> Implementation of RFC 0072 - Pluggable transfer types - backend

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/FileUploader/FileUploaderArea.js
As you cannot select multiple files to preview, it is incorrect to use a checkbox here
Before and after
Message before
Message after
**Frontend**
**Reminder**
1. You license your contribution …
> UX: change from checkbox to radio

- tests/services/files/test_deleted_record_files.py
The order of file permission checks were changed here https://github.com/inveniosoftware/invenio-records-resources/pull/629, which changes the error that is returned for setting content on a non-existant file.
**Reminder**
1. You license …
> tests: update error to reflect records-resources file permission change

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AccessField/components/AccessMessage.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/AccessField/components/EmbargoAccess.js
Currently, the dates in AccessRights component, are not being localized based on the language selected in the app and we would like to have it consistent i.e. if I select Czech language, I would like the dates to also be localized to that language. This is a minor modification, that uses locale set in i18next. Please let us know if it would be OK for you. Thanks!
> localizing dates based on application selected locale

- invenio_rdm_records/resources/config.py
- tests/resources/serializers/test_signposting_serializer.py
* Exposes the Data Package serializer under a JSON-LD serialization with
the appropriate profile parameter.
> records-api: add Data Package serializer

- invenio_rdm_records/services/permissions.py
- tests/conftest.py
- tests/resources/test_draft_file_permissions.py
([See PR in docs for context](https://github.com/inveniosoftware/docs-invenio-rdm/pull/737#discussion_r2156833316))  
This fix restricts RDM permissions to only include the local and multipart transfer types in the default permissions. Users can still enable additional transfer types by following the documentation steps, which involve:  
1. Overriding the permission policy  
2. Setting up allowed domains in the `invenio.cfg` file  
This PR also adds tests demonstrating that fetch and remote transports are disabled by default.  
**Note**: This PR depends on [invenio-drafts-resources#307](https://github.com/inveniosoftware/invenio-drafts-resources/pull/307).  
* If you have added [third-party code …
> fix: Disabled remote and fetch transport in permissions

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsField.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsFieldItem.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsModal.js
We would like to use the creatibutor component for our apps as well. Generally, we really like the look/functionality. We only have small issue, because it is not possible to make any, relevant customizations. This PR keeps 100% the current behavior of the app. The only change is:
1. Added overridable blocks (for our case, certain things as affiliations for the Organizational type of creatibutors does not make sense).
2. Passing three functions as props (to serializeSuggestions, and to serialize and deserialize creatibutors). These are by default undefined and the ones already existing are used by default. 
The issue can be for example, we have more types of identifiers and also our static folder might have different structure (for icons and such). …
> added overridable blocks and passing serializing functions as props

- tests/fixtures/load_error/test_vocabularies_load_error.py
With the pkg_resources replacement PR https://github.com/inveniosoftware/invenio-rdm-records/pull/2082, on Python 3.9 the entry point order can change. This makes the test not care about the order of the error message.
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including …
> tests: have fixture test ignore load order

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/CreatibutorsField/CreatibutorsFieldItem.js
- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/License/LicenseFieldItem.js
This PR reverts https://github.com/inveniosoftware/invenio-rdm-records/pull/1784 and re-implements https://github.com/inveniosoftware/invenio-rdm-records/pull/1389 with the addition of the license field.
The current button order with Remove on the far right makes it too easy to accidentally delete a creatributor when editing a record.  It also isn't consistent with the button order guidelines https://inveniordm.docs.cern.ch/develop/best-practices/ui/#button-colors-and-order
Change in this PR:
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please …
> deposit: change creatributor and license item button order

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/UppyUploader/RDMUppyUploaderPlugin.js
* the code tried to adjust possible part sizes based on the max file size setting in the RDM configuration. This conflicted with the uppy plugin's internal chunking.
* this fix always computes part sizes from AWS limits to be in sync with uppy internals. See [uppy implementation](https://github.com/transloadit/uppy/blob/main/packages/%40uppy/aws-s3/src/MultipartUploader.ts#L130)
This fixes https://github.com/inveniosoftware/invenio-app-rdm/issues/3091
**Frontend** …
> fix: conflicting s3 part size for 1M-5M files

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/DeleteButton/DeleteButton.js
It's missing the icon currently
Before/After
Other button states that were missing the icon previously
> UI: add icon to delete button

- invenio_rdm_records/resources/serializers/schemaorg/schema.py
This chases the awards schema changes from Invenio-Vocabularies: https://github.com/inveniosoftware/invenio-vocabularies/pull/429
> fix(schemaorg): chase award schema relaxation from Invenio-Vocabularies

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/fields/FileUploader/FileUploaderArea.js
This is relevant for the multipart file upload with local file storage, where the checksum gets calculated in a background task after finalizing the upload.
See also: https://github.com/inveniosoftware/invenio-records-resources/pull/650
> deposit-form: add fallback message if checksum is not yet available

- invenio_rdm_records/services/config.py
- invenio_rdm_records/services/sort.py
Currently the community records search uses the same search options as the record search, which means that they both currently de-rank records from unverified users. This creates confusion and frustration in community administrators as they review and accept records into their communities from unverified users, and then cannot find it. Either they think that the inclusion request failed or that the search is broken for their community. To fix this, instance administrators have to verify the community members and the owners of records in that community
As records are manually reviewed before they are accepted into communities, there is no reason to apply the de-ranking in communities.
Ticks in all boxes …
> services: create RDMCommunityRecordSearchOptions

- invenio_rdm_records/resources/iiif.py
Add error handler for `flask_iiif.errors.MultimediaImageNotFound` in the IIIF resource, to get a 404 response instead of a 500.
Example URL: `https://test.researchdata.tuwien.ac.at/api/iiif/record:9tp42-0pk88:example_upload.tiff/full/!800,800/0/default.jpg`
:detective: **Note**: The file `example_upload.tiff` is actually a text file, probably that's why the IIIF file can't be found.
---
```
Exception on /iiif/record:9tp42-0pk88:example_upload.tiff/full/!800,800/0/default.jpg [GET]
Traceback (most recent call last):
File "/var/instance/.venv/lib/python3.13/site-packages/flask_iiif/api.py", line 592, in open_image
image = Image.open(source)
File "/var/instance/.venv/lib/python3.13/site-packages/PIL/Image.py", line 3580, in open
raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: …
```
> iiif: add error handler for `MultimediaImageNotFound`

- invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/controls/PublishButton/SubmitReviewModal.js
Currently we're sending a react node to the ErrorMessage, but it actually only takes an [array of messages](https://github.com/inveniosoftware/react-invenio-forms/blob/master/src/lib/elements/ErrorMessage.js#L72) via `errors`
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6 …
> fix: improve rendering of ErrorMessage
